Repository brave/brave-ios, pull requests merged in 2018-08, with the labels that each got.

#131 Tab Restore Fixes
  Client/Application/AppDelegate.swift
  Client/Frontend/Browser/BrowserViewController.swift
Labels: needsuplift

#133 Fix #132: Update Cookie Accept Policy when updated from preferences
  Client.xcodeproj/project.pbxproj
  Client/Application/AppDelegate.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/HTTPCookieStorageExtensions.swift
Labels: needsuplift

#137 Fix #108: Resolved issue with “packaging up the application” failing for Enterprise builds
  fastlane/Fastfile
Labels: needsuplift

#143 Fix #134: Remove target-specified deployment targets
  Client.xcodeproj/project.pbxproj
Labels: needsuplift

#135 Fix #73: Adds Shields menu popup UI
  BraveShared/BraveShieldState.swift
  Client.xcodeproj/project.pbxproj
  Client/Assets/Images.xcassets/shields-menu-icon.imageset/Contents.json
  Client/Assets/Images.xcassets/shields-menu-icon.imageset/brave_btn@2x.png
  Client/Assets/Images.xcassets/shields-menu-icon.imageset/brave_btn@3x.png
  Client/Assets/Images.xcassets/shields-off-menu-icon.imageset/Contents.json
  Client/Assets/Images.xcassets/shields-off-menu-icon.imageset/brave_btn_off@2x.png
  Client/Assets/Images.xcassets/shields-off-menu-icon.imageset/brave_btn_off@3x.png
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/TabLocationView.swift
  Client/Frontend/Browser/URLBarView.swift
  Client/Frontend/Popover/PopoverController.swift
  Client/Frontend/Shields/ShieldsView.swift
  Client/Frontend/Shields/ShieldsViewController.swift
Labels: needsuplift

#145 Fix #144: Get project to compile when building for testing/running tests
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/xcshareddata/xcschemes/Fennec.xcscheme
  Client.xcodeproj/xcshareddata/xcschemes/ReadingList.xcscheme
  Client.xcodeproj/xcshareddata/xcschemes/Telemetry.xcscheme
  Client/Configuration/Fennec.xcconfig
  ClientTests/ActivityStreamTests.swift
  ClientTests/ClientTests.swift
  ClientTests/CustomSearchEnginesTest.swift
  ClientTests/NavigationRouterTests.swift
  ClientTests/PanelDataObserversTests.swift
  ClientTests/ProfileTest.swift
  ClientTests/ResetTests.swift
  ClientTests/SearchEnginesTests.swift
  ClientTests/SearchTests.swift
  ClientTests/SyncStatusResolverTests.swift
  ClientTests/TabManagerTests.swift
  ClientTests/UIImageViewExtensionsTests.swift
  SharedTests/AuthenticationKeychainInfoTests.swift
  StorageTests/TestSQLiteReadingList.swift
Labels: needsuplift

#151 Fix #109: Only show green lock for fully secure sites
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/TabLocationView.swift
  Client/Frontend/Browser/URLBarView.swift
  Shared/AppConstants.swift
Labels: security

#193 Fix #192: Remove unneeded deployment config
  Client.xcodeproj/project.pbxproj
Labels: bug
