Repository brave/brave-ios, pull requests merged in 2019-09, with the labels that each got.

#1462 Fix #1461: Release Notes for 1.11.4
  CHANGELOG.md
Labels: QA/No

#1469 No Bug: Backport beta with abp-rust to development.
  CHANGELOG.md
  Client.xcodeproj/project.pbxproj
  Client/Assets/Images.xcassets/WebAuth/enter_pin.imageset/Contents.json
  Client/Assets/Images.xcassets/WebAuth/enter_pin.imageset/enterpin@2x.pdf
  Client/WebFilters/AdblockResourceDownloader.swift
  Client/WebFilters/AdblockResourcesMappings.swift
  Client/WebFilters/AdblockerType.swift
  Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift
  Client/WebFilters/ShieldStats/Adblock/Resources/ABPFilterParserData.dat
Labels: blocked

#1385 Fix #1119: Adds Bookmarklet support with validation.
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarkDetailsView.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarkFormFieldsProtocol.swift
  DataTests/BookmarkTests.swift
  Shared/BookmarkValidation.swift
  Shared/Extensions/URLExtensions.swift
  SharedTests/NSURLExtensionsTests.swift
Labels: needs security review
