Repository brave/brave-ios, pull requests merged in 2019-08, with the labels that each got.

#1311 Added support for Exclusion List for WebAuthN.
  Client/U2FExtensions.swift
  Client/WebAuthN/WebAuthnRegisterRequest.swift
Labels: needs security review

#1305 Add Release notes for 1.10
  CHANGELOG.md
Labels: release-notes/exclude

#1356 Fix #1349: Touch key dialog should be displayed once
  Client/U2FExtensions.swift
Labels: QA/Yes

#1392 Fix #1359: Updating U2f/WebAuthn modals to include site host
  Client/Assets/Images.xcassets/WebAuth/enter_pin.imageset/Artboard.png
  Client/Assets/Images.xcassets/WebAuth/enter_pin.imageset/Artboard@2x.png
  Client/Assets/Images.xcassets/WebAuth/enter_pin.imageset/Artboard@3x.png
  Client/Assets/Images.xcassets/WebAuth/enter_pin.imageset/Contents.json
  Client/Assets/Images.xcassets/WebAuth/enter_pin.imageset/enterpin@2x.pdf
  Client/Frontend/Popup/AlertPopupView.swift
  Client/U2FExtensions.swift
Labels: feature/webauthn

#1408 Fix: #1407: This adds Release notes for 1.11.3
  CHANGELOG.md
Labels: release-notes/exclude

#1343 No Bug: Updated PR template to exclude Zenhub info.
  PULL_REQUEST_TEMPLATE
Labels: blocked
