Repository brave/brave-ios, pull requests merged in 2019-07, with the labels that each got.

#1295 Fix #1268: Fix YubiKey workflow for fw 5.2.1
  Client/Frontend/Browser/UserScriptManager.swift
  Client/U2FExtensions.swift
  Client/WebAuthN/WebAuthnAuthenticateRequest.swift
  Client/WebAuthN/WebAuthnRegisterRequest.swift
Labels: feature/webauthn/security-key

#1288 Fix #661: Open in Brave now opens the first URL found in share content
  BraveShareTo/ShareToBraveViewController.swift
  BraveShared/Extensions/StringExtensions.swift
  BraveSharedTests/StringExtensionTests.swift
  Client.xcodeproj/project.pbxproj
  Client/Application/NavigationRouter.swift
Labels: needs security review

#1315 Fix #1314: Update bootstrap script to use the upstream YubiKit
  bootstrap.sh
Labels: QA/Yes
