Repository brave/brave-ios, pull requests merged in 2020-06, with the labels that each got.

#2633 No Bug: Skip job if `CI/skip` label is found on a PR
  .github/workflows/build_and_test.yml
Labels: CI/skip

#2638 Expand Rewards to three decimal places
  BraveRewardsUI/BATValue.swift
  BraveRewardsUITests/BATValueTests.swift
Labels: Epic: Rewards/Ads

#2651 Fix #2650: Save favicons in in-memory db in private mode.
  Client/Frontend/Browser/FaviconHandler.swift
  Client/Frontend/Browser/Favicons/FaviconFetcher.swift
  Data/models/Domain.swift
  Data/models/FaviconMO.swift
  DataTests/FaviconMOTests.swift
Labels: needs security review
