Repository brave/brave-ios, pull requests merged in 2020-12, with the labels that each got.

#3102 Fix #3098: Use different icon for insecure sites
  Client/Assets/Images.xcassets/Contents.json
  Client/Assets/Images.xcassets/insecure-site-icon.imageset/Contents.json
  Client/Assets/Images.xcassets/insecure-site-icon.imageset/insecure-site-icon@2x.png
  Client/Assets/Images.xcassets/insecure-site-icon.imageset/insecure-site-icon@3x.png
  Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
Labels: needs security review

#3069 Fix #2961: Problems with Sharing a PDF File / Additional Share Issues
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/TemporaryDocument.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/DownloadsViewController.swift
  Client/Frontend/Share/ShareExtensionHelper.swift
  Client/Info.plist
  ClientTests/SchemePermissionTests.swift
  Shared/Extensions/URLExtensions.swift
Labels: needs security review

#3105 Fix #3046: Add universal link support for the Brave VPN page.
  Client.xcodeproj/project.pbxproj
  Client/Application/Delegates/AppDelegate.swift
  Client/Entitlements/Beta.entitlements
  Client/Entitlements/Debug.entitlements
  Client/Entitlements/Dev.entitlements
  Client/Entitlements/Enterprise.entitlements
  Client/Entitlements/Release (AppStore).entitlements
  Client/Entitlements/Release.entitlements
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/UniversalLinkManager.swift
  ClientTests/UniversalLinkManagerTests.swift
Labels: needs security review

#3130 Fix #3113: Fetch adblock data every 6 hours.
  Client/Application/Delegates/AppDelegate.swift
  Client/Frontend/Settings/AdblockDebugMenuTableViewController.swift
  Client/WebFilters/AdblockResourceDownloader.swift
Labels: needs security review

#3141 Release notes for 1.22
  CHANGELOG.md
Labels: CI/skip

#3153 Release notes for 1.22.1
  CHANGELOG.md
Labels: CI/skip, QA/No, release-notes/exclude

#3156 Fix #3155 - Remove RTL characters from filenames
  BraveSharedTests/StringExtensionTests.swift
  Client/Frontend/Browser/DownloadQueue.swift
Labels: QA/Yes, bug, release-notes/include

#3159 Fix #3158: Fix test failure testRemoveUnicodeFromFilename
  BraveSharedTests/StringExtensionTests.swift
  Client/Frontend/Browser/DownloadQueue.swift
  ClientTests/StringExtensionsTests.swift
Labels: QA/No, bug, release-notes/exclude
