Repository brave/brave-ios, pull requests merged in 2020-04, with the labels that each got.

#1971 Fix #1963, Fix #1964 - URL bar alignment is off and secure page icon not showing
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/ErrorPageHelper.swift
  Client/Frontend/Browser/Onboarding/OnboardingRewardsAgreementViewController.swift
  Client/Frontend/Browser/Onboarding/OnboardingWebViewController.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
Labels: needs security review

#2470 Release notes for 1.15.1
  CHANGELOG.md
Labels: QA/No, release-notes/exclude

#2408 Fix #2324: Custom homepage/super referrer.
  BraveShared/Analytics/UserReferralProgram.swift
  BraveShared/BraveStrings.swift
  BraveShared/Preferences.swift
  Client.xcodeproj/project.pbxproj
  Client/Application/ClientPreferences.swift
  Client/Application/Delegates/AppDelegate.swift
  Client/Extensions/UIImageViewExtensions.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/HomePanel/CustomTheme.swift
  Client/Frontend/Browser/HomePanel/FavoritesViewController.swift
  Client/Frontend/Browser/HomePanel/NTPBackgroundDataSource.swift
  Client/Frontend/Browser/HomePanel/NTPDataSource.swift
  Client/Frontend/Browser/HomePanel/NTPDownloader.swift
  Client/Frontend/Browser/HomePanel/NTPModels.swift
  Client/Frontend/Popup/QRCodePopupView.swift
  Client/Frontend/Settings/NTPTableViewController.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Settings/ThemesSettingsViewController.swift
  Client/Frontend/Sync/SyncAddDeviceViewController.swift
  Client/Frontend/Sync/SyncQRCodeView.swift
  Client/Utils/FaviconFetcher.swift
  ClientTests/FavoritesViewControllerTests.swift
  Data/models/Bookmark.swift
  DataTests/BookmarkTests.swift
  Shared/UIColorExtensions.swift
Labels: blocked, needs security review
