Repository brave/brave-ios, pull requests merged in 2020-07, with the labels that each got.

#2696 Fix: #2695 : Add Release Notes for v1.18
  CHANGELOG.md
Labels: CI/skip

#2693 Fix Brave Ads state-level targeting crash
  BraveRewardsUI/Localized Strings/Strings.swift
  BraveRewardsUI/Settings/Ads/Details/AdsDetailsViewController.swift
Labels: Epic: Ads

#2706 Fix #2705: Add Release Notes for v1.18.1
  CHANGELOG.md
Labels: CI/skip, QA/No

#2743 Fix #2742 :Add Release notes for v1.19
  CHANGELOG.md
Labels: CI/skip, release-notes/exclude
