Repository brave/brave-ios, pull requests merged in 2021-09, with the labels that each got.

#4122 Fix - Release update to rebase against development without carplay changes.
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/Playlist/BrowserViewController+Playlist.swift
  Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift
  Client/Frontend/Browser/Playlist/Cache/PlaylistManager.swift
  Client/Frontend/Browser/PlaylistHelper.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Client/Frontend/UserContent/UserScripts/Playlist.js
  Data/models/PlaylistItem.swift
Labels: QA/No

#4041 Fix #4040: Add a separate section for history items created earlier than last month
  BraveShared/BraveStrings.swift
  Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift
  Client/Frontend/Sync/BraveCore/History/Historyv2.swift
Labels: enhancement

#4142 No Bug: Rename BraveShareTo to ShareExtension.
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/xcshareddata/xcschemes/ShareTo.xcscheme
  ShareExtension/ShareExtension.plist
  ShareExtension/ShareToBraveViewController.swift
  ShareExtension/de.lproj/InfoPlist.strings
  ShareExtension/en.lproj/InfoPlist.strings
  ShareExtension/es.lproj/InfoPlist.strings
  ShareExtension/fr.lproj/InfoPlist.strings
  ShareExtension/id-ID.lproj/InfoPlist.strings
  ShareExtension/it.lproj/InfoPlist.strings
  ShareExtension/ja.lproj/InfoPlist.strings
  ShareExtension/ko-KR.lproj/InfoPlist.strings
  ShareExtension/ms.lproj/InfoPlist.strings
  ShareExtension/nb.lproj/InfoPlist.strings
  ShareExtension/pl.lproj/InfoPlist.strings
  ShareExtension/pt-BR.lproj/InfoPlist.strings
  ShareExtension/ru.lproj/InfoPlist.strings
  ShareExtension/sv.lproj/InfoPlist.strings
  ShareExtension/tr.lproj/InfoPlist.strings
  ShareExtension/uk.lproj/InfoPlist.strings
  ShareExtension/zh-TW.lproj/InfoPlist.strings
  ShareExtension/zh.lproj/InfoPlist.strings
  fastlane/Fastfile
Labels: QA/No

#4089 Fix #4001: Add BraveTalk api.
  BraveShared/BraveStrings.swift
  BraveShared/BraveUX.swift
  Client.xcodeproj/project.pbxproj
  Client/Assets/Images.xcassets/Brave Rewards/optin_bg.imageset/Contents.json
  Client/Assets/Images.xcassets/Brave Rewards/optin_bg.imageset/optin_bg_2x.png
  Client/Assets/Images.xcassets/Brave Rewards/optin_bg.imageset/optin_bg_3x.png
  Client/Assets/Images.xcassets/Brave Rewards/optin_check_circle.imageset/Contents.json
  Client/Assets/Images.xcassets/Brave Rewards/optin_check_circle.imageset/Shape@2x.png
  Client/Assets/Images.xcassets/Brave Rewards/optin_check_circle.imageset/Shape@3x.png
  Client/Assets/Images.xcassets/rewards_onboarding_cashback.imageset/Contents.json
  Client/Assets/Images.xcassets/rewards_onboarding_cashback.imageset/rewards-onboarding-cashback_2x.png
  Client/Assets/Images.xcassets/rewards_onboarding_cashback.imageset/rewards-onboarding-cashback_3x.png
  Client/Frontend/Brave Rewards/OptIn/BraveTalkOptInSuccessView.swift
  Client/Frontend/Brave Rewards/OptIn/BraveTalkOptInSuccessViewController.swift
  Client/Frontend/Brave Rewards/OptIn/BraveTalkRewardsOptInView.swift
  Client/Frontend/Brave Rewards/OptIn/BraveTalkRewardsOptInViewController.swift
  Client/Frontend/Browser/BraveSearchScriptHandler.swift
  Client/Frontend/Browser/BraveTalkScriptHandler.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/DomainUserScript.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Client/Frontend/UserContent/UserScripts/BraveSearchHelper.js
  Client/Frontend/UserContent/UserScripts/BraveTalkHelper.js
  ClientTests/DomainUserScriptTests.swift
Labels: needs security review

#4174 Fix #4173: Fixes PrivilegedRequest to work on all iOS versions.
  Client.xcodeproj/project.pbxproj
  Client/Application/WebServer.swift
  Client/Assets/SessionRestore.html
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/PrivilegedRequest.swift
  Client/Frontend/Browser/SessionData.swift
  Client/Frontend/Browser/SessionRestoreHandler.swift
  Client/Frontend/Browser/Tab.swift
  Shared/AppConstants.swift
  Shared/Extensions/URLExtensions.swift
  Shared/PrivilegedRequest.swift
Labels: needs security review

#4024 Fix #3916: Refactor new bookmarks & history singleton APIs
  Client.xcodeproj/project.pbxproj
  Client/Application/Delegates/AppDelegate.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/FrequencyQuery.swift
  Client/Frontend/Browser/Search/SearchLoader.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarkEditMode.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarkSaveLocation.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/Settings/Brave Search/BraveSearchLogEntry.swift
  Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Client/Frontend/Settings/Clearables.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Sync/BraveCore/Bookmarks/BookmarkAPIExtensions.swift
  Client/Frontend/Sync/BraveCore/Bookmarks/BookmarkFetchers.swift
  Client/Frontend/Sync/BraveCore/Bookmarks/BookmarkNodeExtensions.swift
  Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift
  Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift
  Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift
  Client/Frontend/Sync/BraveCore/History/HistoryAPIExtensions.swift
  Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift
  Client/Frontend/Sync/BraveCore/History/Historyv2.swift
  ClientTests/SchemePermissionTests.swift
Labels: enhancement

#4196 Fix:#4195 - Add Release notes to iOS v1.31
  CHANGELOG.md
Labels: CI/skip, documentation
