Repository brave/brave-ios, pull requests merged in 2021-12, with the labels that each got.

#4649 Fix #4601 / #4645: Japan NTP Tutorial Page - Incorrect tooltip
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Client/Frontend/Browser/BrowserViewController/ProductNotifications/BrowserViewController+ProductNotification.swift
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeViewController.swift
  Client/Frontend/Settings/RetentionPreferencesDebugMenuViewController.swift
Labels: bug

#4674 Fix #4655: Add Onboarding missing code.
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
Labels: QA/No

#4718 Fix #4714: No "Yes" link or button to tap on to enable Rewards in callout screen
  Client/Frontend/Browser/Onboarding/OnboardingRewardsAgreementViewController.swift
Labels: bug

#4729 Fix #4001: Brave-Search script has the wrong name
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Client/Frontend/Browser/DomainUserScript.swift
Labels: QA/No

#4736 No Bug: Adding Visual Onboarding Repeater in Settings for Testing
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Client/Frontend/Settings/RetentionPreferencesDebugMenuViewController.swift
Labels: QA/No

#4523 Fix ##4522: Removes canvas rule on fingerprint protection
  Client/Frontend/UserContent/UserScripts/FingerprintingProtection.js
Labels: blocked
