Repository brave/brave-ios, pull requests merged in 2021-02, with the labels that each got.

#3286 No Bug: Update Readme to reflect latest iOS 12.4 minimum version bump.
  README.md
Labels: CI/skip

#3231 Fix#936: Add Support for OpenSearch(Auto/ Manual) - Search Engine Settings Screen Changes
  BraveShared/BraveStrings.swift
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift
  Client/Frontend/Browser/BrowserViewController/OpenSearch/OpenSearchEngineButton.swift
  Client/Frontend/Browser/Favorites/FavoritesViewController.swift
  Client/Frontend/Browser/Search/OpenSearch.swift
  Client/Frontend/Browser/Search/SearchEngines.swift
  Client/Frontend/Browser/Search/SearchViewController.swift
  Client/Frontend/Browser/ThirdPartySearchAlerts.swift
  Client/Frontend/Login Management/LoginListViewController.swift
  Client/Frontend/Popup/PopupView.swift
  Client/Frontend/Settings/LoginDetailViewController.swift
  Client/Frontend/Settings/Rewards Internals/QA/RewardsDebugSettingsViewController.swift
  Client/Frontend/Settings/SearchCustomEngineViewController.swift
  Client/Frontend/Settings/SearchEnginePicker.swift
  Client/Frontend/Settings/SearchQuickEnginesViewController.swift
  Client/Frontend/Settings/SearchSettingsTableViewController.swift
  Client/Frontend/Settings/SettingsTableSectionHeaderFooterView.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Strings.swift
  Client/Frontend/UserContent/UserScripts/MainFrame/AtDocumentEnd/MetadataHelper.js
  Client/Networking/NetworkManager.swift
  ClientTests/SearchEnginesTests.swift
  Shared/Extensions/URLExtensions.swift
  Shared/KeyboardHelper.swift
  Storage/PageMetadata.swift
Labels: needs security review

#3339 Release notes for 1.23
  CHANGELOG.md
Labels: CI/skip, QA/No, release-notes/exclude

#3356 Fix #3351: Javascript->JavaScript typo.
  BraveShared/BraveStrings.swift
Labels: CI/skip

#3357 Release notes for 1.23.1
  CHANGELOG.md
Labels: QA/No, release-notes/exclude
