Repository brave/brave-ios, pull requests merged in 2021-11, with the labels that each got.

#4411 Fix #3397: Add ability to search bookmarks by title or URL in the bookmarks list
  BraveShared/BraveStrings.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Client/Frontend/Sync/BraveCore/Bookmarks/BookmarkManager.swift
Labels: enhancement, Epic: Retention

#4449 No Bug: Update swiftlint script to include M1 mac directory.
  swiftlint.sh
Labels: QA/No

#4456 Add convenience method to fetch decimal balance for any token
  BraveWallet/Extensions/RpcControllerExtensions.swift
  Client.xcodeproj/project.pbxproj
Labels: QA/No

#4424 Fix #4377: Revamp 3dot menu on new tab page
  BraveShared/BraveStrings.swift
  Client/Assets/Images.xcassets/Menu/Contents.json
  Client/Assets/Images.xcassets/Menu/menu-brave-talk.imageset/Contents.json
  Client/Assets/Images.xcassets/Menu/menu-brave-talk.imageset/brave-talk.png
  Client/Assets/Images.xcassets/Menu/menu-brave-talk.imageset/brave-talk@2x.png
  Client/Assets/Images.xcassets/Menu/menu-brave-talk.imageset/brave-talk@3x.png
  Client/Assets/Images.xcassets/Menu/menu_brave_news.imageset/Contents.json
  Client/Assets/Images.xcassets/Menu/menu_brave_news.imageset/brave-news.png
  Client/Assets/Images.xcassets/Menu/menu_brave_news.imageset/brave-news@2x.png
  Client/Assets/Images.xcassets/Menu/menu_brave_news.imageset/brave-news@3x.png
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/VPNMenuButton.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
Labels: enhancement, Epic: Retention

#4460 No Bug: Fix widgets code signing for enterprise builds.
  Client.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: QA/No

#4474 Fix #4377: Make NTP menu to fit all items on the screen.
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
Labels: QA/No

#4469 Fix #4463 / #4464: Fixes the interaction of Favourites reordering with default browser modal
  Client/Frontend/Browser/New Tab Page/NewTabCenteredCollectionViewCell.swift
  Client/Frontend/Browser/New Tab Page/Sections/NTPDefaultBrowserCalloutProvider.swift
Labels: bug

#4479 No Bug: Safeguard CoreData operations more.
  Client/Application/Delegates/SceneDelegate.swift
  Client/Application/Migration.swift
  Data/models/CRUDProtocols.swift
  Data/models/DataController.swift
Labels: QA/No

#4433 Fix #4335: Deprecate ours HTTPSE in favor of the one bundled in WKWeb…
  BraveShared/BraveStrings.swift
  BraveShared/Shields/BraveShield.swift
  Client/Application/Delegates/AppDelegate.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Shields/AdvancedShieldsView.swift
  Client/Frontend/Shields/ShieldsViewController.swift
  Client/WebFilters/ContentBlocker/BlocklistName.swift
  Client/WebFilters/ContentBlocker/TrackingProtectionPageStats.swift
  Data/models/Domain.swift
  DataTests/DomainTests.swift
Labels: needs security review

#4467 Fix: #4466 - Add Release Notes for 1.32.1
  CHANGELOG.md
Labels: QA/No, CI/skip, documentation

#4510 Release notes for `1.32.2`
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip

#4533 Fix: #4524 - Add Release notes for v1.32.3
  CHANGELOG.md
Labels: QA/No, CI/skip, documentation
