Repository brave/brave-ios, pull requests merged in 2021-04, with the labels that each got.

#3516 Release notes for 1.24
  CHANGELOG.md
Labels: Epic: Cleanup, QA/No, release-notes/exclude

#3510 No Bug: Move RewardsReporting out of sandbox
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentStart/RewardsReporting.js
Labels: QA/No

#3522 Fix #3520: Update webpack to 5.32.0.
  .gitignore
  package-lock.json
  package.json
Labels: needs security review

#3607 Ref #3524: Fix typo in Playlist copy.
  BraveShared/BraveStrings.swift
Labels: QA/No
