Repository brave/brave-ios, pull requests merged in 2021-06, with the labels that each got.

#3756 Release notes for 1.26
  CHANGELOG.md
Labels: Epic: Cleanup, QA/No, release-notes/exclude

#3759 No Bug: Make the app to compile on Xcode 13 Beta 1 using old tools.
  Client/Frontend/Popup/PopupView.swift
Labels: QA/No

#3748 Fix #3681: Add Brave Search fallback native-website communication.
  BraveSharedTests/StringExtensionTests.swift
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Search/BraveSearchManager.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/UserContent/UserScripts/MainFrame/AtDocumentStart/BraveGetUA.js
  Shared/Extensions/StringExtensions.swift
Labels: needs security review

#3771 No Bug: Update BraveCore build script to use `--auto_gn_gen`
  BraveCore/build_in_core.sh
Labels: CI/skip, QA/No, release-notes/exclude

#3535 Add Brave Search engine, add BraveSearch default SE callbacks.
  Client.xcodeproj/project.pbxproj
  Client/Application/ClientPreferences.swift
  Client/Assets/SearchPlugins/bravesearch.xml
  Client/Frontend/Browser/BraveSearchHelper.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift
  Client/Frontend/Browser/DomainUserScript.swift
  Client/Frontend/Browser/Search/InitialSearchEngines.swift
  Client/Frontend/Browser/Search/OpenSearch.swift
  Client/Frontend/Browser/Search/SearchEngines.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Client/Frontend/UserContent/UserScripts/BraveSearchHelper.js
  ClientTests/InitialSearchEnginesTests.swift
Labels: needs security review

#3784 Ref #3745: Remove rich param from BraveSearch query suggestion endpoint.
  Client/Assets/SearchPlugins/bravesearch.xml
Labels: QA/No

#3837 Release notes for `1.27.1`
  CHANGELOG.md
Labels: CI/skip, Epic: Cleanup, QA/No, release-notes/exclude

#3836 Fix #3834: Adding Open Search References to Default Search Engines
  Client/Frontend/Browser/Search/InitialSearchEngines.swift
  Client/Frontend/Browser/Search/OpenSearch.swift
  Client/Frontend/Browser/Search/SearchEngines.swift
  ClientTests/SearchTests.swift
Labels: bug

#3852 Fix #3783: Remove SE and Handle Migration for existing Users
  Client/Application/ClientPreferences.swift
  Client/Application/Delegates/AppDelegate.swift
  Client/Assets/Images.xcassets/faviconYahoo.imageset/Contents.json
  Client/Assets/Images.xcassets/faviconYahoo.imageset/yahoo-jp-favicon.png
  Client/Assets/Images.xcassets/faviconYahooJP.imageset/Contents.json
  Client/Assets/Images.xcassets/faviconYahooJP.imageset/yahoo-favicon.png
  Client/Assets/SearchPlugins/yahoo-jp.xml
  Client/Assets/SearchPlugins/yahoo.xml
  Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift
  Client/Frontend/Browser/Search/InitialSearchEngines.swift
  Client/Frontend/Browser/Search/OpenSearch.swift
  Client/Frontend/Browser/Search/SearchEngines.swift
  Client/Frontend/Settings/SearchSettingsTableViewController.swift
  ClientTests/InitialSearchEnginesTests.swift
  ClientTests/SearchEnginesTests.swift
Labels: enhancement
