Repository brave/brave-ios, pull requests merged in 2021-08, with the labels that each got.

#3951 Fix #3950: Selecting a Bookmark should close Settings Menu
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
Labels: bug

#3960 Fix #3958: Do not reset to default when global settings are changed
  Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
Labels: enhancement

#3996 Fix #3995: Browser crash when clear history voice command is given with tab tray open
  Client/Frontend/Browser/BrowserViewController.swift
Labels: bug

#3998 Fix #3997: Browser crash when clear history voice command is given with tab tray open in PB only mode
  Client/Frontend/Browser/BrowserViewController.swift
Labels: bug

#3703 Fix #3227: Implement History Sync
  BraveShared/BraveStrings.swift
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Client/Application/ClientPreferences.swift
  Client/Application/Migration.swift
  Client/Assets/Images.xcassets/Menu/emptyHistory.imageset/Contents.json
  Client/Assets/Images.xcassets/Menu/emptyHistory.imageset/historyEmpty@2x.png
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+UIDropInteractionDelegate.swift
  Client/Frontend/Browser/BrowserViewController/Sync/BrowserViewController+CoreMigration.swift
  Client/Frontend/Browser/FrecencyQuery.swift
  Client/Frontend/Browser/FrequencyQuery.swift
  Client/Frontend/Browser/Search/SearchLoader.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/Browser/Toolbars/ToolbarUrlActionsDelegate.swift
  Client/Frontend/Settings/Clearables.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Sync/BraveCore/Bookmarks/BookmarkFetchers.swift
  Client/Frontend/Sync/BraveCore/Bookmarks/BookmarkModelStateObserver.swift
  Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift
  Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift
  Client/Frontend/Sync/BraveCore/BraveServiceStateObserver.swift
  Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift
  Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift
  Client/Frontend/Sync/BraveCore/History/HistoryServiceStateObserver.swift
  Client/Frontend/Sync/BraveCore/History/Historyv2.swift
  Client/Frontend/Sync/SyncSettingsTableViewController.swift
  Client/Frontend/Sync/SyncWelcomeViewController.swift
  Client/Frontend/Sync/WebFilter/Bookmarks/Bookmarks.html
  Client/Frontend/Sync/WebFilter/Bookmarks/BookmarksInterstitial.swift
  Data/models/History.swift
  Shared/Extensions/URLExtensions.swift
  SharedTests/NSURLExtensionsTests.swift
  package-lock.json
  package.json
Labels: Epic: Sync, needs security review

#4003 No Bug: Update SPM Package.resolved
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: QA/No

#4005 Fix #4004: Always request desktop site is not left aligned correctly with other menu items
  Client/Assets/Images.xcassets/Settings/settings-desktop-always.imageset/settings-desktop-always@2x.png
  Client/Assets/Images.xcassets/Settings/settings-desktop-always.imageset/settings-desktop-always@3x.png
Labels: bug

#4007 Fix #4006: Fix Typo inside History Migration Error Pop-Up
  BraveShared/BraveStrings.swift
Labels: bug

#4013 Fix #4009: Disable History sync when user switches to PB only
  BraveShared/BraveStrings.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
Labels: enhancement

#4018 No Bug: Update the localized text for History Migration Error
  BraveShared/BraveStrings.swift
  Client/Frontend/Browser/BrowserViewController/Sync/BrowserViewController+CoreMigration.swift
  Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift
Labels: QA/No

#4025 Release notes for `1.29`
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, Epic: Cleanup, CI/skip

#4028 Fix #4027: History syncs even when browser is set to PB only mode
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
Labels: bug

#4048 [No Bug]: Removing the unused folder sand files inside Frontend
  Client/Frontend/ContentBlocker/BlocklistName.swift
  Client/Frontend/Login/LoginViewController.swift
  Client/Frontend/Menu/BookmarksViewController.swift
  Client/Frontend/Menu/HomeMenuController.swift
Labels: QA/No

#4054 No Bug: Update CI workflow to use macOS 11 & Xcode 12.5
  .github/workflows/build_and_test.yml
  Client/WebFilters/ContentBlocker/Lists/does-it-compile.swift
  Client/WebFilters/ContentBlocker/Lists/test-compile-all-lists.sh
  fastlane/Fastfile
Labels: QA/No, Epic: CI/Tests

#4051 Fix:#4029 - Add Release Notes to 1.30
  CHANGELOG.md
Labels: CI/skip, documentation

#4062 Fix #3755, fix #4061: Update root certificates.
  Client.xcodeproj/project.pbxproj
  Client/Assets/Certificates/AmazonRootCA1.cer
  Client/Assets/Certificates/AmazonRootCA2.cer
  Client/Assets/Certificates/AmazonRootCA3.cer
  Client/Assets/Certificates/AmazonRootCA4.cer
  Client/Assets/Certificates/BaltimoreCyberTrustRoot.cer
  Client/Assets/Certificates/DSTRootCA_X3.cer
  Client/Assets/Certificates/DigiCertHighAssurance.cer
  Client/Assets/Certificates/GlobalSignRootCA_E46.cer
  Client/Assets/Certificates/GlobalSignRootCA_R1.cer
  Client/Assets/Certificates/GlobalSignRootCA_R3.cer
  Client/Assets/Certificates/GlobalSignRootCA_R46.cer
  Client/Assets/Certificates/GlobalSignRootCA_R5.cer
  Client/Assets/Certificates/GlobalSignRootCA_R6.cer
  Client/Assets/Certificates/ISRGRootCA_X1.cer
  Client/Assets/Certificates/ISRGRootCA_X2.cer
  Client/Assets/Certificates/SFSRootCAG2.cer
Labels: needs security review

#3934 Fix #3866 - Added IPv6 support to the URL bar
  Client/Frontend/Browser/URIFixup.swift
  ClientTests/SearchTests.swift
Labels: needs security review

#4069 Fix #4053: Add Release Notes for v1.30.1
  CHANGELOG.md
Labels: CI/skip, documentation

#4074 Fix #4073: Intermittent Issue while displaying the History when Sync is enabled
  Client/Frontend/Browser/Favicons/FaviconFetcher.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift
  Client/Frontend/Sync/BraveCore/History/Historyv2.swift
Labels: bug

#4076 Fix #4075: Sanitize Device Name while displaying in Sync Settings Screen
  BraveSharedTests/StringExtensionTests.swift
  Client/Frontend/Sync/SyncSettingsTableViewController.swift
  Shared/Extensions/StringExtensions.swift
  Shared/Extensions/WKWebViewExtensions.swift
Labels: enhancement, needs security review

#4080 Fix #4068 - Remove pinning certain URLs just like in Brave-Core.
  BraveShared/Analytics/UserReferralProgram.swift
  BraveShared/CertificatePinning.swift
  BraveShared/Shields/WebcompatReporter.swift
  BraveSharedTests/CertificatePinningTest.swift
Labels: needs security review

#4105 [No Bug]: Removing Playable Content Entitlement from Auto-Sign Configs
  Client/Entitlements/Beta.entitlements
  Client/Entitlements/Debug.entitlements
  Client/Entitlements/Dev.entitlements
  Client/Entitlements/Enterprise.entitlements
  Client/Entitlements/Release.entitlements
Labels: QA/No, release-notes/exclude

#4110 No Bug: Fix 'Blocker' code smells on SonarCloud.
  Client/Helpers/DynamicFontHelper.swift
Labels: QA/No
