Repository brave/brave-ios, pull requests merged in 2021-07, with the labels that each got.

#3885 Fix #3884 / 3688 : Quick Search Bar Bugs
  Client/Frontend/Browser/Search/SearchViewController.swift
Labels: bug

#3873 Fix #3865 Remove "%" character from URL allowed characters
  BraveSharedTests/StringExtensionTests.swift
  ClientTests/NavigationRouterTests.swift
  Shared/Extensions/NSCharacterSetExtensions.swift
Labels: needs security review

#3754 No Bug: Update PR template
  PULL_REQUEST_TEMPLATE
Labels: CI/skip, QA/No

#3913 Fix:#3912 Add Release Notes for 1.28
  CHANGELOG.md
Labels: CI/skip, documentation

#3917 Fix #3543: Settings toggles do not persist when scrolling away from them then back
  Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Client/Frontend/Settings/SettingsRowViews.swift
  ThirdParty/Static/Static/Row.swift
Labels: bug

#3926 Fix #3735: Add search button doesn't resize correctly when moving between text fields
  Client/Extensions/UIViewExtensions.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift
Labels: bug

#3579 Feature: #2227: Siri Shortcuts (Activity/Custom Intents)
  BraveShared/BraveStrings.swift
  BrowserIntents/BrowserIntents.entitlements
  BrowserIntents/BrowserIntentsBeta.entitlements
  BrowserIntents/BrowserIntentsDebug.entitlements
  BrowserIntents/BrowserIntentsEnterprise.entitlements
  BrowserIntents/BrowserIntentsRelease (AppStore).entitlements
  BrowserIntents/BrowserIntentsRelease.entitlements
  BrowserIntents/Info.plist
  BrowserIntents/IntentHandler.swift
  Client.xcodeproj/project.pbxproj
  Client/Application/Delegates/AppDelegate.swift
  Client/Application/Shortcuts/ActivityShortcutManager.swift
  Client/Application/Shortcuts/Base.lproj/BrowserIntents.intentdefinition
  Client/Application/Shortcuts/CustomIntentHandler.swift
  Client/Application/Shortcuts/de.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/es.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/fr.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/id-ID.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/it.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/ja.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/ko-KR.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/ms.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/nb.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/pl.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/pt-BR.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/ru.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/sv.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/tr.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/uk.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/zh-TW.lproj/BrowserIntents.strings
  Client/Application/Shortcuts/zh.lproj/BrowserIntents.strings
  Client/Assets/Images.xcassets/Settings/settings-siri-shortcuts.imageset/Contents.json
  Client/Assets/Images.xcassets/Settings/settings-siri-shortcuts.imageset/settings-siri-shortcuts@2x.png
  Client/Assets/Images.xcassets/Settings/settings-siri-shortcuts.imageset/settings-siri-shortcuts@3x.png
  Client/Entitlements/Beta.entitlements
  Client/Entitlements/Debug.entitlements
  Client/Entitlements/Dev.entitlements
  Client/Entitlements/Enterprise.entitlements
  Client/Entitlements/Release (AppStore).entitlements
  Client/Entitlements/Release.entitlements
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Client/Frontend/Browser/Playlist/BrowserViewController+Playlist.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/VPNMenuButton.swift
  Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Settings/ShortcutSettingsViewController.swift
  Client/Info.plist
Labels: needs security review

#3966 [No Bug]: Localization Change for Open Playlist Shortcut Settings Description
  BraveShared/BraveStrings.swift
Labels: QA/No

#3955 Fix #3734: Add Brave services key.
  BraveShared/Analytics/UserReferralProgram.swift
  Client/Configuration/Beta.xcconfig
  Client/Configuration/Debug.xcconfig
  Client/Configuration/Dev.xcconfig
  Client/Configuration/Enterprise.xcconfig
  Client/Info.plist
  Client/Networking/NetworkManager.swift
  Client/WebFilters/AdblockResourceDownloader.swift
  Shared/Extensions/BundleExtension.swift
  fastlane/Fastfile
Labels: needs security review

#3973 Fix #3970 - #3971 - #3972: Shortcuts Related Bug fixes and changes
  BraveShared/BraveStrings.swift
  Client/Application/Delegates/AppDelegate.swift
  Client/Frontend/Browser/BrowserViewController/ProductNotifications/BrowserViewController+ProductNotification.swift
Labels: bug

#3983 Fix #3978 - Fix #3979: Private Mode Only Fixes for Shortcuts
  Client/Application/Shortcuts/ActivityShortcutManager.swift
  Client/Frontend/Browser/BrowserViewController.swift
Labels: bug
