Repository brave/brave-ios, pull requests merged in 2021-10, with the labels that each got.

#4258 Fix: #4257 Add Release Notes for v1.31.1
  CHANGELOG.md
Labels: CI/skip, documentation

#4276 Related #4107: Update readme
  README.md
Labels: CI/skip

#4250 Fix #4249 - Certificate Pinning Robustness
  BraveShared/CertificatePinning.swift
  BraveSharedTests/CertificatePinningTest.swift
  BraveSharedTests/Certificates/intermediate.cer
  BraveSharedTests/Certificates/leaf.cer
  BraveSharedTests/Certificates/root.cer
  Client.xcodeproj/project.pbxproj
  Client/Assets/Certificates/DSTRootCA_X3.cer
Labels: needs security review
