Repository brave/brave-ios, pull requests merged in 2022-06, with the labels that each got.

#5431 Fix #5430: Playlist crashes when streaming item
  Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
Labels: crash, Epic: Playlist

#5440 [No Bug]: Adding new sites to Night Mode exception list
  Sources/Shared/Extensions/URLExtensions.swift
Labels: QA/No

#5449 No Bug: Add action to auto-add tickets for triage.
  .github/workflows/main.yml
Labels: blocked, needs security review, CI/skip

#5436 Ref #5380: Fixup push/pull transifex scripts to respect new directories
  App/l10n/tools/pull-translations-into-project.sh
  App/l10n/tools/push-strings-to-transifex.sh
Labels: blocked

#5487 No Bug: Add missing vpn resource to the BraveVPN target.
  Package.swift
Labels: QA/No

#5476 New workflow: semgrep
  .github/workflows/semgrep.yml
Labels: QA/No

#5503 Ref #5482: Temporarily disable audio farbling
  Client/Frontend/UserContent/UserScripts/FarblingProtection.js
Labels: QA/No

#5510 No Bug: Fix `updateTabsBarVisibility()` crash.
  Client/Frontend/Browser/BrowserViewController.swift
Labels: QA/No

#5520 No Bug: Add more assets to vpn source target.
  Sources/BraveVPN/BraveVPNAssets.xcassets/card_close.imageset/Contents.json
  Sources/BraveVPN/BraveVPNAssets.xcassets/card_close.imageset/card-close@2x.png
  Sources/BraveVPN/BraveVPNAssets.xcassets/card_close.imageset/card-close@3x.png
  Sources/BraveVPN/EnableVPNSettingHeader.swift
Labels: QA/No

#5546 Ref #5545: Remove BlobDownload component
  Client/Frontend/Browser/DownloadQueue.swift
Labels: QA/No

#5562 Ref #4437: Brave Search Callouts Font alignment
  Client/Frontend/Browser/Search/BraveSearchPromotionCell.swift
Labels: QA/No

#5548 Ref #5547: Unit tests DownloadQueue
  Tests/ClientTests/DownloadQueueTests.swift
Labels: QA/No

#5614 Fix #5508, Fix #5615: Tab Screenshots Blank Regression and YouTube page restore
  Client/Frontend/Browser/TabManager.swift
Labels: Epic: Webcompat

#5625 Fix #5624: Remove semgrep workflow
  .github/workflows/semgrep.yml
Labels: QA/No
