Repository brave/brave-ios, pull requests merged in 2022-05, with the labels that each got.

#5325 Update broken brave-core link
  README.md
Labels: QA/No

#5236 Fix #5235: Tab Tray Menu Button Long Press Action Improvements
  BraveShared/BraveStrings.swift
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/Tab.swift
Labels: enhancement

#5327 No bug: Wallet favicon loader/fetcher using FavIconImageRenderer
  BraveWallet/Crypto/CryptoView.swift
  BraveWallet/FaviconReader.swift
  BraveWallet/Panels/Connect/NewSiteConnectionView.swift
  BraveWallet/WalletHostingViewController.swift
  BraveWallet/WalletPanelHostingController.swift
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Client/Frontend/Browser/Favicons/FavIconImageRenderer.swift
  Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift
Labels: QA/No, Epic: Brave Wallet

#5335 Fix #4960: Private Mode Change Color Glitching
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
  Client/Frontend/Browser/TabsBar/TabBarCell.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/BottomToolbarView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
Labels: bug

#5278 Fix #4219: Add de-amp settings
  BraveShared/BraveStrings.swift
  BraveShared/Preferences.swift
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/User Scripts/ScriptSourceType.swift
  Client/Frontend/Browser/User Scripts/UserScriptHelper.swift
  Client/Frontend/Browser/User Scripts/UserScriptType.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Client/Frontend/UserContent/UserScripts/DeAMP.js
  Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift
Labels: needs security review

#5344 Fix #5241: Reader mode bar displayed in other tabs
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
Labels: QA/No

#5302 Fix #5249: Onboarding Changes and Revamp
  BraveShared/BraveStrings.swift
  BraveUI/Design System/Colors/Gradients.swift
  BraveUI/Popover/PopoverController.swift
  Client.xcodeproj/project.pbxproj
  Client/Application/ClientPreferences.swift
  Client/Assets/Images.xcassets/Shields/shield-information.imageset/Contents.json
  Client/Assets/Images.xcassets/Shields/shield-information.imageset/shield-done@2x.png
  Client/Assets/Images.xcassets/Shields/shield-information.imageset/shield-done@3x.png
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Client/Frontend/Browser/BrowserViewController/ProductNotifications/BrowserViewController+ProductNotification.swift
  Client/Frontend/Browser/Onboarding/Welcome/OnboardingPulseAnimationView.swift
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeBraveBlockedAdsController.swift
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeNTPOnboardingView.swift
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeViewCallout.swift
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeViewController.swift
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeViewSearchView.swift
  Client/Frontend/Settings/RetentionPreferencesDebugMenuViewController.swift
  Client/Frontend/Shields/SimpleShieldsView.swift
  Client/WebFilters/ShieldStats/BlockedTrackerParser.swift
  ClientTests/BenchmarkTierTests.swift
  Shared/Extensions/URLExtensions.swift
Labels: enhancement

#5354 Ref #5353: Implement unit tests for DownloadQueue
  Client.xcodeproj/project.pbxproj
  ClientTests/DownloadQueueTests.swift
Labels: QA/No

#5366 Fix #5365: web3 not being updated if wallet notification has been ignored by users
  BraveWallet/WalletProviderPermissionRequestsManager.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
Labels: Epic: Brave Wallet

#5371 No Bug: Update app licenses.
  Client/Assets/About/Licenses.html
  README.md
Labels: QA/No

#5387 No Bug: Cache npm in GH Actions builds
  .github/workflows/build_and_test.yml
  bootstrap.sh
  package-lock.json
  package.json
Labels: QA/No
