Repository brave/brave-ios, pull requests merged in 2022-11, with the labels that each got.

#6296 Fix #6295: Disable autoplay on Playlist when adding Shared Folder
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/Browser/Playlist/PlaylistSharedFolder.swift
Labels: Epic: Playlist

#6212 Improve cosmetic filters and scripts injection
  .gitignore
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/DomainUserScript.swift
  Client/Frontend/Browser/PageData.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/User Scripts/ScriptFactory.swift
  Client/Frontend/Browser/User Scripts/ScriptSourceType.swift
  Client/Frontend/Browser/User Scripts/UserScriptHelper.swift
  Client/Frontend/Browser/User Scripts/UserScriptType.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/CosmeticFiltersScriptHandler.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/DomainSpecific/Paged/FrameCheckWrapper.js
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/DomainSpecific/Paged/YoutubeAdblock.js
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js
  Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift
  Client/WebFilters/ShieldStats/Adblock/FifoDict.swift
  Package.swift
  Tests/ClientTests/PageDataTests.swift
  Tests/ClientTests/User Scripts/UserScriptHelperTests.swift
  Tests/ClientTests/Web Filters/AdBlockEngineManagerTests.swift
Labels: needs security review

#6251 Fix #6219: Do not open external links in child tabs
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
Labels: needs security review

#6249 Fix #6191: Display URL shows properly for Blobs and Session Restore of Blob URLs
  Sources/Shared/Extensions/URLExtensions.swift
  Tests/BraveSharedTests/NSURLExtensionsTests.swift
Labels: needs security review

#6250 Fix #6218: Submit File:// URLs to the search engine like Chrome-iOS
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
Labels: needs security review

#6284 Fix #6283: Move Growth Classes into a separate SPM target
  App/iOS/Delegates/AppDelegate.swift
  App/iOS/Delegates/SceneDelegate.swift
  Client/Extensions/SceneExtensions.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Client/Frontend/Browser/FullScreenCalloutManager.swift
  Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift
  Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Client/Frontend/Browser/Playlist/BrowserViewController+Playlist.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistFolderController.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift
  Client/Frontend/ClientPreferences.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Sync/BraveCore/Bookmarks/BookmarkManager.swift
  Client/Migration/Migration.swift
  Client/Shortcuts/ActivityShortcutManager.swift
  Package.swift
  Sources/BraveShared/Extensions/URLSessionExtensions.swift
  Sources/BraveShared/Preferences.swift
  Sources/BraveUI/UIKit/SceneExtensions.swift
  Sources/Growth/AppReviewManager.swift
  Sources/Growth/DAU.swift
  Sources/Growth/GrowthPreferences.swift
  Sources/Growth/URP/ReferralData.swift
  Sources/Growth/URP/UrpLogsViewController.swift
  Sources/Growth/URP/UrpService.swift
  Sources/Growth/URP/UserReferralProgram.swift
  Tests/GrowthTests/AppReviewManagerTests.swift
  Tests/GrowthTests/DAUTests.swift
Labels: enhancement

#6316 No Bug: Update documentation around BraveCore framework
  BraveCore/Updating the BraveRewards framework.md
  BraveCore/Working with BraveCore.md
Labels: QA/No

#6318 [No Bug]: Do not show cookie consent dialog for active running debug builds
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+CookieNotificationBlocking.swift
Labels: QA/No

#6317 Fix #6306: Tab sync screen empty state text does not fit the width in Polish locale
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/EmptyStateOverlayView.swift
Labels: bug

#6303 Add Brave Ads status headers to search.brave.com
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
Labels: needs security review

#6342 No Bug: Remove dead code
  .reviewdog.yml
  Client/WebFilters/AdblockServicePublisher.swift
Labels: QA/No

#6368 Fix #6359: Fix playlist expired videos on extremely slow networks
  Client/Frontend/Browser/Playlist/Cells/PlaylistCell.swift
  Client/Frontend/Browser/Playlist/Cells/PlaylistCellRedacted.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistManager.swift
  Client/Frontend/Browser/Playlist/PlaylistSharedFolder.swift
  Client/Frontend/Browser/Playlist/Utilities/PlaylistMediaStreamer.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/PlaylistScriptHandler.swift
Labels: Epic: Playlist, Epic: Playlist (CarPlay)

#6370 No Bug: Add cookie reader and storage checker for Brave Search debug …
  Client/Frontend/Settings/Brave Search/BraveSearchDebugMenu.swift
Labels: QA/No

#6355 Fix #6197: Rewrite VPN callout in SwiftUI
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Sources/BraveUI/Images/Shared.xcassets/VPN/vpn_brand.imageset/Contents.json
  Sources/BraveUI/Images/Shared.xcassets/VPN/vpn_brand.imageset/Shape2x.png
  Sources/BraveUI/Images/Shared.xcassets/VPN/vpn_brand.imageset/Shape3x.png
  Sources/BraveUI/Images/Shared.xcassets/VPN/vpn_checkmark_popup.imageset/Contents.json
  Sources/BraveUI/Images/Shared.xcassets/VPN/vpn_checkmark_popup.imageset/basic-check@2x.png
  Sources/BraveUI/Images/Shared.xcassets/VPN/vpn_checkmark_popup.imageset/basic-check@3x.png
  Sources/BraveUI/SwiftUI/PopupView.swift
  Sources/BraveVPN/BraveVPNCommonUI.swift
  Sources/BraveVPN/EnableVPNPopupViewController.swift
  Sources/Onboarding/Images/Images.xcassets/VPN/vpn_popup_shield.imageset/Contents.json
  Sources/Onboarding/Images/Images.xcassets/VPN/vpn_popup_shield.imageset/vpn-shield@2x.png
  Sources/Onboarding/Images/Images.xcassets/VPN/vpn_popup_shield.imageset/vpn-shield@3x.png
  Sources/Onboarding/OnboadingPlaylistView.swift
  Sources/Onboarding/OnboardingVPNDetailsView.swift
Labels: Epic: VPN

#6399 Fix: #6392 Add Release Notes for iOS Release 1.45
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip

#6308 Fix #1938: Implement P3A on iOS
  App/iOS/Delegates/AppDelegate.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+CookieNotificationBlocking.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ProductNotification.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/ClientPreferences.swift
  Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Client/Frontend/Settings/RetentionPreferencesDebugMenuViewController.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Package.swift
  Sources/BraveShared/BraveStrings.swift
  Sources/BraveShared/BraveUX.swift
  Sources/BraveUI/Extensions/DataSourceExtensions.swift
  Sources/BraveUI/Extensions/UIViewExtensions.swift
  Sources/Growth/DAU.swift
  Sources/Onboarding/OnboardingPreferences.swift
  Sources/Onboarding/ProductNotifications/BlockedAdsStackView.swift
  Sources/Onboarding/ProductNotifications/Resources/FullScreenCalloutManager.swift
  Sources/Onboarding/ProductNotifications/Resources/blocking-summary.json
  Sources/Onboarding/Welcome/Welcome3PAViewController.swift
  Sources/Onboarding/Welcome/WelcomeActionToggle.swift
  Sources/Onboarding/Welcome/WelcomeBraveBlockedAdsController.swift
  Sources/Onboarding/Welcome/WelcomeViewCallout.swift
  Sources/Onboarding/Welcome/WelcomeViewController.swift
Labels: Epic: Analytics

#6433 Fix: #6432, Add Release Notes to iOS Release 1.45.1
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip, documentation

#6396 Fix #6390: Fix `SelectorsPollerScript.js`
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js
Labels: QA/Yes

#6457 Fix #6456: Cannot connect to iOS sync chain code
  Client/Frontend/Sync/SyncAddDeviceViewController.swift
  Client/Frontend/Sync/SyncQRCodeView.swift
Labels: bug

#6454 Fix #6453: Add Hide for now capability to Filter Open Tab Session
  Client/Frontend/Browser/Tab Tray/TabTrayController+TableViewDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
  Client/Frontend/Browser/Tab Tray/Views/TabSyncCustomView.swift
  Sources/BraveShared/BraveStrings.swift
Labels: enhancement

#6470 [Follow Up] #1938: P3A alignment and UI fixes for onboarding
  Sources/Onboarding/Welcome/Welcome3PAViewController.swift
  Sources/Onboarding/Welcome/WelcomeActionToggle.swift
  Sources/Onboarding/Welcome/WelcomeViewController.swift
Labels: QA/No

#6480 No Bug: Fix swiftlint newer version failing.
  Client/Frontend/Browser/Punycode.swift
Labels: QA/No

#6483 No Bug: Update readme for the swiftlint bump
  README.md
Labels: QA/No, CI/skip

#6431 Fix #4918: IDN domains not working
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
  Sources/Shared/URIFixup.swift
  Tests/ClientTests/SearchTests.swift
Labels: bug, needs security review

#6489 Fix #6298: [Follow up to 5856] Save login toggle hidden behind search bar when deleting a credentials
  Client/Frontend/Login/LoginListViewController.swift
Labels: bug

#6490 Fix #6333: Current tab is not always focused in tab bar
  Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
Labels: bug

#6494 Fix #6475: Fixes resolution of videos in Brave when browsing
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCarplayManager.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistManager.swift
  Client/Frontend/Browser/Playlist/Utilities/PlaylistMediaStreamer.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/PlaylistScriptHandler.swift
Labels: Epic: Playlist

#6419 Fix #6276: Process immediate child nodes that aren't added and aren't observed.
  Client/Frontend/Browser/Playlist/Cells/PlaylistCellRedacted.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/PlaylistScript.js
Labels: Epic: Playlist
