Repository brave/brave-ios, pull requests merged in 2022-03, with the labels that each got.

#5040 No Bug: Add basic markdown parser for SwiftUI Text in iOS 14
  BraveUI/SwiftUI/BasicMarkdownParsing.swift
  BraveUI/SwiftUI/FilterableViewModifier.swift
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: QA/No

#5041 No bug: calling api to get current gas estimation for eip1559 tx for user to confirm the unapproved tx.
  BraveWallet/Crypto/Stores/TransactionConfirmationStore.swift
  BraveWallet/Crypto/Transaction Confirmations/EditPriorityFeeView.swift
  BraveWallet/Crypto/Transaction Confirmations/TransactionConfirmationView.swift
Labels: QA/No

#5029 Bump Brave-Core to 1.37.74 (Beta) - Wallet Changes
  BraveWallet/Crypto/CryptoView.swift
  BraveWallet/Crypto/Stores/AccountActivityStore.swift
  BraveWallet/Crypto/Stores/AssetDetailStore.swift
  BraveWallet/Crypto/Stores/CryptoStore.swift
  BraveWallet/Crypto/Stores/KeyringStore.swift
  BraveWallet/Crypto/Stores/PortfolioStore.swift
  BraveWallet/Crypto/Stores/SendTokenStore.swift
  BraveWallet/Crypto/Stores/SettingsStore.swift
  BraveWallet/Crypto/Stores/SwapTokenStore.swift
  BraveWallet/Crypto/Stores/TransactionConfirmationStore.swift
  BraveWallet/Crypto/Stores/WalletStore.swift
  BraveWallet/Crypto/Transaction Confirmations/EditGasFeeView.swift
  BraveWallet/Crypto/Transaction Confirmations/EditPriorityFeeView.swift
  BraveWallet/Crypto/Transaction Confirmations/TransactionConfirmationView.swift
  BraveWallet/Crypto/Transactions/TransactionView.swift
  BraveWallet/Extensions/BraveWalletSwiftUIExtensions.swift
  BraveWallet/Preview Content/MockAssetRatioService.swift
  BraveWallet/Preview Content/MockContent.swift
  BraveWallet/Preview Content/MockEthTxManagerProxy.swift
  BraveWallet/Preview Content/MockEthTxService.swift
  BraveWallet/Preview Content/MockKeyringService.swift
  BraveWallet/Preview Content/MockStores.swift
  BraveWallet/Preview Content/MockSwapService.swift
  BraveWalletTests/SendTokenStoreTests.swift
  BraveWalletTests/SwapTokenStoreTests.swift
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Settings/SettingsViewController.swift
  package-lock.json
  package.json
Labels: Epic: Brave Wallet

#5048 Fix 5047: Fix Crash in PIP presentation
  Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController+AVDelegates.swift
Labels: Epic: Playlist

#5013 Fix #3228: Implement Password Sync
  BraveShared/BraveStrings.swift
  BraveShared/Extensions/SharedExtensions.swift
  BraveSharedTests/TimeExtensionTests.swift
  Client.xcodeproj/project.pbxproj
  Client/Application/ClientPreferences.swift
  Client/Application/Delegates/AppDelegate.swift
  Client/Application/Migration.swift
  Client/Frontend/Browser/BrowserNavigationHelper.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/BrowserViewController/Sync/BrowserViewController+CoreMigration.swift
  Client/Frontend/Browser/LoginsHelper.swift
  Client/Frontend/Login/LoginInfoTableViewCell.swift
  Client/Frontend/Login/LoginInfoViewController.swift
  Client/Frontend/Login/LoginListViewController.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift
  Client/Frontend/Sync/BraveCore/BraveSyncAPIExtensions.swift
  Client/Frontend/Sync/BraveCore/Password/PasswordAPIExtensions.swift
  Client/Frontend/Sync/BraveCore/Password/PasswordStoreStateObserver.swift
  Client/Frontend/Sync/SyncSettingsTableViewController.swift
  Client/Helpers/MenuHelper.swift
  ClientTests/LoginsHelperTests.swift
  Shared/Extensions/URLExtensions.swift
  SharedTests/NSURLExtensionsTests.swift
Labels: needs security review, Epic: Sync

#5073 Fix #4911: Update Swap button description copy
  BraveWallet/WalletStrings.swift
Labels: QA/Yes, Epic: Brave Wallet

#5085 [No Bug]: Fixing (null) references in pbxproj - LoginInfoController
  Client.xcodeproj/project.pbxproj
Labels: QA/No

#5097 No Bug: Update brave-core to 1.37.87 beta.
  package-lock.json
  package.json
Labels: QA/No

#5087 Fix #5086, #5088: Playlist FavIcons & Particle Renderer not showing
  Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
  Client/Frontend/Browser/Playlist/Utilities/PlaylistMediaStreamer.swift
  Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift
  Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift
  Client/Frontend/UserContent/UserScripts/Playlist.js
Labels: Epic: Playlist

#5096 Fix #5093: Fixes Now playing info on lock screen + Fixed background audio on iOS 15+.
  Client/Frontend/Browser/Playlist/Utilities/PlaylistMediaStreamer.swift
  Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift
Labels: Epic: Playlist

#5142 Fix #4996: Top-Toolbar Playlist Badge Problem
  Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
Labels: bug

#5144 Fix #5131: Reader mode URLs show up in history
  Client/Frontend/Browser/BrowserViewController.swift
Labels: bug

#5143 Fix #5113: Update effective_tld_names.dat to the latest version
  Shared/effective_tld_names.dat
Labels: privacy

#5060 Fix #2683, #2684: Implement Cosmetic Filtering and Scriptlet Injection + Adblock & Stats refactor
  Client.xcodeproj/project.pbxproj
  Client/Application/ClientPreferences.swift
  Client/Application/Delegates/AppDelegate.swift
  Client/Application/Delegates/SceneDelegate.swift
  Client/Extensions/AsyncAwait.swift
  Client/Frontend/Brave Today/Composer/FeedDataSource.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift
  Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift
  Client/Frontend/Settings/AdblockDebugMenuTableViewController.swift
  Client/Frontend/Settings/SearchCustomEngineViewController.swift
  Client/Frontend/Shields/WKContentWorld+Sandbox.swift
  Client/Networking/NetworkManager.swift
  Client/Networking/NetworkSession.swift
  Client/Networking/NetworkSessionMock.swift
  Client/WebFilters/AdblockResourceDownloader.swift
  Client/WebFilters/AdblockRustEngine.swift
  Client/WebFilters/ContentBlocker/BlocklistName.swift
  Client/WebFilters/ContentBlocker/ContentBlocker.swift
  Client/WebFilters/ContentBlocker/ContentBlockerHelper.swift
  Client/WebFilters/CosmeticFiltersResourceDownloader.swift
  Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift
  ClientTests/ContentBlockerTests.swift
  ClientTests/NetworkManagerTests.swift
Labels: needs security review

#5159 Fix #5154: Show downloads missing in keyboard shortcuts guide
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
Labels: bug

#5147 Fix #5134: Clear Private Data should reset the Shield Preferences on Domains
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/Helpers/BrowserNavigationHelper.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/Settings/Clearables.swift
  Client/Frontend/Sync/BraveCore/History/HistoryAPIExtensions.swift
  Data/models/Domain.swift
  Data/models/History.swift
Labels: bug

#5168 Fix #5162: Edit button is visible when playing a full screen video in the Playlist
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
Labels: bug

#5184 Fix #5179: Tab Tray does not work in landscape mode
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
Labels: bug

#5191 [No Bug]: Update to match other js functions in the project
  Client/Frontend/UserContent/UserScripts/ReadyState.js
Labels: QA/No
