Repository brave/brave-ios, pull requests merged in 2022-09, with the labels that each got.

#5957 Ref #5923: Update brave-core to 1.43.88
  package-lock.json
  package.json
Labels: QA/No

#5956 Tab Sync UI revamp Part 1
  Client/Assets/Images.xcassets/Sync/Contents.json
  Client/Assets/Images.xcassets/Sync/sync-settings.imageset/Contents.json
  Client/Assets/Images.xcassets/Sync/sync-settings.imageset/sync_settings.png
  Client/Assets/Images.xcassets/Sync/sync-settings.imageset/sync_settings@2x.png
  Client/Assets/Images.xcassets/Sync/sync-settings.imageset/sync_settings@3x.png
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/SendTab/SendTabToSelfController.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController+SearchResultDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController+TableViewDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
  Client/Frontend/Browser/Tab Tray/Views/TabSyncContainerView.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/EmptyStateOverlayView.swift
  Client/Frontend/Sync/BraveCore/BraveSyncAPIExtensions.swift
  Client/Frontend/Sync/SyncSettingsTableViewController.swift
  Sources/BraveShared/BraveStrings.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.laptop.and.phone.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.laptop.and.phone.symbolset/brave.laptop.and.phone.svg
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.laptop.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.laptop.symbolset/brave.laptop.svg
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.rectangle.on.rectangle.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.rectangle.on.rectangle.symbolset/brave.rectangle.on.rectangle.svg
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.tablet.and.phone.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.tablet.and.phone.symbolset/brave.tablet.and.phone.svg
Labels: enhancement

#5961 Ref #5936: Swap slider settings icon for custom SF Symbol
  Client/Frontend/Browser/ReaderModeBarView.swift
  Sources/BraveNews/FeedSectionHeaderView.swift
  Sources/BraveNews/NewsAssets.xcassets/brave-today-settings.imageset/Contents.json
  Sources/BraveNews/NewsAssets.xcassets/brave-today-settings.imageset/settings_toggles@2x.png
  Sources/BraveNews/NewsAssets.xcassets/brave-today-settings.imageset/settings_toggles@3x.png
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.slider.horizontal.3.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.slider.horizontal.3.symbolset/brave.slider.horizontal.3.svg
Labels: crash

#5964 Fix #5963: Close All Tabs action should close Tabs for current Tab Mode
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
  Client/Frontend/Browser/TabManager.swift
Labels: bug

#5980 Fix #5979: iOS is not sending some URLs from History to Sync Engine
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
Labels: bug

#5986 No Bug: Fix build on Xcode 14 RC
  App/ShareExtension/ShareToBraveViewController.swift
Labels: QA/No

#5988 [Release Branch] Ref #5794: Update brave-core to 1.43.91.
  package-lock.json
  package.json
Labels: QA/No

#6019 Fix #5984: Tab-Sync UI Revamp Part 2
  Client/Assets/Images.xcassets/Sync/tab-completed.imageset/Contents.json
  Client/Assets/Images.xcassets/Sync/tab-completed.imageset/tab-sent.png
  Client/Assets/Images.xcassets/Sync/tab-completed.imageset/tab-sent@2x.png
  Client/Assets/Images.xcassets/Sync/tab-completed.imageset/tab-sent@3x.png
  Client/Assets/Images.xcassets/Sync/tab-progress.imageset/Contents.json
  Client/Assets/Images.xcassets/Sync/tab-progress.imageset/tab-sending-@3x.png
  Client/Assets/Images.xcassets/Sync/tab-progress.imageset/tab-sending.png
  Client/Assets/Images.xcassets/Sync/tab-progress.imageset/tab-sending@2x.png
  Client/Extensions/AsyncAwait.swift
  Client/Frontend/Browser/BrowserTrayAnimators.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/SendTab/SendTab+TransitioningDelegate.swift
  Client/Frontend/Browser/SendTab/SendTabProcessController.swift
  Client/Frontend/Browser/SendTab/SendTabToSelfController.swift
  Client/Frontend/Browser/SendTab/SendTabTransitioningController.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController+TableViewDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
  Client/Frontend/Browser/Tab Tray/Views/TabSyncContainerView.swift
  Client/Frontend/Browser/Tab Tray/Views/TabSyncCustomView.swift
  Sources/BraveShared/BraveStrings.swift
  Tests/ClientTests/SyncHelperTests.swift
Labels: enhancement

#5712 Fix #4805: Detect and store VPN state after sign-in
  App/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Client/Frontend/Browser/BraveSkusScriptHandler.swift
  Client/Frontend/Browser/BraveSkusWebHelper.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/DomainUserScript.swift
  Client/Frontend/Browser/Handlers/BraveTalkScriptHandler.swift
  Client/Frontend/Browser/User Scripts/ScriptFactory.swift
  Client/Frontend/Browser/User Scripts/ScriptSourceType.swift
  Client/Frontend/Browser/User Scripts/UserScriptType.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/UserContent/UserScripts/BraveSkusHelper.js
  Package.swift
  Sources/BraveVPN/BraveVPN.swift
  Sources/BraveVPN/BraveVPNPreferences.swift
  Sources/BraveVPN/IAPObserver.swift
  Sources/BraveVPN/VPNProductInfo.swift
  Tests/ClientTests/BraveSkusWebHelperTests.swift
Labels: needs security review

#6033 Ref #6015: Use wallpaper logo override URLs as well as images
  Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
Labels: QA/No

#6041 No Bug: Update ZIPFoundation minimum version to 0.9.15
  App/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
Labels: QA/No

#6048 Fix #6003: Include option for users to hide privacy stats from the NTP
  Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Client/Frontend/Browser/New Tab Page/Sections/FavoritesOverflowSectionProvider.swift
  Client/Frontend/Browser/New Tab Page/Sections/FavoritesSectionProvider.swift
  Client/Frontend/Browser/New Tab Page/Sections/StatsSectionProvider.swift
  Client/Frontend/ClientPreferences.swift
  Client/Frontend/Settings/NTPTableViewController.swift
  Sources/BraveShared/BraveStrings.swift
  Sources/BraveUI/UIKit/OptionSelectionViewController.swift
Labels: enhancement, Epic: NTP

#6057 No Bug: Improve incremental build times
  Plugins/CurrentBundleGenPlugin/CurrentBundleGenPlugin.swift
Labels: QA/No

#6058 Fix #5982: When playing next item automatically, item is not highlighted in playlist
  Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
Labels: bug

#6061 Fix #6014: Improving Make Brave default browser panel/screen during onboarding
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeViewCallout.swift
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeViewController.swift
Labels: bug

#6070 Fix #3521: Generate secure random numbers instead of using Math.random()
  Client/Frontend/Browser/DomainUserScript.swift
  Client/Frontend/Browser/User Scripts/ScriptFactory.swift
  Client/Frontend/Browser/User Scripts/ScriptSourceType.swift
  Client/Frontend/Browser/User Scripts/UserScriptType.swift
  Client/Frontend/UserContent/UserScripts/ArchiveIsCompat.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/AllFrames/AtDocumentStart/LoginsHelper.js
  Client/Frontend/UserContent/UserScripts/YoutubeAdblock.js
  Package.swift
  Tests/ClientTests/DomainUserScriptTests.swift
Labels: needs security review

#6073 No Bug: Fix duplicated localized string key.
  Sources/BraveWallet/WalletStrings.swift
Labels: QA/No

#6074 Fix #6071: Add https://vid.puffyan.us/ to add to playlist bar
  Sources/Shared/Extensions/URLExtensions.swift
Labels: Epic: Playlist

#6038 Ref #6036 Improved code readability on BrowserViewController+Menu
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/MenuButtonFactory.swift
  Tests/ClientTests/MenuItemFactoryTests.swift
Labels: QA/No

#6067 Ref #6065 Removed boilerplate code from test spy
  Tests/ClientTests/TabManagerNavDelegateTests.swift
Labels: QA/No

#6082 Fix #6081: Revert Shadow DOM for Content-Filters
  Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift
Labels: needs security review
