Repository brave/brave-ios, pull requests merged in 2022-02, with the labels that each got.

#4910 No Bug: Support releasing with Xcode 13.2 and up (including 13.3 beta)
  BraveUI/SwiftUI/FilterableViewModifier.swift
  BraveWallet/Chart/LineChartView.swift
  BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift
  Client.xcodeproj/project.pbxproj
  ThirdParty/Static/Static.xcodeproj/project.pbxproj
Labels: QA/Yes

#4929 No Bug: Fix incorrect modifier chain from `FB9812596` workaround
  BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift
Labels: QA/No

#4959 Fix #4958: With sandboxing, arguments must be escaped. Also page needs to access handlers
  Client/Assets/Interstitial Pages/Pages/CertificateError.html
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/SessionRestoreHandler.swift
Labels: QA/Yes

#4963 Fix #4954: Tab search bar still active after completing search which requires two taps to select found tab
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
Labels: enhancement

#4968 Guard iOS 14.3 and up to be sandboxed. iOS 14.2 and below has a WebKit Crash
  Client/Frontend/Browser/DomainUserScript.swift
  Client/Frontend/Browser/MetadataParserHelper.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Shared/Extensions/WKWebViewExtensions.swift
Labels: crash
