Repository brave/brave-ios, pull requests merged in 2022-12, with the labels that each got.

#6526 Ref #6314: Update brave-core to 1.46.133
  package-lock.json
  package.json
Labels: QA/No

#6264 Fix #6154: Make SolanaWeb3 interface not accessible by Pages
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/SolanaProviderScriptHandler.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/SolanaWeb3Script.js
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/WalletSolanaProviderScript.js
  Client/Frontend/UserContent/UserScripts/__firefox__.js
  Package.swift
Labels: needs security review

#6540 Ref #1938: Settings P3A Title Case
  Sources/BraveShared/BraveStrings.swift
Labels: QA/No

#6558 No Bug: Add locale picker to Brave News debug settings
  Sources/BraveNews/Composer/FeedDataSource.swift
  Sources/BraveNews/Settings/BraveNewsDebugSettingsView.swift
Labels: QA/No

#6612 Ref #6521: URL bar only showing origin in both display & edit mode
  Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Sources/Shared/Extensions/URLExtensions.swift
Labels: bug

#6616 [No Bug]: Removing unnecessary puny code class with String methods
  Client/Frontend/Browser/Punycode.swift
Labels: QA/No

#6621 Fix #6615 #6025 - Callout-Popover Related Problems
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ProductNotification.swift
Labels: bug

#6611 Fix #6610: Fix playlist to work on pages with dynamic embedded frames
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/PlaylistScript.js
Labels: Epic: Playlist

#6631 Fix #6623: Fix script injection overrides and double injected scripts
  Client/Frontend/UserContent/UserScripts/Sandboxed/AllFrames/AtDocumentStart/DownloadContentScript.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/AllFrames/AtDocumentStart/ForcePasteScript.js
  Client/Frontend/UserContent/UserScripts/__firefox__.js
Labels: needs security review

#6636 Fix #6623: Revert Fix #6324: Calculate toolbar height correctly
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/BottomToolbarView.swift
  Client/Frontend/UIConstants.swift
Labels: Epic: Webcompat

#6622 Fix #6619: Swap transaction not working from Solana Dapps
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/WalletSolanaProviderScript.js
Labels: needs security review

#6649 Fix #6648: Revert back the legacy AppReview Logic
  Client/Frontend/Browser/BrowserViewController.swift
  Sources/Growth/AppReviewManager.swift
  Sources/Growth/GrowthPreferences.swift
  Tests/GrowthTests/LegacyAppReviewTests.swift
Labels: QA/No

#6671 [No Bug]: Update New Issue template
  .github/ISSUE_TEMPLATE/new-issue.md
Labels: QA/No, release-notes/exclude, CI/skip, documentation
