Repository brave/brave-ios, pull requests merged in 2022-08, with the labels that each got.

#5767 Fix: #5766. Add Release Notes for iOS Release 1.41.1
  CHANGELOG.md
Labels: CI/skip, documentation

#5763 No Bug: Update App Store Links
  README.md
Labels: CI/skip

#5719 Fix 5716: Enabling Solana
  BraveWallet/WalletConstants.swift
  Tests/BraveWalletTests/KeyringStoreTests.swift
  Tests/BraveWalletTests/NetworkSelectionStoreTests.swift
  Tests/BraveWalletTests/NetworkStoreTests.swift
  Tests/BraveWalletTests/PortfolioStoreTests.swift
Labels: needs security review

#5807 Ref #4877: Add copy for the upcoming shared playlist folders feature.
  Sources/BraveShared/BraveStrings.swift
Labels: QA/No

#5764 Fix #5166: Expose iOS receipt blob for VPN purchase for Premium Services website
  Client/Frontend/Browser/BraveSkusWebHelper.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Tab.swift
  Tests/ClientTests/BraveSkusWebHelperTests.swift
Labels: needs security review

#5855 Fix #5831: Adding Biometric Authentication to Login Edit action
  Client/Frontend/Login/LoginAuthViewController.swift
  Client/Frontend/Login/LoginInfoTableViewCell.swift
  Client/Frontend/Login/LoginInfoViewController.swift
  Client/Frontend/Passcode/WindowProtection.swift
Labels: bug

#5872 Fix #5262: Search string is not updated if cursor is not at the end
  Client/Frontend/Widgets/AutocompleteTextField.swift
  Sources/BraveShared/Extensions/StringExtensions.swift
  Tests/ClientTests/StringExtensionsTests.swift
Labels: bug

#5869 Fix #5859: Fix Security Tokens issue
  Client/Frontend/Browser/Handlers/BraveSearchScriptHandler.swift
  Client/Frontend/Browser/Handlers/BraveTalkScriptHandler.swift
  Client/Frontend/Browser/User Scripts/ScriptFactory.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentStart/PrintHandler.js
  Client/Frontend/UserContent/UserScripts/BraveSearchHelper.js
  Client/Frontend/UserContent/UserScripts/BraveTalkHelper.js
  Client/Frontend/UserContent/UserScripts/DeAMP.js
  Client/Frontend/UserContent/UserScripts/FarblingProtection.js
  Client/Frontend/UserContent/UserScripts/RequestBlocking.js
  Client/Frontend/UserContent/UserScripts/ResourceDownloader.js
  Client/Frontend/UserContent/UserScripts/WindowRenderHelper.js
Labels: security, needs security review

#5826 No bug: Fix:#5768 Add older release notes to changelog file
  CHANGELOG.md
Labels: CI/skip, documentation

#5877 Fix #4891: Can't dismiss/slide down the Quick Search settings menu
  Client/Frontend/Settings/SearchQuickEnginesViewController.swift
Labels: bug

#5864 No Bug: Remove legacy code
  Client/Frontend/Accessors/HomePageAccessors.swift
  Client/Frontend/Accessors/NewTabAccessors.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/Handlers/MailtoLinkHandler.swift
  Client/Frontend/Browser/Helpers/HomePageHelper.swift
  Client/Frontend/Browser/MailProviders.swift
  Client/Frontend/Browser/TabManager.swift
Labels: QA/No

#5893 NoBug: Fix #5892 Add Release Notes to iOS Release v1.42
  CHANGELOG.md
Labels: CI/skip, documentation

#5897 Fix #5005: Update Show Tab Bar default setting to landscape only
  Client/Migration/Migration.swift
Labels: bug

#5915 Fix #5862: Extending size of click target for search suggestion populate button
  Client/Frontend/Browser/Search/SearchSuggestionCell.swift
Labels: bug

#5918 No Bug: Remove undefined escapeHTML function.
  Client/Frontend/UserContent/UserScripts/Sandboxed/MainFrame/AtDocumentStart/ReaderMode.js
Labels: QA/No

#5916 Fix #4684: Race condition allows on-screen keyboard to pre-empt while showing Privacy Education
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
Labels: bug

#5917 Fix #4672: Japan NTP tutorial page is being set as active tab when skipping on-boarding
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Client/Frontend/Browser/Onboarding/OnboardingState.swift
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeViewController.swift
Labels: bug

#5922 No Bug: Add new staging url for Brave Search.
  Client/Frontend/Browser/DomainUserScript.swift
  Client/Frontend/Browser/Search/BraveSearchManager.swift
Labels: QA/No

#5914 Fix #5912, fix #5913: Expose isBrave for all frames, remove braveSear…
  Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentStart/BraveGetUA.js
Labels: needs security review

#5809 Fix #3229: Implement Open Tabs Sync
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+DownloadQueueDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/ButtonToast.swift
  Client/Frontend/Browser/SendTab/SendTabToSelf+TransitioningDelegate.swift
  Client/Frontend/Browser/SendTab/SendTabToSelfController.swift
  Client/Frontend/Browser/SendTab/SendableTabInfoDataSource.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController+CollectionViewDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController+SearchResultDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController+TableViewDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
  Client/Frontend/Browser/Tab Tray/Views/TabSyncContainerView.swift
  Client/Frontend/Browser/Tab Tray/Views/TabSyncCustomView.swift
  Client/Frontend/Browser/Tab Tray/Views/TabTrayButtons.swift
  Client/Frontend/Browser/Tab Tray/Views/TabTrayCell.swift
  Client/Frontend/Browser/Tab Tray/Views/TabTrayContainerView.swift
  Client/Frontend/Browser/Tab Tray/Views/TabTrayPrivateModeInfoView.swift
  Client/Frontend/Browser/Tab Tray/Views/TabTraySearchView.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/EmptyStateOverlayView.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/ClientPreferences.swift
  Client/Frontend/Login/LoginListViewController.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Share/SendTabToSelfActivity.swift
  Client/Frontend/Sync/BraveCore/BraveSyncAPIExtensions.swift
  Client/Frontend/Sync/BraveCore/OpenTabs/OpenTabsSessionStateObserver.swift
  Client/Frontend/Sync/BraveCore/OpenTabs/SendTabToSelfModelStateObserver.swift
  Client/Frontend/Sync/SyncSettingsTableViewController.swift
  Client/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/BraveShared/BraveStrings.swift
  Tests/ClientTests/SyncHelperTests.swift
  Tests/ClientTests/SyncTests.swift
  Tests/ClientTests/TabManagerTests.swift
  Tests/ClientTests/TabSessionTests.swift
Labels: enhancement, Epic: Sync

#5927 No Bug: Files cleanup
  App/iOS/Delegates/AppDelegate.swift
  App/iOS/Supporting Files/Info.plist
  Client/Frontend/Browser/NavigationRouter.swift
  Client/Frontend/Browser/New Tab Page/Backgrounds/NewTabPageBackgroundButtonsView.swift
  Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Client/Frontend/Browser/Search/SearchSuggestClient.swift
  Client/Frontend/Browser/Search/SearchSuggestionDataSource.swift
  Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Widgets/ChevronView.swift
  Client/Frontend/Widgets/ErrorToast.swift
  Client/Helpers/UserActivityHandler.swift
  Client/MailSchemes.plist
  Client/Providers/Profile.swift
  Client/WebAuthN/U2FExtensions.swift
  Package.swift
  Sources/Shared/Extensions/NSFileManagerExtensions.swift
  Sources/Storage/ThirdParty/SwiftData.swift
Labels: QA/No

#5929 No Bug: Various Tab Sync related changes / fixes
  Client/Frontend/Browser/Tab Tray/TabTrayController+SearchResultDelegate.swift
  Sources/BraveShared/BraveStrings.swift
Labels: QA/No

#5954 No Bug: Fix linter errors found by updated `swiftlint`
  Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift
  README.md
Labels: QA/No
