Repository brave/brave-ios, pull requests merged in 2022-01, with the labels that each got.

#4768 Fix #4767: 🔗 Broken issue links in CHANGELOG
  CHANGELOG.md
Labels: CI/skip

#4785 Fix #4784: Add Referrer: no-referrer for all internal pages
  Client/Assets/About/Licenses.html
  Client/Assets/Interstitial Pages/Pages/CertificateError.html
  Client/Assets/Interstitial Pages/Pages/GenericError.html
  Client/Assets/Interstitial Pages/Pages/NetworkError.html
  Client/Assets/SessionRestore.html
  Client/Frontend/Browser/SessionRestoreHandler.swift
  Client/Frontend/Reader/Reader.html
  Client/Frontend/Reader/ReaderViewLoading.html
  Client/Frontend/Sync/WebFilter/Bookmarks/Bookmarks.html
  Client/WebFilters/SafeBrowsing/SafeBrowsingError.html
Labels: needs security review

#4796 Fix #4789: Bookmarks page not remembered when using the toolbar icon
  Client/Frontend/Browser/BrowserNavigationHelper.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
Labels: bug

#4806 Fix #4802: No search history result isn't showing up the correct message
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/EmptyStateOverlayView.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
Labels: bug

#4788 Fix #4732: Long button text in Spanish is unreadable
  Client/Frontend/Browser/Onboarding/Welcome/WelcomeViewCallout.swift
Labels: bug

#4791 Ref #4483: Fire field change event only when the element is not active.
  Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentStart/LoginsHelper.js
Labels: QA/No

#4787 Fix #4693: BAT/rewards icon appears greyed out when dismissing on-boarding via skip
  Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift
Labels: bug

#4762 Fix #4144: Remove 1Password Extension
  Client.xcodeproj/project.pbxproj
  Client/Assets/About/Licenses.html
  Client/Frontend/Share/ShareExtensionHelper.swift
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button-light.imageset/Contents.json
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button-light.imageset/onepassword-button-light.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button-light.imageset/onepassword-button-light@2x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button-light.imageset/onepassword-button-light@3x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button-light.pdf
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button.imageset/Contents.json
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button.imageset/onepassword-button.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button.imageset/onepassword-button@2x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button.imageset/onepassword-button@3x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-button.pdf
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension-light.imageset/Contents.json
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension-light.imageset/onepassword-extension-light@2x~compact.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension-light.imageset/onepassword-extension-light@2x~regular.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension-light.imageset/onepassword-extension-light@3x~compact.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension-light.imageset/onepassword-extension-light~compact.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension-light.imageset/onepassword-extension-light~regular.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension-light~compact.pdf
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension-light~regular.pdf
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension.imageset/Contents.json
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension.imageset/onepassword-extension@2x~compact.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension.imageset/onepassword-extension@2x~regular.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension.imageset/onepassword-extension@3x~compact.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension.imageset/onepassword-extension~compact.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension.imageset/onepassword-extension~regular.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension~compact.pdf
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-extension~regular.pdf
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar-light.imageset/Contents.json
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar-light.imageset/onepassword-navbar-light.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar-light.imageset/onepassword-navbar-light@2x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar-light.imageset/onepassword-navbar-light@3x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar-light.pdf
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar.imageset/Contents.json
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar.imageset/onepassword-navbar.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar.imageset/onepassword-navbar@2x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar.imageset/onepassword-navbar@3x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-navbar.pdf
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar-light.imageset/Contents.json
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar-light.imageset/onepassword-toolbar-light.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar-light.imageset/onepassword-toolbar-light@2x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar-light.imageset/onepassword-toolbar-light@3x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar-light.pdf
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar.imageset/Contents.json
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar.imageset/onepassword-toolbar.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar.imageset/onepassword-toolbar@2x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar.imageset/onepassword-toolbar@3x.png
  ThirdParty/onepassword-app-extension/1Password.xcassets/onepassword-toolbar.pdf
  ThirdParty/onepassword-app-extension/Info.plist
  ThirdParty/onepassword-app-extension/LICENSE.txt
  ThirdParty/onepassword-app-extension/OnePasswordExtension.h
  ThirdParty/onepassword-app-extension/OnePasswordExtension.m
  ThirdParty/onepassword-app-extension/OnePasswordExtension.xcodeproj/project.pbxproj
  ThirdParty/onepassword-app-extension/OnePasswordExtension.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ThirdParty/onepassword-app-extension/OnePasswordExtension.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ThirdParty/onepassword-app-extension/README.md
Labels: QA/No

#4757 Fix #4440: Replace action sheets with menus
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/ToolbarUrlActionsProtocol.swift
  Client/Frontend/Browser/Toolbars/ToolbarProtocols.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
Labels: enhancement

#4786 Fix #4400: Add more iPad keyboard shortcuts
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
  Client/Frontend/Strings.swift
Labels: enhancement

#4833 Ref #4400: Add more iPad keyboard shortcuts (Text Fix for Paste action)
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
Labels: QA/No

#4769 Fix #4438: Downloads Improvements
  BraveShared/BraveStrings.swift
  Client.xcodeproj/project.pbxproj
  Client/Application/NavigationRouter.swift
  Client/Extensions/FileManagerExtension.swift
  Client/Frontend/Browser/BrowserNavigationHelper.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+DownloadQueueDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/DownloadsViewController.swift
Labels: enhancement

#4840 Fix: #4838 - Add Release Notes for iOS v1.33 & v1.34
  CHANGELOG.md
Labels: CI/skip, documentation

#4846 No bug: Update 1.34 Release Notes
  CHANGELOG.md
Labels: CI/skip, documentation

#4836 Fix #4835: Add the ability to remove site-specific web data
  BraveShared/BraveStrings.swift
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Client/Frontend/Settings/ManageWebsiteDataView.swift
Labels: needs security review

#4853 Fix #4783: When Brave is closed, selecting "New private window" from context menu opens standard window
  Client/Application/Delegates/SceneDelegate.swift
Labels: bug

#4849 Fix #4848: Printer abuse
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/PrintHelper.swift
Labels: needs security review

#4852 Fix #4814: Save logins switch is shown when focus is set to search field without any saved passwords
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Login/LoginEmptyView.swift
  Client/Frontend/Login/LoginListViewController.swift
Labels: bug

#4576 Fix #3396: Add ability to search Open Tabs
  BraveShared/BraveStrings.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
  Client/Frontend/Browser/Tab Tray/TabTrayView.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/Browser/TabTrayButtonExtensions.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/EmptyStateOverlayView.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/Widgets/SiteTableViewController.swift
Labels: enhancement

#4854 Ref #4974: Added unit test coverage for unquotedIfNecessary
  Client/Frontend/Reader/ReaderModeUtils.swift
  ClientTests/StringExtensionsTests.swift
Labels: QA/No

#4856 No Bug: Add SwiftUI Previews `#if DEBUG` Swiftlint rule
  .swiftlint.yml
  BraveUI/Design System/Views/BraveButtonStyle.swift
  BraveUI/SwiftUI/PopupView.swift
  BraveWallet/Blockies/BlockieGroup.swift
  BraveWallet/Blockies/Blockies.swift
  BraveWallet/Crypto/AssetIconView.swift
  BraveWallet/Crypto/Onboarding/BiometricsPromptView.swift
  BraveWallet/Crypto/Onboarding/RecoveryPhraseGrid.swift
  BraveWidgets/FavoritesWidget.swift
  BraveWidgets/ShortcutsWidget.swift
  BraveWidgets/SingleStatWidget.swift
  BraveWidgets/StatsWidget.swift
  Client/Frontend/Browser/Onboarding/Welcome/PlaylistOnboardingView.swift
  Client/Frontend/Browser/Onboarding/Welcome/PrivacyEverywhereView.swift
  Client/Frontend/Browser/Playlist/PlaylistPopoverView.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/PlaylistMenuButton.swift
  Client/Frontend/Passcode/PasscodeMigrationView.swift
Labels: QA/No

#4861 Fix #3959, #3190, #4860: Fixes related with missing Quick search engine bar - Wrong Top Section Header Paddings
  Client/Frontend/Browser/Search/SearchViewController.swift
  Client/Frontend/Settings/SearchQuickEnginesViewController.swift
  Client/Frontend/Settings/SearchSettingsTableViewController.swift
  Client/Frontend/Widgets/SiteTableViewController.swift
Labels: bug

#4867 Ref #4841: Restore tab tray animation after search feature was added
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/Tab Tray/TabTrayAnimation.swift
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
Labels: QA/Yes

#4859 Fix #4858: WKContentWorld Sandboxing - Sandbox as much as possible
  Client.xcodeproj/project.pbxproj
  Client/Assets/MainFrameAtDocumentEndSandboxed.js
  Client/Assets/MainFrameAtDocumentStartSandboxed.js
  Client/Extensions/PaymentRequestExtension.swift
  Client/Frontend/Browser/BraveSearchScriptHandler.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift
  Client/Frontend/Browser/DomainUserScript.swift
  Client/Frontend/Browser/LoginsHelper.swift
  Client/Frontend/Browser/MetadataParserHelper.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/Browser/PlaylistHelper.swift
  Client/Frontend/Browser/ResourceDownloadManager.swift
  Client/Frontend/Browser/SessionRestoreHandler.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Client/Frontend/Browser/WindowRenderHelperScript.swift
  Client/Frontend/Reader/ReadabilityService.swift
  Client/Frontend/Reader/ReaderMode.swift
  Client/Frontend/Shields/WKContentWorld+Sandbox.swift
  Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentStart/RewardsReporting.js
  Client/Frontend/UserContent/UserScripts/BraveSearchHelper.js
  Client/Frontend/UserContent/UserScripts/FullscreenHelper.js
  Client/Frontend/UserContent/UserScripts/MainFrame/AtDocumentEnd/MainFrame.js
  Client/Frontend/UserContent/UserScripts/MediaBackgrounding.js
  Client/Frontend/UserContent/UserScripts/PaymentRequest.js
  Client/Frontend/UserContent/UserScripts/Playlist.js
  Client/Frontend/UserContent/UserScripts/PlaylistDetector.js
  Client/Frontend/UserContent/UserScripts/PlaylistSwizzler.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/AllFrames/AtDocumentStart/AdsReporting.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/AllFrames/AtDocumentStart/LoginsHelper.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/AllFrames/AtDocumentStart/__firefox__.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/MainFrame/AtDocumentEnd/CustomSearchHandler.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/MainFrame/AtDocumentEnd/FindInPage.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/MainFrame/AtDocumentEnd/MetadataHelper.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/MainFrame/AtDocumentStart/NoImageModeHelper.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/MainFrame/AtDocumentStart/ReaderMode.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/ResourceDownloader.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/WindowRenderHelper.js
  Client/WebAuthN/U2FExtensions.swift
  Client/WebFilters/ContentBlocker/ContentBlockerHelper.swift
  ClientTests/TabSessionTests.swift
  ClientTests/UserAgentTests.swift
  ClientTests/WKWebViewExtensionsTest.swift
  DataTests/CoreDataTestCase.swift
  Shared/Extensions/WKWebViewExtensions.swift
  webpack.config.js
Labels: needs security review

#4887 Fix:#4886 - Add Release Notes for 1.34.1
  CHANGELOG.md
Labels: CI/skip, documentation

#4889 No Bug: Updated build core script for M1 machine
  BraveCore/build_in_core.sh
Labels: QA/No
