Repository brave/brave-ios, pull requests merged in 2022-10, with the labels that each got.

#6092 Ref #6039: Update brave-core to 1.44.105
  package-lock.json
  package.json
Labels: QA/No

#6102 No Bug: Remove unused BVC code
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/Handlers/ClipboardBarDisplayHandler.swift
  Client/Frontend/Browser/Helpers/MetadataParserHelper.swift
  Client/Frontend/ClientPreferences.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/NoImageModeScriptHandler.swift
Labels: QA/No

#6103 No Bug: Removing the condition of compiling filter list data
  Client/Frontend/Browser/BrowserViewController.swift
Labels: QA/No

#6110 Fix #6109: Recent Search Auto-Fill should populate the text not the URL
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Shared/SharedStrings.swift
Labels: bug

#6112 Fix #5924: Problem with Tab Display Title including "localhost"
  Client/Frontend/Browser/Tab.swift
  Tests/ClientTests/TabEventHandlerTests.swift
Labels: bug

#6111 No Bug: Move GitHub Actions CI to Xcode 14.0.1
  .github/workflows/build_and_test.yml
Labels: QA/No

#6121 Ref #6096: Always hide the collapsed bar on keyboard hide
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Keyboard.swift
Labels: QA/No

#6120 Fix #5856: Logins & Passwords 'save login' toggle hidden behind search bar
  Client/Frontend/Login/LoginListViewController.swift
Labels: bug

#6129 No Bug: Bump Xcode requirement in README
  README.md
Labels: QA/No, CI/skip

#6148 Fix #6141: Fix testnets icon in iOS14 is not grey-out.
  Sources/BraveWallet/Crypto/NetworkPicker.swift
  Sources/BraveWallet/NetworkIcon.swift
Labels: Epic: Brave Wallet

#6156 [Release Branch] Ref #6039: Update brave-core to 1.44.112
  package-lock.json
  package.json
Labels: QA/No

#6138 Fix #6137: Do not show reader mode button if content fails to parse.
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/ReaderModeScriptHandler.swift
Labels: needs security review

#6170 [No Bug]: Move shouldRequestBeOpenedAsPopup in URLExtension
  Client/Frontend/Browser/BrowserViewController.swift
  Sources/Shared/Extensions/URLExtensions.swift
  Tests/ClientTests/SchemePermissionTests.swift
Labels: QA/No

#6181 Fix #6168: Do not invoke tel: and sms: schemes in subframes.
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
Labels: needs security review

#6149 Fix #5967: Password Protection for Secondary Account Removal
  Sources/BraveWallet/Crypto/Accounts/Activity/AccountActivityView.swift
  Sources/BraveWallet/Crypto/Accounts/Details/AccountDetailsView.swift
  Sources/BraveWallet/Crypto/Stores/KeyringStore.swift
  Sources/BraveWallet/PasswordEntryView.swift
  Sources/BraveWallet/RemoveAccountConfirmationView.swift
  Sources/BraveWallet/Settings/BiometricsPasscodeEntryView.swift
  Sources/BraveWallet/WalletStrings.swift
Labels: security

#6189 Fix #6160: UI Issues with tab sync flow in landscape
  Client/Frontend/Browser/Tab Tray/TabTrayController.swift
  Client/Frontend/Browser/Tab Tray/Views/TabSyncContainerView.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/EmptyStateOverlayView.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/Login/LoginListViewController.swift
  Client/Frontend/Sync/SyncSettingsTableViewController.swift
Labels: bug

#6153 [No Bug]: Create shared directory in-case of a deletion
  Client/Providers/Profile.swift
Labels: QA/No

#6199 [No Bug]: Fixing Logger Rebase compilation problem
  Client/Providers/Profile.swift
Labels: priority/P1

#6151 Fix #5881: Password Protection for Account Private Key
  Sources/BraveWallet/Crypto/Accounts/Details/AccountDetailsView.swift
  Sources/BraveWallet/Crypto/Accounts/Details/AccountPrivateKeyView.swift
  Sources/BraveWallet/PasswordEntryView.swift
Labels: security

#6205 New workflow: reviewdog
  .github/workflows/reviewdog.yml
  .reviewdog.yml
Labels: QA/No

#6216 Fix #6174: Send to your device flow modals too large in landscape view
  Client/Frontend/Browser/SendTab/SendTabProcessController.swift
Labels: bug

#6227 Fix #6157: Tab restores with a light grey / disabled close button
  Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
Labels: bug

#6220 Fix #6223: Playlist detection can only apply to pages and not video nodes
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/PlaylistScript.js
Labels: Epic: Playlist

#6281 Ref #6122: Update brave-core to 1.45.116
  package-lock.json
  package.json
Labels: QA/No

#6292 [No Bug]: Moving missing images to SPM onboarding target
  Client/Assets/Images.xcassets/Shields/thankyou-check.imageset/Contents.json
  Client/Assets/Images.xcassets/Shields/thankyou-check.imageset/thankyou-check-o-min.png
  Client/Assets/Images.xcassets/Shields/thankyou-check.imageset/thankyou-check-o@2x-min.png
  Client/Assets/Images.xcassets/Shields/thankyou-check.imageset/thankyou-check-o@3x-min.png
  Client/Frontend/Shields/SimpleShieldsView.swift
  Sources/BraveUI/Images/Shared.xcassets/shields-share.imageset/Contents.json
  Sources/BraveUI/Images/Shared.xcassets/shields-share.imageset/share-shields@3x.png
  Sources/BraveUI/Images/Shared.xcassets/shields-share.imageset/shields-share.png
  Sources/BraveUI/Images/Shared.xcassets/shields-share.imageset/shields-share@2x.png
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/Contents.json
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/data-saved-domain.imageset/Contents.json
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/data-saved-domain.imageset/domain_data_saved.png
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/data-saved-domain.imageset/domain_data_saved@2x.png
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/data-saved-domain.imageset/domain_data_saved@3x.png
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/share-bubble-shield.imageset/Contents.json
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/share-bubble-shield.imageset/shield-done-filled.png
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/share-bubble-shield.imageset/shield-done-filled@2x.png
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/share-bubble-shield.imageset/shield-done-filled@3x.png
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/shield-information.imageset/Contents.json
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/shield-information.imageset/shield-done@2x.png
  Sources/Onboarding/Images/Images.xcassets/ProductNotifications/shield-information.imageset/shield-done@3x.png
  Sources/Onboarding/ProductNotifications/ShareTrackersController.swift
Labels: QA/No
