Repository brave/brave-ios, pull requests merged in 2022-07, with the labels that each got.

#5649 No Bug: Unwrap toolbar and tabs bar in updateTabsBarVisibility().
  Client/Frontend/Browser/BrowserViewController.swift
Labels: QA/No

#5659 Fix #553: Add collapsed URL bar state with domain information
  BraveShared/BraveStrings.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/Toolbars/HeaderContainerView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
Labels: needs security review

#5666 No Bug: Use bundle for grabbing custom colors for SwiftUI views.
  Client/Frontend/Browser/PrivacyHub/AllVPNAlertsView.swift
  Client/Frontend/Browser/PrivacyHub/PrivacyReportLabels.swift
Labels: QA/No

#5671 Ref #5645: Don't expand toolbars on trait collection change
  Client/Frontend/Browser/BrowserViewController.swift
Labels: QA/No

#5673 Js/5374 request blocking fix
  Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift
Labels: QA/No

#5664 Fix #5657: Alternative Website Frontends feature.
  BraveShared/BraveStrings.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/ClientPreferences.swift
  Client/Frontend/Settings/SettingsViewController.swift
  Client/Frontend/Settings/WebsiteRedirectsSettingsView.swift
  Client/WebFilters/WebsiteRedirects.swift
  Tests/ClientTests/Web Filters/WebsiteRedirectsTests.swift
Labels: needs security review

#5629 Ref #5374: Move request blocking stats tracking to `RequestBlockingContentHelper`
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/FingerprintingProtection.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/UserContent/UserScripts/MainFrame/AtDocumentStart/TrackingProtectionStats.js
  Client/WebFilters/AdblockRustEngine.swift
  Client/WebFilters/ContentBlocker/ContentBlockerHelper+TabContentScript.swift
  Client/WebFilters/ContentBlocker/RequestBlockingContentHelper.swift
  Client/WebFilters/ContentBlocker/TrackingProtectionPageStats.swift
  Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift
  Tests/ClientTests/AdblockRustTests.swift
Labels: QA/No

#5679 Ref #5374: Ignore data schemes for request blocking
  Client/WebFilters/AdblockRustEngine.swift
Labels: QA/No

#5708 Fix #5692: Fix favicons not showing for .ico files
  Client/Frontend/Browser/FaviconHandler.swift
  Client/Frontend/Browser/ImageCache/WebImageCache.swift
Labels: QA/Yes, Epic: Webcompat

#5715 No Bug: Update submitter checklist to mention UI checks
  PULL_REQUEST_TEMPLATE
Labels: CI/skip

#5536 Fix #5373: de amp debounce
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/WebFilters/DebouncingResourceDownloader.swift
  Sources/Shared/Extensions/ArrayExtensions.swift
  Tests/ClientTests/Resources/debouncing.json
  Tests/ClientTests/Web Filters/DebouncingResourceDownloaderTests.swift
  Tests/SharedTests/ArrayExtensionTests.swift
Labels: enhancement

#5743 No Bug: Move BraveShared to Sources directory.
  Package.swift
  Sources/BraveShared/Analytics/AppReview.swift
  Sources/BraveShared/Analytics/DAU.swift
  Sources/BraveShared/Analytics/ReferralData.swift
  Sources/BraveShared/Analytics/URLSession+Requests.swift
  Sources/BraveShared/Analytics/UrpLogsViewController.swift
  Sources/BraveShared/Analytics/UrpService.swift
  Sources/BraveShared/Analytics/UserReferralProgram.swift
  Sources/BraveShared/BraveCertificateUtils.swift
  Sources/BraveShared/BraveStrings+DNT.swift
  Sources/BraveShared/BraveStrings.swift
  Sources/BraveShared/BraveUX.swift
  Sources/BraveShared/CertificatePinning.swift
  Sources/BraveShared/Certificates/AmazonRootCA1.cer
  Sources/BraveShared/Certificates/AmazonRootCA2.cer
  Sources/BraveShared/Certificates/AmazonRootCA3.cer
  Sources/BraveShared/Certificates/AmazonRootCA4.cer
  Sources/BraveShared/Certificates/GlobalSignRootCA_E46.cer
  Sources/BraveShared/Certificates/GlobalSignRootCA_R1.cer
  Sources/BraveShared/Certificates/GlobalSignRootCA_R3.cer
  Sources/BraveShared/Certificates/GlobalSignRootCA_R46.cer
  Sources/BraveShared/Certificates/GlobalSignRootCA_R5.cer
  Sources/BraveShared/Certificates/GlobalSignRootCA_R6.cer
  Sources/BraveShared/Certificates/ISRGRootCA_X1.cer
  Sources/BraveShared/Certificates/ISRGRootCA_X2.cer
  Sources/BraveShared/Certificates/SFSRootCAG2.cer
  Sources/BraveShared/Extensions/ErrorExtensions.swift
  Sources/BraveShared/Extensions/JSONSerializationExtensions.swift
  Sources/BraveShared/Extensions/SharedExtensions.swift
  Sources/BraveShared/Extensions/StringExtensions.swift
  Sources/BraveShared/Extensions/TimeExtensions.swift
  Sources/BraveShared/Extensions/UIColorExtensions.swift
  Sources/BraveShared/Extensions/UIStackViewExtensions.swift
  Sources/BraveShared/Extensions/URLCacheExtensions.swift
  Sources/BraveShared/Extensions/URLComponentsExtensions.swift
  Sources/BraveShared/Extensions/URLExtensions.swift
  Sources/BraveShared/Favicons/FaviconAttributes.swift
  Sources/BraveShared/Javascript/BrowserifiedJS.swift
  Sources/BraveShared/Javascript/BrowserifyExposable.swift
  Sources/BraveShared/Javascript/BundledJSProtocol.swift
  Sources/BraveShared/Javascript/JSContextExtensions.swift
  Sources/BraveShared/Javascript/JSValueExtensions.swift
  Sources/BraveShared/PaymentRequest/PaymentRequest.swift
  Sources/BraveShared/Preferences.swift
  Sources/BraveShared/Private CDN/PrivateCDN.swift
  Sources/BraveShared/RepresentableOptionType.swift
  Sources/BraveShared/Shields/BraveGlobalShieldStats.swift
  Sources/BraveShared/Shields/BraveShield.swift
  Sources/BraveShared/Shields/WebcompatReporter.swift
  Sources/BraveShared/Widgets/FavoritesWidgetData.swift
Labels: QA/No

#5745 No Bug: Shared framework cleanup
  App/iOS/Delegates/AppDelegate.swift
  Client/Extensions/UIScrollViewSwizzled.swift
  Client/Frontend/Browser/New Tab Page/Sections/NTPDefaultBrowserCalloutProvider.swift
  Client/Frontend/Browser/Tab.swift
  Client/Providers/Profile.swift
  Package.swift
  Sources/Shared/AppConstants.swift
  Sources/Shared/AppInfo.swift
  Sources/Shared/AuthenticationKeychainInfo.swift
  Sources/Shared/Cancellable.swift
  Sources/Shared/DeviceInfo.swift
  Sources/Shared/Extensions/ArrayExtensions.swift
  Sources/Shared/Extensions/DataExtensions.swift
  Sources/Shared/Extensions/HashExtensions.swift
  Sources/Shared/Extensions/HexExtensions.swift
  Sources/Shared/Extensions/JSONExtensions.swift
  Sources/Shared/Extensions/NSFileManagerExtensions.swift
  Sources/Shared/Extensions/StringExtensions.swift
  Sources/Shared/Extensions/UIDeviceExtensions.swift
  Sources/Shared/Extensions/UIImageExtensions.swift
  Sources/Shared/Extensions/URLExtensions.swift
  Sources/Shared/Functions.swift
  Sources/Shared/LaunchArguments.swift
  Sources/Shared/NotificationConstants.swift
  Sources/Shared/Prefs.swift
  Sources/Shared/Reachability.swift
  Sources/Shared/SystemUtils.swift
  Sources/Shared/TimeConstants.swift
  Sources/Shared/UIColorExtensions.swift
  Sources/Shared/effective_tld_names.dat
  Tests/BraveSharedTests/NSURLExtensionsTests.swift
  Tests/ClientTests/StringExtensionsTests.swift
  Tests/ClientTests/TestHashExtensions.swift
  Tests/SharedTests/ArrayExtensionTests.swift
  Tests/SharedTests/HexExtensionsTests.swift
  Tests/SharedTests/UtilsTests.swift
Labels: QA/No

#5759 No Bug: Make the app work with Xcode 14.
  Sources/Shared/Extensions/HexExtensions.swift
Labels: QA/No
