Repository brave/brave-ios, pull requests merged in 2022-04, with the labels that each got.

#5193 No Bug: Safeguard divide by 0 operation for on the buy-vpn screen.
  Client/Frontend/BraveVPN/BuyVPNView.swift
Labels: QA/No

#5203 No bug: Fix BraveWalletTests on arm64
  Client.xcodeproj/project.pbxproj
Labels: QA/No

#5198 [No Bug]: Remove Unused Classes From Shared
  Client.xcodeproj/project.pbxproj
  Shared/AsyncReducer.swift
  Shared/BundleExtensions.swift
  Shared/Cancellable.swift
  Shared/CrashSimulator.h
  Shared/CrashSimulator.m
  Shared/DateGroupedTableData.swift
  Shared/Extensions/BundleExtension.swift
  Shared/Extensions/NSCoderExtensions.swift
  Shared/Extensions/OptionalExtensions.swift
  Shared/Extensions/SetExtensions.swift
  Shared/Extensions/URLRequestExtensions.swift
  Shared/FeatureSwitch.swift
  Shared/KeychainCache.swift
  Shared/RemoteDevices.swift
  Shared/Shared-Bridging-Header.h
  SharedTests/AsyncReducerTests.swift
  SharedTests/FeatureSwitchTests.swift
  Storage/ThirdParty/SwiftData.swift
Labels: QA/No

#5173 Fix #5172: Adding blocklist functionality and night mode darker colors
  BraveUI/Design System/Colors/Colors.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Helpers/NightModeHelper.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/TabsBar/TabBarCell.swift
  Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/BottomToolbarView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
  Shared/Extensions/URLExtensions.swift
Labels: enhancement

#5220 Fix #5219: Crash verifying recovery phrase
  BraveWallet/Crypto/Onboarding/VerifyRecoveryPhraseView.swift
Labels: crash

#5156 #3700 Add farbling
  Client.xcodeproj/project.pbxproj
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/DomainUserScript.swift
  Client/Frontend/Browser/Handlers/BraveSearchScriptHandler.swift
  Client/Frontend/Browser/Handlers/BraveTalkScriptHandler.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/User Scripts/FarblingProtectionHelper.swift
  Client/Frontend/Browser/User Scripts/RandomConfiguration.swift
  Client/Frontend/Browser/User Scripts/ScriptFactory.swift
  Client/Frontend/Browser/User Scripts/ScriptSourceType.swift
  Client/Frontend/Browser/User Scripts/UserScriptHelper.swift
  Client/Frontend/Browser/User Scripts/UserScriptType.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Client/Frontend/UserContent/UserScripts/FarblingProtection.js
  Client/Frontend/UserContent/UserScripts/FingerprintingProtection.js
  Client/Frontend/UserContent/UserScripts/nacl.min.js
  ClientTests/DomainUserScriptTests.swift
  ClientTests/TabSessionTests.swift
  ClientTests/User Scripts/FarblingProtectionHelperTests.swift
  ClientTests/User Scripts/RandomConfigurationTests.swift
  ClientTests/User Scripts/ScriptFactoryTests.swift
  ClientTests/User Scripts/UserScriptHelperTests.swift
Labels: needs security review

#5223 Fix #5222: Playlist overlay showing at end of stream
  Client/Frontend/Browser/Playlist/Utilities/PlaylistStatusObserver.swift
  Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift
  Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift
Labels: Epic: Playlist

#5157 Fix #3014: Adding Open Tabs in Search Suggestions
  BraveShared/BraveStrings.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/FrequencyQuery.swift
  Client/Frontend/Browser/Search/SearchLoader.swift
  Client/Frontend/Browser/Search/SearchViewController.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/Widgets/TwoLineCell.swift
  Client/Helpers/DynamicFontHelper.swift
  Storage/Site.swift
Labels: enhancement

#5224 Fix #4862 - #5215: Some problems around Custom Search Engine
  BraveShared/BraveStrings.swift
  Client/Frontend/Browser/Search/OpenSearch.swift
  Client/Frontend/Browser/Search/SearchEngines.swift
  Client/Frontend/Settings/SearchSettingsTableViewController.swift
Labels: bug

#5231 Fix #4934: Adding Cancel into the Suppress Alerts modal on iPad
  Client/Frontend/Browser/Helpers/PrintHelper.swift
Labels: bug

#5232 Fix #5150: Reader Mode bar stuck on page after closing tab
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
  Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
Labels: bug

#5234 Fix #4964: Adds Picture-In-Picture support for videos on pages
  Client/Frontend/UserContent/UserScripts/Playlist.js
Labels: Epic: Webcompat

#5246 Ref #3361: Use only phone number data detector type.
  Client/Frontend/Browser/TabManager.swift
Labels: QA/No

#5253 Fix 5247: No rounding if users want to send/swap full token balance
  BraveWallet/Crypto/BuySendSwap/SendTokenView.swift
  BraveWallet/Crypto/BuySendSwap/SwapCryptoView.swift
  BraveWallet/Crypto/Stores/SendTokenStore.swift
  BraveWallet/Crypto/Stores/SwapTokenStore.swift
  BraveWallet/Extensions/RpcServiceExtensions.swift
  BraveWalletTests/SendTokenStoreTests.swift
  BraveWalletTests/SwapTokenStoreTests.swift
Labels: bug, QA/Yes, Epic: Brave Wallet

#5261 Fix #5196: Fix Particle Emitter on iPad again (for HLS Streams)
  Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift
  Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift
Labels: Epic: Playlist

#5271 Fix #5267: Notification gets cut off when NTP is showing.
  Client/Frontend/Brave Notifications/BraveNotificationsPresenter.swift
Labels: bug, QA/Yes

#5239 Fix #1042: Implement DomainAndRegistry for eTLD+1
  BraveSharedTests/NSURLExtensionsTests.swift
  Client.xcodeproj/project.pbxproj
  Shared/Extensions/URLExtensions.swift
Labels: needs security review, Epic: Webcompat

#5226 Fix #5225: Add "Debouncing"
  Client.xcodeproj/project.pbxproj
  Client/Application/Delegates/AppDelegate.swift
  Client/Application/Delegates/SceneDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/WebFilters/DebouncingResourceDownloader.swift
  ClientTests/Resources/debouncing.json
  ClientTests/Web Filters/DebouncingResourceDownloaderTests.swift
Labels: needs security review

#5287 Ref #5272: Update brave-core to 1.38.106.
  package-lock.json
  package.json
Labels: QA/No

#5174 Adds base functionality for Brave Wallet Dapps support
  BraveShared/BraveUX.swift
  BraveUI/Popover/PopoverController.swift
  BraveWallet/Crypto/CryptoView.swift
  BraveWallet/Crypto/NetworkPicker.swift
  BraveWallet/Crypto/Stores/Address.swift
  BraveWallet/Crypto/Stores/CryptoStore.swift
  BraveWallet/Crypto/Transaction Confirmations/TransactionConfirmationView.swift
  BraveWallet/Panels/Add Suggested Network/AddSuggestedNetworkView.swift
  BraveWallet/Panels/Add Suggested Token/AddSuggestedTokenView.swift
  BraveWallet/Panels/Connect/EditSiteConnectionView.swift
  BraveWallet/Panels/Connect/NewSiteConnectionView.swift
  BraveWallet/Panels/Signature Request/SignatureRequestView.swift
  BraveWallet/Panels/WalletPanelView.swift
  BraveWallet/Panels/WebpageRequestContainerView.swift
  BraveWallet/Preview Content/MockJsonRpcService.swift
  BraveWallet/Preview Content/MockKeyringService.swift
  BraveWallet/WalletHostingViewController.swift
  BraveWallet/WalletPanelHostingController.swift
  BraveWallet/WalletPreferences.swift
  BraveWallet/WalletProviderPermissionRequestsManager.swift
  BraveWallet/WalletStrings.swift
  BraveWalletTests/PortfolioStoreTests.swift
  BraveWalletTests/SendTokenStoreTests.swift
  BraveWalletTests/SwapTokenStoreTests.swift
  BraveWalletTests/TransactionConfirmationStoreTests.swift
  Client.xcodeproj/project.pbxproj
  Client/Assets/Images.xcassets/Symbol Sets/brave.arrow.left.arrow.right.symbolset/Contents.json
  Client/Assets/Images.xcassets/Symbol Sets/brave.arrow.left.arrow.right.symbolset/brave.arrow.left.arrow.right.svg
  Client/Assets/Images.xcassets/Symbol Sets/brave.checkmark.circle.fill.symbolset/Contents.json
  Client/Assets/Images.xcassets/Symbol Sets/brave.checkmark.circle.fill.symbolset/brave.checkmark.circle.fill.svg
  Client/Assets/Images.xcassets/Symbol Sets/brave.history.symbolset/Contents.json
  Client/Assets/Images.xcassets/Symbol Sets/brave.history.symbolset/brave.history.svg
  Client/Assets/Images.xcassets/Symbol Sets/brave.key.symbolset/Contents.json
  Client/Assets/Images.xcassets/Symbol Sets/brave.key.symbolset/brave.key.svg
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/WalletURLBarButton.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Client/Frontend/UserContent/UserScripts/WalletEthereumProvider.js
  Client/Wallet/EthereumProviderHelper.swift
  Client/Wallet/WalletProviderConstants.swift
  Data/models/Domain.swift
  DataTests/DomainTests.swift
Labels: needs security review

#5296 No Bug: Bump GitHub Actions to macOS 12 public beta and Xcode 13.3.1
  .github/workflows/build_and_test.yml
Labels: QA/No

#5299 No Bug: Update SPM Package.resolved version
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: QA/No

#5300 Ref #4435: Fetch persistent favicons for Privacy Hub websites list.
  Client/Frontend/Browser/Playlist/Controllers/PlaylistNewFolderView.swift
  Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift
Labels: QA/No

#5301 No Bug: Don't generate Info.plist for BraveWidgets target
  Client.xcodeproj/project.pbxproj
Labels: QA/No

#5303 No Bug: Update Privacy Hub url.
  BraveShared/BraveUX.swift
Labels: QA/No

#5309 No Bug: Fix running DataTests on arm64 simulators
  Client.xcodeproj/project.pbxproj
Labels: QA/No
