Repository brave/brave-ios, pull requests merged in 2023-12, with the labels that each got.

#8491 Add Release Notes for iOS Release 1.58
  CHANGELOG.md
Labels: QA/No, CI/skip

#8532 Ref #7835, #8494: Fix handling of External URL when in third-party frames but active tab #8495
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
Labels: bug

#8469 Fix #2336: Add option to disable Bookmarks/OpenTabs/History suggestions when typing in url
  Sources/Brave/Frontend/Browser/Search/SearchEngines.swift
  Sources/Brave/Frontend/Browser/Search/SearchLoader.swift
  Sources/Brave/Frontend/Browser/Search/SearchSuggestionDataSource.swift
  Sources/Brave/Frontend/Browser/Search/SearchViewController.swift
  Sources/Brave/Frontend/ClientPreferences.swift
  Sources/Brave/Frontend/Settings/General/SearchEngines/SearchSettingsTableViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: enhancement, needs-security-review

#8528 Add Release Notes for iOS Release 1.58.1
  CHANGELOG.md
Labels: QA/No, CI/skip

#8533 Fix #8114: Support CoW Swap 🐮 orders in Safer Sign
  Sources/BraveWallet/Crypto/Stores/CryptoStore.swift
  Sources/BraveWallet/Crypto/Stores/SignMessageRequestStore.swift
  Sources/BraveWallet/Crypto/Transaction Confirmations/PendingTransactionView.swift
  Sources/BraveWallet/Crypto/Transaction Confirmations/SaferSignTransactionContainerView.swift
  Sources/BraveWallet/Crypto/Transaction Confirmations/SaferSignTransactionView.swift
  Sources/BraveWallet/Crypto/Transaction Confirmations/SwapTransactionConfirmationView.swift
  Sources/BraveWallet/Extensions/BraveWalletExtensions.swift
  Sources/BraveWallet/Extensions/RpcServiceExtensions.swift
  Sources/BraveWallet/Panels/RequestContainerView.swift
  Sources/BraveWallet/Panels/Signature Request/SaferSignMessageRequestContainerView.swift
  Sources/BraveWallet/Panels/Signature Request/SignMessageRequestContainerView.swift
  Sources/BraveWallet/Panels/Signature Request/SignMessageRequestContentView.swift
  Sources/BraveWallet/Panels/Signature Request/SignMessageRequestView.swift
  Sources/BraveWallet/WalletStrings.swift
Labels: puLL-Merge

#8544 Add Release Notes for iOS Release 1.58.2
  CHANGELOG.md
Labels: QA/No, CI/skip

#8557 Fix #8546: Add 1.61 translations.
  Sources/BraveShields/Resources/pl.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/de.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/de.lproj/Localizable.strings
  Sources/BraveStrings/Resources/es.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/es.lproj/Localizable.strings
  Sources/BraveStrings/Resources/fr.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/fr.lproj/Localizable.strings
  Sources/BraveStrings/Resources/id-ID.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/id-ID.lproj/Localizable.strings
  Sources/BraveStrings/Resources/it.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/it.lproj/Localizable.strings
  Sources/BraveStrings/Resources/ja.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/ja.lproj/Localizable.strings
  Sources/BraveStrings/Resources/ko-KR.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/ko-KR.lproj/Localizable.strings
  Sources/BraveStrings/Resources/ms.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/ms.lproj/Localizable.strings
  Sources/BraveStrings/Resources/nb.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/nb.lproj/Localizable.strings
  Sources/BraveStrings/Resources/pl.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/pl.lproj/Localizable.strings
  Sources/BraveStrings/Resources/pt-BR.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/pt-BR.lproj/Localizable.strings
  Sources/BraveStrings/Resources/ru.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/ru.lproj/Localizable.strings
  Sources/BraveStrings/Resources/sv.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/sv.lproj/Localizable.strings
  Sources/BraveStrings/Resources/tr.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/tr.lproj/Localizable.strings
  Sources/BraveStrings/Resources/uk.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/uk.lproj/Localizable.strings
  Sources/BraveStrings/Resources/zh-TW.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/zh-TW.lproj/Localizable.strings
  Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/zh.lproj/Localizable.strings
  Sources/BraveWallet/Resources/de.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/es.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/fr.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/id-ID.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/it.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/ja.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/ko-KR.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/ms.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/nb.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/pl.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/pt-BR.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/ru.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/sv.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/tr.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/uk.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/zh-TW.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
Labels: puLL-Merge

#8564 Fix #8552: Reopening closed tabs via Cmd + Shift + T is not working when these tabs are closed using Cmd + W
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
Labels: bug

#8550 Fix #7485, #8012, #8151: Fix Playlist PIP continuation in Background, Data URL playing, Onboarding Popup
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCarplayManager.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/PlaylistScriptHandler.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/PlaylistScript.js
  Sources/Playlist/PlaylistDownloadManager.swift
  Sources/Playlist/PlaylistManager.swift
Labels: QA/Yes

#8577 Fix #8576: Address bar blank before website starts loading
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
Labels: bug

#8573 Fix #8535: Fix toggling night mode
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/NightModeMenuButton.swift
Labels: bug

#8572 Fix #8526: Fix the issue of the share button disappearing
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
Labels: bug
