Repository brave/brave-ios, pull requests merged in 2023-03, with the labels that each got.

#7042 Fix:6964: Shields panel url should show origin only, not full url
  Sources/Brave/Frontend/Shields/ShieldsViewController.swift
  Tests/ClientTests/SearchTests.swift
  Tests/ClientTests/URLFormatTests.swift
Labels: bug

#7029 Fix #5727: Fix Wallet JS async-await and replyHandler order
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/EthereumProviderScriptHandler.swift
Labels: Epic: Brave Wallet

#7031 Fix #6820: Allow to permanently delete Sync accounts
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/Brave/Frontend/Sync/BraveCore/BraveSyncAPIExtensions.swift
  Sources/Brave/Frontend/Sync/SyncAddDeviceViewController.swift
  Sources/Brave/Frontend/Sync/SyncPairWordsViewController.swift
  Sources/Brave/Frontend/Sync/SyncSettingsTableViewController.swift
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/BraveShared/BraveStrings.swift
  Sources/BraveUI/UIKit/AlertPopupView.swift
  Sources/BraveUI/UIKit/UIKitPopupView.swift
Labels: Epic: Sync

#7069 Ref #6957: Update brave-core to 1.49.120
  Sources/BraveWallet/Preview Content/MockJsonRpcService.swift
  package-lock.json
  package.json
Labels: QA/No

#7073 Fix#6961: Fix ordering of Playlist Folders
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistFolderController.swift
Labels: QA/Yes, Epic: Playlist

#7099 No Bug: Add xcconfig to handle building Brave service keys into the app
  App/Client.xcodeproj/project.pbxproj
  App/Configuration/Base.xcconfig
  App/Configuration/Debug.xcconfig
  App/Configuration/Local.templates/Keys.xcconfig
Labels: QA/No

#7106 Fix #7105: Fix some folders not showing in CarPlay
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift
Labels: Epic: Playlist (CarPlay)

#7126 No Bug: Remove Xcode 14.3 strict concurrency workaround
  App/Configuration/Base.xcconfig
  Package.swift
Labels: QA/No

#7156 Fix #7146: Crash when creating sync chain after attempting to join deleted chain [Same profile]
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
Labels: bug, crash

#7157 Fix #6868: Revert parts of Playlist to work with Soundcloud
  Package.swift
  Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/PlaylistScriptHandler.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/PlaylistScript.js
Labels: Epic: Playlist

#7176 No Bug: Adds additional debug information to Brave News debug settings
  Sources/BraveNews/Composer/FeedDataSource.swift
  Sources/BraveNews/Settings/BraveNewsDebugSettingsView.swift
Labels: QA/No

#7154 NoBug: Add flags to build script to disable goma
  BraveCore/build_in_core.sh
Labels: QA/No
