Repository brave/brave-ios, pull requests merged in 2023-05, with the labels that each got.

#7391 Fix 7380: VPN easy access Region switcher
  App/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  App/iOS/Delegates/AppDelegate.swift
  Package.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/RegionMenuButton.swift
  Sources/BraveShared/Extensions/StringExtensions.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveVPN/BraveVPN.swift
  Sources/BraveVPN/BraveVPNPickerViewController.swift
  Sources/BraveVPN/BraveVPNRegionPickerViewController.swift
  Sources/BraveVPN/VPNRegion.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.arrow.small-right.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.globe.symbolset/Contents.json
Labels: enhancement

#7402 Fix #7285: Private text is not fully shown in tab tray
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
Labels: bug

#7399 Fix #7397: Scrolling Tab Bar Long-Press problem
  Sources/Brave/Frontend/Browser/Tabs/TabBar/TabsBarViewController.swift
Labels: bug

#7405 Fix #7401: Previously opened tabs are closed on Brave relaunching
  Sources/Brave/Migration/Migration.swift
  Sources/Data/models/SessionWindow.swift
Labels: bug

#7409 Ref #7285: Private text is not fully shown in tab tray
  Sources/Brave/Frontend/Browser/Tabs/TabTray/Views/TabTrayPrivateModeInfoView.swift
Labels: bug

#7411 Fix #7410: Open Tabs Session Time hour format display error
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController+TableViewDelegate.swift
  Tests/ClientTests/SyncHelperTests.swift
Labels: bug

#7381 Fix #7373: Remove duplicate shields settings (Phishing and Malware)
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+P3A.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Sources/Brave/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Sources/Brave/Frontend/Shields/ShieldsViewController.swift
  Sources/Brave/Migration/Migration.swift
  Sources/BraveShields/BraveShield.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/Data/models/Domain.swift
  Sources/Preferences/GlobalPreferences.swift
  Tests/DataTests/DomainTests.swift
Labels: security

#7333 Fix #7360: Add non-aggressive cosmetic filters
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/User Scripts/UserScriptType.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/CosmeticFiltersScriptHandler.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/URLPartinessScriptHandler.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js
  Sources/Brave/WebFilters/AdBlockEngineManager.swift
  Sources/Brave/WebFilters/ShieldStats/Adblock/AdBlockStats.swift
  Sources/Brave/WebFilters/ShieldStats/Adblock/CachedAdBlockEngine.swift
Labels: QA/Yes

#7431 Fix #7412: VPN Region Selector related changes
  App/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
  Sources/BraveVPN/BraveVPN.swift
  Sources/BraveVPN/BraveVPNPickerViewController.swift
  Sources/BraveVPN/BraveVPNSettingsViewController.swift
  Sources/BraveVPN/VPNRegion.swift
Labels: bug

#7417 No Bug: Update Transifex scripts to work with python3
  App/l10n/tools/download-translations-from-transifex.swift
  App/l10n/tools/xliff-cleanup.py
Labels: QA/No, CI/skip

#7440 [release] Update brave-core to 1.51.114.
  package-lock.json
  package.json
Labels: QA/No

#7442 Fix #7432: VPN region easy access displays incorrect region on existing profile
  Sources/BraveVPN/BraveVPN.swift
Labels: bug

#7407 Fix: #7357 Add Release Notes for iOS Release 1.50
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip

#7462 Fix #7460: Fix cookie consent notice dialog
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Sources/BraveUI/Images/GIFImage.swift
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-animation-dark.dataset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-animation-dark.dataset/dark-mode.gif
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-animation.dataset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-animation.dataset/light-mode.gif
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Background@2x-1.png
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Background@2x.png
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Background@3x-1.png
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Background@3x.png
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Contents.json
  Sources/Onboarding/ProductNotifications/CookieNotificationBlockingConsentView.swift
Labels: QA/Yes

#7400 Fix #7370: NFT Discovery
  Sources/BraveWallet/AdjustableHeightAttributedTextView.swift
  Sources/BraveWallet/Crypto/Asset Details/AssetDetailView.swift
  Sources/BraveWallet/Crypto/NFT/NFTView.swift
  Sources/BraveWallet/Crypto/Onboarding/CreateWalletView.swift
  Sources/BraveWallet/Crypto/Onboarding/RestoreWalletView.swift
  Sources/BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift
  Sources/BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift
  Sources/BraveWallet/Crypto/Stores/CryptoStore.swift
  Sources/BraveWallet/Crypto/Stores/NFTStore.swift
  Sources/BraveWallet/Crypto/Stores/PortfolioStore.swift
  Sources/BraveWallet/Crypto/Stores/SettingsStore.swift
  Sources/BraveWallet/Settings/Web3SettingsView.swift
  Sources/BraveWallet/WalletConstants.swift
  Sources/BraveWallet/WalletPreferences.swift
  Sources/BraveWallet/WalletPromptView.swift
  Sources/BraveWallet/WalletStrings.swift
  Tests/BraveWalletTests/SettingsStoreTests.swift
Labels: needs security review

#7469 Fix #7468 Bottom Bar Callout is blocking Cookie Consent Callout
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
Labels: bug

#7450 Fix #7436: [hackerone] Sync settings should be behind Face ID / Passcode authentication
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/Brave/Frontend/Sync/SyncAddDeviceViewController.swift
  Sources/Brave/Frontend/Sync/SyncPairCameraViewController.swift
  Sources/Brave/Frontend/Sync/SyncPairWordsViewController.swift
  Sources/Brave/Frontend/Sync/SyncSettingsTableViewController.swift
  Sources/Brave/Frontend/Sync/SyncViewController.swift
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: security

#7482 Fix #7481: Login List View Background Color Issue
  Sources/Brave/Frontend/Login/LoginListViewController.swift
Labels: bug

#7490 No Bug: Update leaf certificate for tests
  Tests/CertificateUtilitiesTests/Certificates/leaf.cer
Labels: QA/No

#7475 No Bug: Github Actions deps bump node12 => node16
  .github/workflows/build_and_test.yml
Labels: QA/No

#7494 Fix #7493 - Ref #7436: Sync Chain Deletion - Authentication problems
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/Brave/Frontend/Sync/SyncSettingsTableViewController.swift
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
Labels: bug

#7536 Fix #7466: Fix Playlist lockscreen pausing
  Sources/Brave/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift
Labels: Epic: Playlist

#7525 Fix #7448, fix #7413: VPN Initialize and Connect issues
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/VPNMenuButton.swift
  Sources/BraveVPN/BraveVPN.swift
  Sources/BraveVPN/BuyVPNViewController.swift
  Sources/BraveVPN/InstallVPNViewController.swift
Labels: bug

#7545 Ref #7378: Update brave-core to 1.52.117
  package-lock.json
  package.json
Labels: QA/No
