Repository brave/brave-ios, pull requests merged in 2023-11, with the labels that each got.

#8352 Fix #8350: Fix Playlist not working on Youtube at all
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Sources/Brave/Frontend/Browser/Tab.swift
  Sources/Brave/Frontend/Settings/Features/PlaylistSettingsViewController.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/PlaylistSwizzlerScript.js
  Sources/Playlist/PlaylistPreferences.swift
Labels: QA/Yes

#8194 Fix #8203: Apple Search Ads Install Attribution
  App/iOS/Delegates/AppDelegate.swift
  App/iOS/Delegates/SceneDelegate.swift
  Package.swift
  Sources/BraveShared/Extensions/AsyncAwait.swift
  Sources/BraveShared/Extensions/URLSessionExtensions.swift
  Sources/CertificateUtilities/BraveCertificateUtils.swift
  Sources/CertificateUtilities/CertificatePinning.swift
  Sources/CertificateUtilities/Certificates/AmazonRootCA1.cer
  Sources/CertificateUtilities/Certificates/AmazonRootCA2.cer
  Sources/CertificateUtilities/Certificates/AmazonRootCA3.cer
  Sources/CertificateUtilities/Certificates/AmazonRootCA4.cer
  Sources/CertificateUtilities/Certificates/GlobalSignRootCA_E46.cer
  Sources/CertificateUtilities/Certificates/GlobalSignRootCA_R1.cer
  Sources/CertificateUtilities/Certificates/GlobalSignRootCA_R3.cer
  Sources/CertificateUtilities/Certificates/GlobalSignRootCA_R46.cer
  Sources/CertificateUtilities/Certificates/GlobalSignRootCA_R5.cer
  Sources/CertificateUtilities/Certificates/GlobalSignRootCA_R6.cer
  Sources/CertificateUtilities/Certificates/ISRGRootCA_X1.cer
  Sources/CertificateUtilities/Certificates/ISRGRootCA_X2.cer
  Sources/CertificateUtilities/Certificates/SFSRootCAG2.cer
  Sources/Growth/DAU.swift
  Sources/Growth/GrowthPreferences.swift
  Sources/Growth/URP/AdAttributionData.swift
  Sources/Growth/URP/UrpService.swift
  Sources/Growth/URP/UserReferralProgram.swift
  Sources/Shared/AppConstants.swift
  Tests/CertificateUtilitiesTests/CertificatePinningTest.swift
  Tests/CertificateUtilitiesTests/Certificates/expired.badssl.com/expired.badssl.com-intermediate-ca-1.cer
  Tests/CertificateUtilitiesTests/Certificates/expired.badssl.com/expired.badssl.com-intermediate-ca-2.cer
  Tests/CertificateUtilitiesTests/Certificates/expired.badssl.com/expired.badssl.com-leaf.cer
  Tests/CertificateUtilitiesTests/Certificates/expired.badssl.com/expired.badssl.com-root-ca.cer
  Tests/CertificateUtilitiesTests/Certificates/expired.badssl.com/self-signed.badssl.com.cer
  Tests/CertificateUtilitiesTests/Certificates/expired.badssl.com/untrusted.badssl.com-leaf.cer
  Tests/CertificateUtilitiesTests/Certificates/expired.badssl.com/untrusted.badssl.com-root.cer
  Tests/CertificateUtilitiesTests/Certificates/intermediate.cer
  Tests/CertificateUtilitiesTests/Certificates/root.cer
  Tests/GrowthTests/DAUTests.swift
Labels: enhancement

#8388 No Bug: Add brave player copy text
  Sources/BraveShields/ShieldStrings.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: QA/No

#8387 Fix #8333: Add Open Browser History and Open Tabs from Other Devices Activity Based Shortcuts
  App/iOS/Delegates/SceneDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/Helpers/BrowserNavigationHelper.swift
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Sources/Brave/Frontend/Settings/General/ShortcutSettingsViewController.swift
  Sources/Brave/Shortcuts/ActivityShortcutManager.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: Epic: Siri Shortcuts

#8319 Fix #7827: Sign In With Ethereum
  Sources/BraveWallet/Crypto/Accounts/AccountView.swift
  Sources/BraveWallet/Extensions/String+Extensions.swift
  Sources/BraveWallet/OriginInfoFavicon.swift
  Sources/BraveWallet/Panels/RequestContainerView.swift
  Sources/BraveWallet/Panels/Signature Request/SignInWithEthereumView.swift
  Sources/BraveWallet/Panels/Signature Request/SignMessageErrorView.swift
  Sources/BraveWallet/Panels/Signature Request/SignMessageRequestContainerView.swift
  Sources/BraveWallet/Panels/Signature Request/SignMessageRequestView.swift
  Sources/BraveWallet/Panels/Signature Request/SignatureRequestView.swift
  Sources/BraveWallet/WalletStrings.swift
Labels: needs-security-review

#8395 [No Bug]: Ancient Migrations - Unused Preference Cleanup
  App/iOS/Delegates/AppDelegate.swift
  Sources/Brave/Frontend/Browser/Search/OpenSearch.swift
  Sources/Brave/Frontend/Browser/Search/SearchEngines.swift
  Sources/Brave/Frontend/Browser/TabManager.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Sources/Brave/Frontend/ClientPreferences.swift
  Sources/Brave/Frontend/Settings/General/SearchEngines/SearchSettingsTableViewController.swift
  Sources/Brave/Migration/Migration.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveVPN/BraveVPN.swift
  Sources/Data/models/DataController.swift
  Sources/Data/models/Domain.swift
  Sources/Preferences/GlobalPreferences.swift
  Sources/Shared/AuthenticationKeychainInfo.swift
  Tests/ClientTests/SearchEnginesTests.swift
Labels: QA/No

#8372 Add Release Notes for iOS Release 1.52.1
  CHANGELOG.md
Labels: QA/No, CI/skip, documentation

#8411 No Bug: Duplicate localized string key.
  Sources/BraveStrings/BraveStrings.swift
Labels: QA/No

#8354 Fix #8353: Add Subscription Custom Offer Codes Interaction
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveVPN/BraveVPNSettingsViewController.swift
  Sources/BraveVPN/BuyVPNViewController.swift
Labels: enhancement, Epic: VPN

#8391 Fix #7592: Alternative - New Keyboard Shortcuts for tabs "reopen" and "reverse navigation" And Zoom In Zoom Out
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
  Sources/Brave/Frontend/Browser/PageZoom/PageZoomHandler.swift
  Sources/Brave/Frontend/Browser/PageZoom/PageZoomSettingsView.swift
  Sources/Brave/Frontend/Browser/PageZoom/PageZoomView.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: enhancement

#8414 Add Release Notes for iOS Release 1.56
  CHANGELOG.md
Labels: QA/No, CI/skip, documentation

#8429 [No Bug]: Removing TabMO and Tab Migration
  App/iOS/Delegates/AppState.swift
  Sources/Brave/Frontend/Browser/SessionData.swift
  Sources/Brave/Frontend/Browser/Tab.swift
  Sources/Brave/Migration/Migration.swift
  Sources/Data/models/Model.xcdatamodeld/.xccurrentversion
  Sources/Data/models/Model.xcdatamodeld/Model26.xcdatamodel/contents
  Sources/Data/models/TabMO.swift
  Tests/DataTests/DataControllerTests.swift
  Tests/DataTests/TabMOTests.swift
Labels: QA/No

#8433 Fix 8431: Copy mistake in confirmation message after resetting VPN config
  Sources/BraveStrings/BraveStrings.swift
Labels: bug, blocked: needs info

#8415 Fix #8001: Display the VPN subscription in the App Store
  App/iOS/Delegates/AppDelegate.swift
  App/iOS/Delegates/SceneDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Sources/Brave/Frontend/Browser/Helpers/BrowserNavigationHelper.swift
  Sources/BraveVPN/BraveVPN.swift
  Sources/BraveVPN/BraveVPNPreferences.swift
  Sources/BraveVPN/BraveVPNSettingsViewController.swift
  Sources/BraveVPN/BuyVPNViewController.swift
  Sources/BraveVPN/IAPObserver.swift
  Sources/Preferences/GlobalPreferences.swift
Labels: Epic: VPN

#8443 Ref #8431: Copy mistake in confirmation message after resetting VPN config
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveVPN/BraveVPNSettingsViewController.swift
Labels: bug

#8450 Add Release Notes for iOS Release 1.57.1
  CHANGELOG.md
Labels: QA/No, CI/skip, documentation

#8442 Fix #8361: Open Add separator between inactive tabs
  Sources/Brave/Frontend/Browser/Tabs/TabBar/TabBarCell.swift
Labels: Epic: UI/UX

#8456 Fix #8253: Don't navigate to javascript:// URLs from the omnibox
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+BraveTalk.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Sources/Brave/Frontend/Browser/Toolbars/ToolbarUrlActionsDelegate.swift
  Sources/Brave/Shortcuts/ActivityShortcutManager.swift
Labels: bug, security

#8417 Fix #8173: Update URL bar design & display origin-only URLs
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Rewards.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ProductNotification.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+TabManagerDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/Certificate Viewer/CertificateViewController.swift
  Sources/Brave/Frontend/Browser/Tab.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/BottomToolbarView.swift
  Sources/Brave/Frontend/Browser/Toolbars/HeaderContainerView.swift
  Sources/Brave/Frontend/Browser/Toolbars/PageSecurityView.swift
  Sources/Brave/Frontend/Browser/Toolbars/ToolbarHelper.swift
  Sources/Brave/Frontend/Browser/Toolbars/ToolbarProtocols.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/ReaderModeButton.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/RewardsButton.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
  Sources/Brave/Frontend/Share/MenuActivity.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.lock.plain.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.verification.outline.symbolset/Contents.json
  Tests/ClientTests/DisplayTextFieldTest.swift
Labels: needs security review

#8472 Fix #8227: When launching the QR code scanning UI while in the Landscape mode, the camera view is rotated 90 degrees
  Sources/Brave/Frontend/Browser/Search/Recent Search/RecentSearchQRCodeScannerController.swift
  Sources/Brave/Frontend/Sync/SyncCameraView.swift
Labels: bug

#8455 Add Release Notes for iOS Release 1.57.2
  CHANGELOG.md
Labels: QA/No, CI/skip, documentation

#8483 Fix: #8479 - Fix long-press and video detection
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/PlaylistScript.js
Labels: QA/Yes

#8485 Fix #8484: Portrait Orientation Locking on Phone is not working
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift
  Sources/Brave/Frontend/Settings/SettingsNavigationController.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/Brave/Frontend/Sync/SyncViewController.swift
  Sources/BraveWallet/WalletHostingViewController.swift
  Sources/BraveWallet/WalletPanelHostingController.swift
  Sources/Shared/DeviceOrientation.swift
  Sources/Shared/Extensions/UIDeviceExtensions.swift
Labels: bug

#8495 Fix #7835, #8494: Fix handling of External URL when in third-party frames but active tab
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
Labels: needs security review

#8501 Fix #7439: Update clear history app intent for SwiftUI
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/AdvancedShieldSettings.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
Labels: QA/No
