Repository brave/brave-ios, pull requests merged in 2023-07, with the labels that each got.

#7643 Fix #7514 - #7280: Search buttons are behind safe area when using hardware keyboard - Omnibar missing after trying to change search settings
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
Labels: bug

#7678 No Bug: Fix missing corner radius on URL bar
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/LocationContainerView.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
Labels: QA/No

#7681 No Bug: Update Leo SF Symbols to 1.0.7
  App/BraveWidgets/LockScreenFavoriteWidget.swift
  App/BraveWidgets/TopNewsListWidget.swift
  App/BraveWidgets/TopNewsWidget.swift
  Sources/BraveUI/Popover/PopoverOriginFocusView.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.brave.icon-monochrome.symbolset/Contents.json
  package-lock.json
  package.json
Labels: QA/No

#7682 Fix #7657 - #7656: Local Authentication Changes and Bug Fixes
  Sources/Brave/Frontend/Login/LoginAuthViewController.swift
  Sources/Brave/Frontend/Login/LoginInfoViewController.swift
  Sources/Brave/Frontend/Login/LoginListViewController.swift
  Sources/Brave/Frontend/Passcode/WindowProtection.swift
  Sources/Brave/Frontend/Sync/SyncViewController.swift
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: bug

#7694 Fix #7693: Ensure PopupView is sized correctly when presenting
  Sources/BraveUI/SwiftUI/PopupView.swift
Labels: bug

#7549 Fix #6533: Update VPN CTA - Purchase Flow
  Sources/Brave/Frontend/Brave Notifications/Brave Wallet/WalletConnectionView.swift
  Sources/Brave/Frontend/Browser/Playlist/Cells/PlaylistCell.swift
  Sources/Brave/Frontend/Browser/Playlist/Cells/PlaylistMenuHeader.swift
  Sources/Brave/Frontend/Browser/Search/BraveSearchPromotionCell.swift
  Sources/Brave/Frontend/Browser/Tabs/TabTray/Views/TabSyncContainerView.swift
  Sources/Brave/Frontend/Browser/Tabs/TabTray/Views/TabSyncCustomView.swift
  Sources/BraveNews/Settings/BraveNewsAddSourceResultsViewController.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveUI/Extensions/UIFontExtenions.swift
  Sources/BraveUI/Extensions/UIFontExtensions.swift
  Sources/BraveVPN/BuyVPNView.swift
  Sources/BraveVPN/BuyVPNViewController.swift
  Sources/BraveWallet/WalletTableViewHeaderView.swift
  Sources/DesignSystem/Views/GradientView.swift
Labels: enhancement, Epic: VPN

#7700 Fix #7676: Changing compression priority search button item
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
Labels: bug

#7721 Fix #7702: OpenSearch issues - [hackerone 2057565]
  Sources/Brave/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift
  Sources/Brave/Frontend/Browser/Search/OpenSearch.swift
  Sources/Brave/Frontend/Browser/Search/SearchSuggestionDataSource.swift
  Sources/Brave/Frontend/Browser/ThirdPartySearchAlerts.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: bug, security

#7727 Fix #7686: Voice search not detecting sound
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/Search/Voice Search/SpeechRecognizer.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
Labels: bug

#7734 Fix #7733: Allow Custom Search Engines to be default in Private Mode
  Sources/Brave/Frontend/Browser/Search/SearchSuggestionDataSource.swift
  Sources/Brave/Frontend/Settings/SearchSettingsTableViewController.swift
Labels: enhancement

#7744 Fix #7743: Removed assertionFailure in scripts.
  Sources/Brave/Frontend/Browser/UserScriptManager.swift
Labels: QA/No

#7762 No Bug: Duplicated localized string key.
  Sources/BraveWallet/WalletStrings.swift
Labels: QA/No

#7761 Fix: #7453 Add Release Notes for iOS Release 1.51
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip

#7724 Fix #6729: Add Playlist P3A Questions
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+P3A.swift
  Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/Browser/BrowserViewController+Playlist.swift
  Sources/Brave/Frontend/Browser/Playlist/Utilities/PlaylistP3A.swift
  Sources/Brave/Shortcuts/ActivityShortcutManager.swift
  Sources/Growth/P3AFeatureUsage.swift
Labels: Epic: Playlist, Epic: P3A

#7670 Ref #4879: VPN churn improvements - Popover Types
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _discount_image.imageset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _discount_image.imageset/auto_renew _discount_image@2x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _discount_image.imageset/auto_renew _discount_image@3x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _discount_image.imageset/auto_renew _discount_image_mode_dark@2x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _discount_image.imageset/auto_renew _discount_image_mode_dark@3x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _free_image.imageset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _free_image.imageset/auto_renew _free_image@2x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _free_image.imageset/auto_renew _free_image@3x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _soon_image.imageset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _soon_image.imageset/auto_renew _soon_image@2x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _soon_image.imageset/auto_renew _soon_image@3x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _soon_image.imageset/auto_renew _soon_image_mode_dark@2x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/auto_renew _soon_image.imageset/auto_renew _soon_image_mode_dark@3x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/subscribe_all-devices_image.imageset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/VPN/subscribe_all-devices_image.imageset/Illustration@2x 1.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/subscribe_all-devices_image.imageset/Illustration@2x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/subscribe_all-devices_image.imageset/Illustration@3x 1.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/subscribe_all-devices_image.imageset/Illustration@3x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/subscribe_protection_image.imageset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/VPN/subscribe_protection_image.imageset/subscribe_voluntary_discount_image@2x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/subscribe_protection_image.imageset/subscribe_voluntary_discount_image@3x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/update_billing_expired.imageset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/VPN/update_billing_expired.imageset/update_billing_expired@2x 1.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/update_billing_expired.imageset/update_billing_expired@2x.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/update_billing_expired.imageset/update_billing_expired@3x 1.png
  Sources/Onboarding/Assets/Images.xcassets/VPN/update_billing_expired.imageset/update_billing_expired@3x.png
  Sources/Onboarding/OnboardingPreferences.swift
  Sources/Onboarding/ProductNotifications/FullScreenCalloutManager.swift
  Sources/Onboarding/VPNNotifications/VPNChurnPromoView.swift
  Sources/Onboarding/VPNNotifications/VPNLinkReceiptView.swift
Labels: enhancement

#7772 [release branch] Ref #7553: Update brave-core to 1.56.13
  package-lock.json
  package.json
Labels: QA/No

#7778 Fix #7737: Crash at Browsing Mode Change while drag-drop action in Tab Tray
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
Labels: bug, crash

#7775 Release Notes for iOS Release 1.51.1
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip

#7783 No bug: Attempted fix for KVO crash in iOS17
  Sources/BraveWallet/Crypto/Stores/TabbedPageViewController.swift
Labels: QA/No

#7789 Fix #7752: Reopen last closed tab in tab tray context menu
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+TabManagerDelegate.swift
  Sources/Brave/Frontend/Browser/TabManager.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.browser.mobile-tab-ntp.symbolset/Contents.json
Labels: enhancement

#7781 Add Release Notes for iOS Release 1.51.2
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip

#7800 Fix #7798: Add Haptic Feedback Voice Search for successful query
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/Search/Recent Search/RecentSearchQRCodeScannerController.swift
Labels: enhancement
