Repository brave/brave-ios, pull requests merged in 2023-08, with the labels that each got.

#7820 Ref #7686: Resetting Speech Recognizer properly after valid search conditions
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/Search/Voice Search/SpeechRecognizer.swift
Labels: bug

#7821 Fix iOS for recent `AdblockEngine` changes
  App/iOS/Delegates/AppDelegate.swift
  Sources/Brave/WebFilters/AdBlockEngineManager.swift
  Sources/Brave/WebFilters/FilterListCustomURLDownloader.swift
  Sources/Brave/WebFilters/ShieldStats/Adblock/AdBlockEngine+Extensions.swift
  Sources/Brave/WebFilters/ShieldStats/Adblock/CachedAdBlockEngine.swift
  Tests/ClientTests/AdblockRustTests.swift
  Tests/ClientTests/Web Filters/AdBlockEngineManagerTests.swift
Labels: QA/Yes

#7825 Fix #7822: Fix Block scripts to work on all frames
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
Labels: sec-low

#7830 Ref #7730: Update brave-core to 1.57.35
  package-lock.json
  package.json
Labels: QA/No

#7833 Fix #7831: Fixed PopoverController not deallocating
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift
  Sources/Brave/Frontend/Browser/Playlist/Browser/BrowserViewController+Playlist.swift
Labels: bug

#7829 Fix #7828: Adding Issue Category Separately to VPN Contact Form
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveVPN/BraveVPNContactFormViewController.swift
Labels: Epic: VPN

#7848 Fix #7832: Restored but unopened tabs not added to Recently Closed Tabs
  Sources/Brave/Frontend/Browser/TabManager.swift
  Sources/Data/models/RecentlyClosed.swift
Labels: bug

#7852 Ref #7730: Update brave-core to 1.57.42
  package-lock.json
  package.json
Labels: QA/No

#7811 Fix #7810: Private Mode Biometric Authentication
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/Brave/Frontend/ClientPreferences.swift
  Sources/Brave/Frontend/Passcode/WindowProtection.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/Brave/Frontend/Sync/SyncViewController.swift
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/Brave/Frontend/Widgets/LoadingViewController.swift
  Sources/Brave/Frontend/Widgets/SiteTableViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: enhancement

#7868 Fix #7855: Add 'Private tabs' settings section
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/Brave/Frontend/Settings/Debug/AdblockDebugMenuTableViewController.swift
  Sources/Brave/Frontend/Settings/Debug/Brave Search/BraveSearchDebugMenu.swift
  Sources/Brave/Frontend/Settings/Debug/Brave Search/BraveSearchDebugMenuDetail.swift
  Sources/Brave/Frontend/Settings/Debug/Brave Search/BraveSearchLogEntry.swift
  Sources/Brave/Frontend/Settings/Debug/BraveCoreDebugSwitchesView.swift
  Sources/Brave/Frontend/Settings/Debug/LocalStateInspectorView.swift
  Sources/Brave/Frontend/Settings/Debug/RetentionPreferencesDebugMenuViewController.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/QA/RewardsDebugSettingsViewController.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/QA/RewardsInternalsAutoContributeController.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/QA/RewardsInternalsDebugViewController.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/RewardsInternalsContributionListController.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/RewardsInternalsContributionPublishersListController.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/RewardsInternalsLogController.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/RewardsInternalsPromotionListController.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/RewardsInternalsSharable.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/RewardsInternalsShareController.swift
  Sources/Brave/Frontend/Settings/Debug/Rewards Internals/RewardsInternalsViewController.swift
  Sources/Brave/Frontend/Settings/Debug/SandboxInspectorView.swift
  Sources/Brave/Frontend/Settings/Debug/VPNLogsViewController.swift
  Sources/Brave/Frontend/Settings/Display/MediaSettingsView.swift
  Sources/Brave/Frontend/Settings/Display/NTPTableViewController.swift
  Sources/Brave/Frontend/Settings/Features/BraveRewardsSettingsViewController.swift
  Sources/Brave/Frontend/Settings/Features/PlaylistSettingsViewController.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/AdvancedShieldSettings.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/AdvancedShieldsSettingsView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/ClearDataSectionView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/Clearables.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/DefaultShieldsSectionView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/FilterLists/FilterListAddURLView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/FilterLists/FilterListsView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/ManageWebsiteDataView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/OtherPrivacySettingsSectionView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/PrivacyReportSettingsView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/ShieldLabelView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/ShieldToggleView.swift
  Sources/Brave/Frontend/Settings/General/SearchEngines/SearchCustomEngineViewController.swift
  Sources/Brave/Frontend/Settings/General/SearchEngines/SearchEnginePicker.swift
  Sources/Brave/Frontend/Settings/General/SearchEngines/SearchQuickEnginesViewController.swift
  Sources/Brave/Frontend/Settings/General/SearchEngines/SearchSettingsTableViewController.swift
  Sources/Brave/Frontend/Settings/General/ShortcutSettingsViewController.swift
  Sources/Brave/Frontend/Settings/General/WebsiteRedirectsSettingsView.swift
  Sources/Brave/Frontend/Settings/PasscodeSettingsViewController.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/Brave/Frontend/Settings/Tabs/LocationViewPositionPickerCell.swift
  Sources/Brave/Frontend/Settings/Tabs/PrivateTabsView.swift
  Sources/Brave/Frontend/Widgets/LoadingViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: enhancement, Epic: Settings

#7878 Fix #7849: Update Sync Local Authentication Logic
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/Brave/Frontend/Sync/SyncSettingsTableViewController.swift
  Sources/Brave/Frontend/Sync/SyncViewController.swift
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/Brave/Frontend/Widgets/LoadingViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: enhancement, Epic: Sync, needs-security-review

#7884 Ref #7730: Update brave-core 1.57.47
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Sources/Brave/Frontend/Rewards/BraveRewards.swift
  Sources/BraveNews/Customize/NewsSettingsView.swift
  Sources/BraveShared/Extensions/BraveAdsExtensions.swift
  Sources/BraveWallet/Preview Content/MockBraveWalletService.swift
  package-lock.json
  package.json
Labels: QA/No

#7883 Fix #7882: Enable cookie consent notice blocking by default
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Sources/Brave/Frontend/Settings/Debug/RetentionPreferencesDebugMenuViewController.swift
  Sources/Brave/WebFilters/FilterListStorage.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveUI/Images/GIFImage.swift
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-animation-dark.dataset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-animation-dark.dataset/dark-mode.gif
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-animation.dataset/Contents.json
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-animation.dataset/light-mode.gif
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Background@2x-1.png
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Background@2x.png
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Background@3x-1.png
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Background@3x.png
  Sources/Onboarding/Assets/Images.xcassets/CookieConsent/cookie-consent-background.imageset/Contents.json
  Sources/Onboarding/OnboardingPreferences.swift
  Sources/Onboarding/ProductNotifications/CookieNotificationBlockingConsentView.swift
  Sources/Onboarding/ProductNotifications/FullScreenCalloutManager.swift
Labels: QA/Yes

#7892 Fix #7860: Default Browser Prompt NTP - Logic Change
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Sources/Brave/Frontend/Browser/New Tab Page/Sections/NTPDefaultBrowserCalloutProvider.swift
  Sources/Onboarding/ProductNotifications/FullScreenCalloutManager.swift
Labels: Epic: NTP

#7894 Fix #7893: Browser Lock - Cancel Issue
  Sources/Brave/Frontend/Passcode/WindowProtection.swift
Labels: bug, priority/P1

#7910 Fix #7909: Handle JitsiMeet delegate methods to close unjoined calls.
  Sources/BraveTalk/BraveTalkJitsiCoordinator.swift
Labels: Epic: Brave Talk

#7915 Fix #7911: Switches to private tab mode when using biometric authentication in sync flow
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/Brave/Frontend/Browser/Tabs/TabTray/Views/TabSyncCustomView.swift
  Sources/Brave/Frontend/Login/LoginAuthViewController.swift
  Sources/Brave/Frontend/Passcode/WindowProtection.swift
  Sources/Brave/Frontend/Widgets/LoadingViewController.swift
Labels: bug, priority/P2

#7922 [release] Update brave-core to 1.57.53
  package-lock.json
  package.json
Labels: QA/No

#7928 Ref #7927: Update brave-core to 1.58.99
  package-lock.json
  package.json
Labels: QA/No

#7925 [No Bug]: Disconnect before showing VPN buy screen
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/VPNMenuButton.swift
  Sources/BraveVPN/BraveVPN.swift
Labels: QA/No, Epic: VPN

#7929 Fix #7930: Missing main actor isolation of preference on async method
  Sources/Brave/WebFilters/FilterListResourceDownloader.swift
  Sources/Brave/WebFilters/FilterListStorage.swift
Labels: QA/No

#7926 Fix #7916: Fix Playlist script to work on dynamic history sites
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/PlaylistScript.js
Labels: QA/Yes, Epic: Playlist

#7862 Fix #7861: Adds Query Parameter Filtering/Stripping
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/Tab.swift
Labels: needs security review, QA/Yes

#7919 Fix #7897: Clearing Out Data From Recently Closed Tabs
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+TabManagerDelegate.swift
  Sources/Brave/Frontend/Browser/Tabs/RecentlyClosedTabs/RecentlyClosedTabsView.swift
Labels: bug

#7941 Fix #7920: Fix cookie consent upgrade
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/AdvancedShieldSettings.swift
  Sources/Brave/WebFilters/FilterListResourceDownloader.swift
  Sources/Brave/WebFilters/FilterListStorage.swift
Labels: bug

#7951 Fix #7875: VPN Restore Infinite Loading
  Sources/BraveVPN/BuyVPNViewController.swift
  Sources/BraveVPN/IAPObserver.swift
Labels: bug, Epic: VPN

#7959 Fix #7952: Opening link in private tab will bypass biometrics authentication
  Sources/Brave/Extensions/SceneExtensions.swift
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+TabManagerDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Sources/Brave/Frontend/Passcode/WindowProtection.swift
  Sources/Brave/Frontend/Sync/SyncSettingsTableViewController.swift
  Sources/Brave/Frontend/Sync/SyncViewController.swift
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/Brave/Frontend/Widgets/LoadingViewController.swift
Labels: bug, priority/P2

#7918 Fix #7887: Sync UX improvement - Conditional Device Number
  Sources/Brave/Frontend/Sync/BraveCore/BraveSyncAPIExtensions.swift
  Sources/Brave/Frontend/Sync/SyncPairCameraViewController.swift
  Sources/Brave/Frontend/Sync/SyncPairWordsViewController.swift
  Sources/Brave/Frontend/Sync/SyncSettingsTableViewController.swift
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/Brave/Migration/Migration.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: enhancement, Epic: Sync

#7917 Fix #7258: Fix Playback Rate resetting in PIP
  Sources/Brave/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift
Labels: Epic: Playlist, Epic: Playlist (CarPlay)

#7981 Fix #7980: [Follow up to #7952] Opening in private from home screen will bypass biometrics
  Sources/Brave/Extensions/SceneExtensions.swift
  Sources/Brave/Frontend/Browser/NavigationRouter.swift
  Sources/Brave/Frontend/Browser/QuickActions.swift
  Sources/Brave/Frontend/Passcode/WindowProtection.swift
Labels: bug, priority/P2

#7984 Ref # 7887: Sync UX improvement - Conditional Device Number - Localization Change
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: Epic: Sync
