Repository brave/brave-ios, pull requests merged in 2023-06, with the labels that each got.

#7552 No Bug: Reverting App Review Logic to use legacy Logic
  Sources/Growth/AppReviewManager.swift
Labels: QA/No

#7542 Fix #7541: Fixing CarPlay Next and Previous steering wheel buttons
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistManager.swift
  Sources/Brave/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift
Labels: Epic: Playlist, Epic: Playlist (CarPlay)

#7100 Fix #7084: New P3A Questions for iOS specific feature
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+P3A.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift
Labels: Epic: P3A

#7565 No Bug: Update Leo SF Symbols
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Sources/Brave/Frontend/Browser/ReaderModeBarView.swift
  Sources/Brave/Frontend/Browser/SendTab/SendTabToSelfController.swift
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController+TableViewDelegate.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Sources/BraveNews/Customize/NewsSettingsView.swift
  Sources/BraveNews/FeedSectionHeaderView.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.share.macos.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.smartphone.tablet-portrait.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.smartphone.tablet.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.tune.symbolset/Contents.json
  package-lock.json
  package.json
Labels: QA/No

#7581 No Bug: Separate `URLMatcher` from `DebounceService`
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/WebFilters/AdblockResourceDownloader.swift
  Sources/Brave/WebFilters/DebouncingResourceDownloader.swift
  Sources/Brave/WebFilters/DebouncingService.swift
  Sources/Brave/WebFilters/URLMatcher/URLMatcher.swift
  Tests/ClientTests/Web Filters/DebouncingServiceTests.swift
Labels: QA/No

#7564 No Bug: Improve script tests
  Tests/ClientTests/User Scripts/MockMessageHandler.swift
  Tests/ClientTests/User Scripts/MockScriptsViewController.swift
  Tests/ClientTests/User Scripts/ScriptExecutionTests.swift
Labels: QA/No

#7588 Fix #5543: Relax SSL Certificate Validation to match all other browsers
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/CertificateUtilities/BraveCertificateUtils.swift
Labels: needs security review

#7602 No Bug: Add followed locales & decoding errors to News debug settings
  Sources/BraveNews/Composer/FeedDataSource.swift
  Sources/BraveNews/Settings/BraveNewsDebugSettingsView.swift
  Sources/CodableHelpers/FailableDecodable.swift
Labels: QA/No

#7534 Fix #7443: Migrate User Assets from BraveCore to CoreData
  Sources/BraveWallet/Crypto/Stores/AccountActivityStore.swift
  Sources/BraveWallet/Crypto/Stores/AssetDetailStore.swift
  Sources/BraveWallet/Crypto/Stores/CryptoStore.swift
  Sources/BraveWallet/Crypto/Stores/NFTStore.swift
  Sources/BraveWallet/Crypto/Stores/PortfolioStore.swift
  Sources/BraveWallet/Crypto/Stores/SelectAccountTokenStore.swift
  Sources/BraveWallet/Crypto/Stores/SendTokenStore.swift
  Sources/BraveWallet/Crypto/Stores/SettingsStore.swift
  Sources/BraveWallet/Crypto/Stores/SwapTokenStore.swift
  Sources/BraveWallet/Crypto/Stores/TransactionConfirmationStore.swift
  Sources/BraveWallet/Crypto/Stores/TransactionDetailsStore.swift
  Sources/BraveWallet/Crypto/Stores/TransactionsActivityStore.swift
  Sources/BraveWallet/Crypto/Stores/UserAssetsStore.swift
  Sources/BraveWallet/Crypto/Stores/WalletStore.swift
  Sources/BraveWallet/Extensions/BraveWalletExtensions.swift
  Sources/BraveWallet/Extensions/WalletServiceExtensions.swift
  Sources/BraveWallet/Preview Content/MockStores.swift
  Sources/BraveWallet/WalletPreferences.swift
  Sources/BraveWallet/WalletUserAssetManager.swift
  Sources/Data/models/Domain.swift
  Sources/Data/models/Model.xcdatamodeld/.xccurrentversion
  Sources/Data/models/Model.xcdatamodeld/Model21.xcdatamodel/contents
  Sources/Data/models/WalletUserAsset.swift
  Sources/Data/models/WalletUserAssetGroup.swift
  Tests/BraveWalletTests/AccountActivityStoreTests.swift
  Tests/BraveWalletTests/AssetDetailStoreTests.swift
  Tests/BraveWalletTests/NFTStoreTests.swift
  Tests/BraveWalletTests/PortfolioStoreTests.swift
  Tests/BraveWalletTests/SelectAccountTokenStoreTests.swift
  Tests/BraveWalletTests/SendTokenStoreTests.swift
  Tests/BraveWalletTests/SwapTokenStoreTests.swift
  Tests/BraveWalletTests/TransactionConfirmationStoreTests.swift
  Tests/BraveWalletTests/TransactionsActivityStoreTests.swift
  Tests/BraveWalletTests/UserAssetsStoreTests.swift
  Tests/DataTests/WalletUserAssetGroupTests.swift
  Tests/DataTests/WalletUserAssetTests.swift
Labels: needs security review

#7614 Ref #7596: User can open "Sync" settings screen when device screen lock is disabled
  Sources/Brave/Frontend/Login/LoginAuthViewController.swift
  Sources/Brave/Frontend/Sync/SyncViewController.swift
Labels: bug

#7589 Fix #7497: Rate App News Card & Logic
  Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Sources/Brave/Frontend/Browser/New Tab Page/Sections/BraveNewsSectionProvider.swift
  Sources/BraveNews/Cards/RateCardViews.swift
  Sources/BraveNews/Composer/FeedCard.swift
  Sources/BraveNews/Composer/FeedCardGenerator.swift
  Sources/BraveNews/Composer/FeedDataSource.swift
  Sources/BraveNews/FeedItemView.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveUI/Extensions/UIActionExtensions.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.thumb.up.symbolset/Contents.json
  Sources/Growth/AppReviewManager.swift
  Sources/Growth/GrowthPreferences.swift
  Tests/GrowthTests/AppReviewManagerLegacyTests.swift
  Tests/GrowthTests/AppReviewManagerRevisedTests.swift
Labels: enhancement, Epic: Brave News

#7551 Fix #7032: Voice Search
  App/iOS/Supporting Files/Info.plist
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCarplayManager.swift
  Sources/Brave/Frontend/Browser/Search/Voice Search/SpeechRecognizer.swift
  Sources/Brave/Frontend/Browser/Search/Voice Search/VoiceSearchInputView.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/BottomToolbarView.swift
  Sources/Brave/Frontend/Browser/Toolbars/ToolbarButton.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/UrlBarTextField.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.microphone.symbolset/Contents.json
Labels: enhancement

#7635 Ref #7032: Voice Search - Remove online recognition references
  App/iOS/Supporting Files/Info.plist
  Sources/Brave/Frontend/Browser/Search/Voice Search/SpeechRecognizer.swift
Labels: QA/No

#7629 Fix #7606: VPN toggle switch is blinking twice when enabling it
  Sources/BraveVPN/BraveVPNProtocolPickerViewController.swift
  Sources/BraveVPN/BraveVPNSettingsViewController.swift
Labels: bug, Epic: VPN

#7633 Fix # 7605: Camera view is rotated to 90 degrees in "Scan QR Code" UI when a device in Landscape Mode
  Sources/Brave/Frontend/Browser/Search/Recent Search/RecentSearchQRCodeScannerController.swift
Labels: bug

#7641 Fix #6260: Reverse order of URL bar context menu items when using bottom bar
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/Shared/SharedStrings.swift
Labels: enhancement

#7650 [release branch] Ref #7378: Update brave-core to 1.52.129
  package-lock.json
  package.json
Labels: QA/No
