Repository brave/brave-ios, pull requests merged in 2023-01, with the labels that each got.

#6530 Fix #6154: Enable Solana Dapps by Default
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/Browser/UserScriptManager.swift
  Sources/BraveWallet/Crypto/CryptoView.swift
  Sources/BraveWallet/Panels/WalletPanelView.swift
  Sources/BraveWallet/Settings/WalletSettingsView.swift
  Sources/BraveWallet/WalletConstants.swift
  Sources/BraveWallet/WalletStrings.swift
Labels: needs security review

#6688 Ref #6684: Onboarding Default Browser Callout Multi-line button
  Sources/BraveShared/BraveStrings.swift
  Sources/Onboarding/Welcome/WelcomeViewCallout.swift
  Sources/Onboarding/Welcome/WelcomeViewController.swift
Labels: bug

#6690 Fix #6675: Both reveal and copy password actions should prompt for authentication
  Client/Frontend/Login/LoginInfoTableViewCell.swift
  Client/Frontend/Login/LoginInfoViewController.swift
Labels: bug

#6708 Fix #6657 - #6665 - #6456: Sync QR Code related issues
  Client/Frontend/Sync/SyncAddDeviceViewController.swift
  Client/Frontend/Sync/SyncQRCodeView.swift
  Client/Frontend/Sync/SyncSelectDeviceTypeViewController.swift
  Client/Frontend/Sync/SyncSettingsTableViewController.swift
  Client/Frontend/Sync/SyncWelcomeViewController.swift
Labels: bug, Epic: Sync

#6704 Fix ##6687: Don't show sms/tel dialog for non-active tabs
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/BraveShared/BraveStrings.swift
Labels: security

#6725 No Bug: Upgrade CodeQL action
  .github/workflows/codeql-analysis.yml
Labels: security

#6720 Fix #6715: Remove use of Playability API
  Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistDownloadManager.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistManager.swift
  Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/PlaylistScriptHandler.swift
Labels: Epic: Playlist

#6718 Fix: #6717 - Playlist Downloading ID not consistent
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
  Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
  Client/Frontend/Browser/Playlist/Utilities/PlaylistMediaStreamer.swift
Labels: Epic: Playlist

#6716 Fix #6670: Playlist icon disappearing in URL bar
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/PlaylistScriptHandler.swift
Labels: Epic: Playlist

#6736 No Bug: Add iOS 16.2 check to list offset workaround modifier
  Sources/BraveUI/SwiftUI/ListInitialOffsetWorkaround.swift
Labels: QA/No

#6744 Ref #6739: Also allow individual Brave News feeds to fail silently
  Sources/BraveNews/Composer/FeedDataSource.swift
Labels: QA/No

#6780 Fix #6779: Customize Brave Tabs bar modal doesn't show Maybe later button on iOS 14 light theme
  Sources/Onboarding/Callouts/OnboardingBottomBarView.swift
Labels: bug

#6781 Fix #6294: Bookmark import not working
  Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift
Labels: bug

#6783 No Bug: Remove missed dead legacy transfer strings & UI
  Client/Frontend/Brave Rewards/Common/LegacyWalletTransferButton.swift
  Client/Frontend/Brave Rewards/Common/LegacyWalletTransferStatusButton.swift
  Sources/BraveShared/BraveStrings.swift
Labels: QA/No

#6768 Fix #16677: URLFormatter Displays incorrect format
  Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
  Client/Frontend/Shields/ShieldsViewController.swift
Labels: priority/P2, needs security review, Epic: Security

#6777 Fix #6796: Reader-Mode uses InternalURL and WKURLSchemeHandler
  App/iOS/Delegates/AppDelegate.swift
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+CoreMigration.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift
  Client/Frontend/Browser/Handlers/ReaderModeHandler.swift
  Client/Frontend/Browser/Handlers/SessionRestoreHandler.swift
  Client/Frontend/Browser/Helpers/ErrorPageHelper.swift
  Client/Frontend/Browser/Interstitial Pages/InternalSchemeHandler.swift
  Client/Frontend/Browser/SessionData.swift
  Client/Frontend/Reader/ReaderModeHandlers.swift
  Client/Frontend/Sync/WebFilter/Bookmarks/BookmarksInterstitial.swift
  Client/Frontend/UserContent/UserScripts/Sandboxed/MainFrame/AtDocumentEnd/FindInPageScript.js
  Client/Frontend/UserContent/UserScripts/Sandboxed/MainFrame/AtDocumentStart/ReaderModeScript.js
  Client/Networking/WebServer.swift
  Sources/BraveShared/BraveStrings.swift
  Sources/Shared/Extensions/URLExtensions.swift
  Tests/BraveSharedTests/NSURLExtensionsTests.swift
  Tests/ClientTests/ClientTests.swift
Labels: Epic: Reader-mode, Epic: Cleanup

#6805 Fix #6656: Remove wallet injection from Private Browsing
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Client/Frontend/Browser/TabManager.swift
Labels: Epic: Brave Wallet

#6804 Fix #6749: Change Playlist autoplay to be ON by default
  Client/Migration/Migration.swift
Labels: Epic: Playlist

#6825 Fix #2806: Support Full Page Screenshots of Website
  Client/Frontend/Browser/BrowserViewController.swift
Labels: enhancement

#6836 No bug: Duplicated translation key.
  Sources/BraveShared/BraveStrings.swift
Labels: QA/No

#6755 Fix #3395: Add Recently Closed Tabs
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabManagerDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Helpers/FaviconImage.swift
  Client/Frontend/Browser/PrivacyHub/PrivacyReportAllTimeListsView.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/TabManager.swift
  Client/Frontend/Browser/Tabs/RecentlyClosedTabs/RecentlyClosedTabsView.swift
  Client/Frontend/Browser/Tabs/TabBar/TabBarCell.swift
  Client/Frontend/Browser/Tabs/TabBar/TabsBarViewController.swift
  Client/Frontend/Browser/Tabs/TabTray/TabTrayAnimation.swift
  Client/Frontend/Browser/Tabs/TabTray/TabTrayController+CollectionViewDelegate.swift
  Client/Frontend/Browser/Tabs/TabTray/TabTrayController+KeyCommands.swift
  Client/Frontend/Browser/Tabs/TabTray/TabTrayController+SearchResultDelegate.swift
  Client/Frontend/Browser/Tabs/TabTray/TabTrayController+TableViewDelegate.swift
  Client/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Client/Frontend/Browser/Tabs/TabTray/Views/TabSyncContainerView.swift
  Client/Frontend/Browser/Tabs/TabTray/Views/TabSyncCustomView.swift
  Client/Frontend/Browser/Tabs/TabTray/Views/TabTrayButtons.swift
  Client/Frontend/Browser/Tabs/TabTray/Views/TabTrayCell.swift
  Client/Frontend/Browser/Tabs/TabTray/Views/TabTrayContainerView.swift
  Client/Frontend/Browser/Tabs/TabTray/Views/TabTrayPrivateModeInfoView.swift
  Client/Frontend/Browser/Tabs/TabTray/Views/TabTraySearchView.swift
  Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Client/Migration/Migration.swift
  Sources/BraveShared/BraveStrings.swift
  Sources/BraveWallet/Settings/CustomNetworkListView.swift
  Sources/Data/models/Model.xcdatamodeld/.xccurrentversion
  Sources/Data/models/Model.xcdatamodeld/Model17.xcdatamodel/contents
  Sources/Data/models/RecentlyClosed.swift
  Sources/Data/models/TabMO.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.arrow.counterclockwise.rectangle.portrait.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/brave.arrow.counterclockwise.rectangle.portrait.symbolset/brave.arrow.counterclockwise.rectangle.portrait.svg
  Tests/DataTests/RecentlyClosedTests.swift
Labels: enhancement

#6819 Fix #6789: Omnibox disappears when the cookie consent banner/toast appears
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+CookieNotificationBlocking.swift
Labels: bug

#6821 Fix # 6554: Only NTP Present, Brave Should Open External Links Within That Same Tab
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/TabManager.swift
Labels: enhancement

#6838 Fix #2123, fix #1048: Allow ‘Reopen Last Closed Tab’ Shortcut (iPadOS) - Add Shake to Reopen in the Tab screen
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+BraveTalk.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabManagerDelegate.swift
  Client/Frontend/Browser/Search/SearchViewController+KeyCommands.swift
  Client/Frontend/Browser/Search/SearchViewController.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/Tabs/TabBar/TabsBarViewController.swift
  Client/Frontend/Browser/Tabs/TabTray/TabTrayController+KeyCommands.swift
  Client/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
  Sources/BraveShared/BraveStrings.swift
  Sources/Shared/SharedStrings.swift
Labels: enhancement

#6814 Fix #6813: Remove usage of LocalRequestHandler in internal scripts
  Client/Assets/Interstitial Pages/Pages/GenericError.html
  Client/Frontend/Browser/Handlers/ReaderModeHandler.swift
  Client/Frontend/Browser/Interstitial Pages/GenericErrorPageHandler.swift
  Client/Frontend/Browser/Interstitial Pages/InternalSchemeHandler.swift
  Client/Frontend/Reader/ReadabilityService.swift
  Client/Frontend/Reader/ReaderViewLoading.html
  Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Internal/LocalRequestHelper.swift
Labels: needs security review
