Repository brave/brave-ios, pull requests merged in 2023-09, with the labels that each got.

#8011 Ref #7980: [Follow up to #7952] Opening in private from home screen will bypass biometrics
  Sources/Brave/Frontend/Browser/NavigationRouter.swift
  Sources/Brave/Frontend/Browser/QuickActions.swift
  Sources/Brave/Frontend/Passcode/WindowProtection.swift
Labels: bug

#8015 Fix #7996: Switching Private Mode Tab Tray cause position loss in Normal Mode
  Sources/Brave/Frontend/Browser/TabManager.swift
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
Labels: bug

#7999 Ref # 7887: Sync UX improvement - Conditional Device Number - Text Change
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: Epic: Sync

#8032 Fix #7851: Tab selection for TabsBar interface is done after active website is loaded
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/Tabs/TabBar/TabsBarViewController.swift
Labels: enhancement

#8036 No Bug: Cleanup unused code
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Sources/Brave/Migration/Migration.swift
  Sources/BraveShields/BraveGlobalShieldStats.swift
  Sources/Preferences/GlobalPreferences.swift
Labels: QA/No

#8054 Fix #8003: P3A Forward Button usage question
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+P3A.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
Labels: Epic: P3A

#8067 Fix #8045: Default Browser Notification - Update (Text - Default Logic)
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/Onboarding/OnboardingPreferences.swift
Labels: enhancement

#7983 Fix #3939: Add Screen Time support.
  App/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+ScreenTime.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+TabManagerDelegate.swift
  Sources/Brave/Frontend/ClientPreferences.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/OtherPrivacySettingsSectionView.swift
  Sources/BraveShared/BraveURLs.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: needs security review

#8048 Fix #7835: Add Suppress button to Allow link to switch apps?
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/Tab.swift
  Sources/Brave/Frontend/Browser/TabManager.swift
Labels: security

#8119 Fix #8095: Favorites are shown in Private Tab mode when switching the apps
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
Labels: bug, Epic: Private-browsing

#8122 Fix #8087: VPN Reset Configuration Clear confirmation
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveVPN/BraveVPNSettingsViewController.swift
  Sources/BraveVPN/InstallVPNView.swift
Labels: bug, Epic: VPN

#8147 Fix #8146: Fixes Tab Selection and mode switching
  Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
Labels: bug

#8139 Fix # 7770: Discrepancy in the titles of multiple settings screens
  Sources/Brave/Frontend/Browser/PageZoom/PageZoomSettingsView.swift
  Sources/Brave/Frontend/Settings/Display/MediaSettingsView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/FilterLists/FilterListsView.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/PrivacyReportSettingsView.swift
  Sources/Brave/Frontend/Settings/General/SearchEngines/SearchCustomEngineViewController.swift
  Sources/Brave/Frontend/Settings/General/SearchEngines/SearchEnginePicker.swift
  Sources/Brave/Frontend/Settings/General/SearchEngines/SearchSettingsTableViewController.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/Brave/Frontend/Share/PageZoomActivity.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: bug, Epic: Settings

#8149 Fix #8148: Problem with toggling Sync Types from Settings
  Sources/Brave/Frontend/Sync/BraveCore/BraveSyncAPIExtensions.swift
  Sources/Brave/Frontend/Sync/SyncSettingsTableViewController.swift
  Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift
  Sources/Brave/Migration/Migration.swift
Labels: bug, Epic: Sync

#8040 Ref #4879: VPN Churn Improvements - Callout Logic and Settings Changes
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/VPNMenuButton.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/BraveShared/BraveURLs.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/BraveVPN/BraveVPN.swift
  Sources/BraveVPN/BraveVPNPreferences.swift
  Sources/BraveVPN/BraveVPNSettingsViewController.swift
  Sources/BraveVPN/BuyVPNViewController.swift
  Sources/BraveVPN/IAPObserver.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.warning.triangle-filled.symbolset/Contents.json
  Tests/BraveVPNTests/BraveVPNTests.swift
Labels: enhancement, Epic: VPN

#8152 Fix #8017: Opening Private Tab from App Icon Long Press with Basic Challenge
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/QuickActions.swift
Labels: bug
