Repository brave/brave-ios, pull requests merged in 2023-04, with the labels that each got.

#7185 No Bug: Remove old CoreData migration logic.
  App/iOS/Delegates/AppDelegate.swift
  Sources/Brave/Migration/Migration.swift
  Sources/Data/DataPreferences.swift
  Sources/Data/models/DataController.swift
  Sources/DataTestsUtils/CoreDataTestCase.swift
Labels: QA/No

#7212 Ref #7178: Update brave-core to 1.50.114
  package-lock.json
  package.json
Labels: QA/No

#7216 No Bug: Add WireguardExtension to fastlane.
  fastlane/Fastfile
Labels: QA/No, CI/skip

#7151 Fix #6682 - Added playback rate 2.5x
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift
Labels: enhancement

#7201 Fix #7172: Improved App Rating Logic
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistFolderController.swift
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/Brave/Shortcuts/ActivityShortcutManager.swift
  Sources/BraveShared/Preferences.swift
  Sources/Growth/AppReviewManager.swift
  Sources/Growth/GrowthPreferences.swift
  Tests/GrowthTests/AppReviewManagerLegacyTests.swift
  Tests/GrowthTests/AppReviewManagerRevisedTests.swift
  Tests/GrowthTests/LegacyAppReviewTests.swift
Labels: enhancement

#7226 No Bug: Update Guardian Connect to 1.8.0
  App/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
Labels: QA/No

#7251 Ref #6646: Update GuardianConnect to 1.8.1
  App/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
Labels: QA/No

#6857 Fix #6841: Add custom filter list urls
  Sources/Brave/Frontend/Browser/Helpers/LaunchHelper.swift
  Sources/Brave/Frontend/Settings/AdblockDebugMenuTableViewController.swift
  Sources/Brave/Frontend/Settings/FilterListAddURLView.swift
  Sources/Brave/Frontend/Settings/FilterListsView.swift
  Sources/Brave/WebFilters/AdBlockEngineManager.swift
  Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift
  Sources/Brave/WebFilters/CustomFilterListStorage.swift
  Sources/Brave/WebFilters/FilterListCustomURL.swift
  Sources/Brave/WebFilters/FilterListCustomURLDownloader.swift
  Sources/Brave/WebFilters/FilterListResourceDownloader.swift
  Sources/Brave/WebFilters/ShieldStats/Adblock/CachedAdBlockEngine.swift
  Sources/BraveShared/BraveStrings.swift
  Sources/BraveUI/SwiftUI/SectionFooterErrorView.swift
  Sources/BraveWallet/Crypto/BuySendSwap/SendTokenView.swift
  Sources/Data/models/CustomFilterListSetting.swift
  Sources/Data/models/FilterListSetting.swift
  Sources/Data/models/Model.xcdatamodeld/.xccurrentversion
  Sources/Data/models/Model.xcdatamodeld/Model19.xcdatamodel/contents
Labels: needs security review

#7246 Fix: #7240 Add Release Notes for iOS Release 1.49
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip

#7234 Fix #6856: Shortcuts and Intent Donations not working
  App/BrowserIntents/Entitlements/BrowserIntents.entitlements
  App/BrowserIntents/Entitlements/BrowserIntentsBeta.entitlements
  App/BrowserIntents/Entitlements/BrowserIntentsDebug.entitlements
  App/BrowserIntents/Entitlements/BrowserIntentsEnterprise.entitlements
  App/BrowserIntents/Entitlements/BrowserIntentsRelease (AppStore).entitlements
  App/BrowserIntents/Entitlements/BrowserIntentsRelease.entitlements
  App/Client.xcodeproj/project.pbxproj
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Sources/Brave/Shortcuts/ActivityShortcutManager.swift
Labels: bug

#7266 Fix: #7239 Add Release Notes for iOS Release 1.49.1
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip

#7195 Fix #7194: Add `scriptletGlobals`
  Sources/Brave/Frontend/Browser/User Scripts/ScriptFactory.swift
Labels: Epic: Privacy

#7275 Fix #7276: Move filter list storage manager to own file
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+CookieNotificationBlocking.swift
  Sources/Brave/Frontend/Browser/Helpers/LaunchHelper.swift
  Sources/Brave/Frontend/Popup/CookieNotificationBlockingConsentView.swift
  Sources/Brave/Frontend/Settings/AdblockDebugMenuTableViewController.swift
  Sources/Brave/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift
  Sources/Brave/Frontend/Settings/FilterListsView.swift
  Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift
  Sources/Brave/WebFilters/FilterListResourceDownloader.swift
  Sources/Brave/WebFilters/FilterListStorage.swift
  Sources/BraveShared/Preferences.swift
Labels: QA/Yes

#7264 Fix #7103: Shields show Session Restore - Reader Mode Internal URL
  Sources/Brave/Frontend/Shields/ShieldsViewController.swift
  Sources/BraveShared/Extensions/URLExtensions.swift
  Tests/BraveSharedTests/URLExtensionTests.swift
Labels: bug

#7290 No Bug: Use correct table name for two Wallet localized strings.
  Sources/BraveWallet/WalletStrings.swift
Labels: QA/No

#7270 Fix #6824: Recent searches 'show more' text is cut in some languages
  Sources/Brave/Frontend/Browser/Search/Recent Search/RecentSearchHeaderView.swift
Labels: bug

#7274 No Bug: Log Brave blocking
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/RequestBlockingScript.js
Labels: QA/No

#7273 Fix #7272: Use symbol in scripts
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/RewardsReportingScript.js
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/TrackingProtectionStats.js
Labels: QA/Yes

#7292 Fix #5981: Full Screen - Popover Callout Optimizations
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+CookieNotificationBlocking.swift
  Sources/BraveUI/Images/GIFImage.swift
  Sources/Onboarding/ProductNotifications/CookieNotificationBlockingConsentView.swift
  Sources/Onboarding/ProductNotifications/PasscodeMigrationView.swift
  Sources/Onboarding/ProductNotifications/Resources/FullScreenCalloutManager.swift
Labels: enhancement

#7307 No Bug: Update Guardian Connect to 1.8.3
  App/Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
Labels: QA/No

#7309 Revert "Ref #7168: Update News widget ordering to be based on recency"
  App/BraveWidgets/News Topics/NewsTopicsModel.swift
Labels: QA/No

#7314 Ref #7302: Update Leo SF Symbols version
  package-lock.json
  package.json
Labels: QA/No

#7174 Fix #7173: NFT tab
  Sources/BraveWallet/Blockies/Blockies.swift
  Sources/BraveWallet/Crypto/AssetIconView.swift
  Sources/BraveWallet/Crypto/CryptoPagesView.swift
  Sources/BraveWallet/Crypto/NFT/NFTDetailView.swift
  Sources/BraveWallet/Crypto/NFT/NFTView.swift
  Sources/BraveWallet/Crypto/Portfolio/PortfolioView.swift
  Sources/BraveWallet/Crypto/Stores/CryptoStore.swift
  Sources/BraveWallet/Crypto/Stores/NFTStore.swift
  Sources/BraveWallet/Crypto/Stores/PortfolioStore.swift
  Sources/BraveWallet/Crypto/Transaction Confirmations/SwapTransactionConfirmationView.swift
  Sources/BraveWallet/Extensions/BraveWalletSwiftUIExtensions.swift
  Sources/BraveWallet/WalletStrings.swift
  Tests/BraveWalletTests/NFTStoreTests.swift
  Tests/BraveWalletTests/PortfolioStoreTests.swift
Labels: needs security review

#7322 Ref #7303: Fix Recently Closed Tabs and Tab Restore
  Sources/Brave/Migration/Migration.swift
Labels: QA/No

#7327 No Bug: Always include a contact form issue type.
  Sources/BraveVPN/BraveVPNContactFormViewController.swift
Labels: QA/No

#7332 Ref #6646: Region Change with preferred Tunnel
  Sources/BraveVPN/BraveVPN.swift
Labels: QA/No

#7298 Fix #7202: Wallet Market Tab
  Sources/BraveWallet/Crypto/Asset Details/AssetDetailHeaderView.swift
  Sources/BraveWallet/Crypto/Asset Details/AssetDetailView.swift
  Sources/BraveWallet/Crypto/CryptoPagesView.swift
  Sources/BraveWallet/Crypto/Market/MarketView.swift
  Sources/BraveWallet/Crypto/Portfolio/PortfolioView.swift
  Sources/BraveWallet/Crypto/Search/AssetSearchView.swift
  Sources/BraveWallet/Crypto/Stores/AssetDetailStore.swift
  Sources/BraveWallet/Crypto/Stores/CryptoStore.swift
  Sources/BraveWallet/Crypto/Stores/MarketStore.swift
  Sources/BraveWallet/Extensions/BlockchainRegistryExtensions.swift
  Sources/BraveWallet/Extensions/BraveWalletExtensions.swift
  Sources/BraveWallet/Extensions/BraveWalletSwiftUIExtensions.swift
  Sources/BraveWallet/Extensions/WalletNumberFormatterExtensions.swift
  Sources/BraveWallet/Extensions/WeiFormatter.swift
  Sources/BraveWallet/Preview Content/MockStores.swift
  Sources/BraveWallet/WalletStrings.swift
  Tests/BraveWalletTests/MarketStoreTests.swift
  Tests/BraveWalletTests/WeiFormatterTests.swift
Labels: needs security review

#7329 No Bug: Replace macOS app with a script for making leo asset catalogs
  Package.swift
  Plugins/LeoAssetsPlugin/LeoAssetsPlugin.swift
  Plugins/LeoAssetsPlugin/make_asset_catalog.sh
Labels: needs-security-review

#7325 No Bug: Update CI to macOS 13 and Xcode 14.3
  .github/workflows/build_and_test.yml
Labels: QA/No

#7348 Fix #7347: Remove unnecessary PIP code on iOS 15+ (prevents potential crash).
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistViewController+AVDelegates.swift
  Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift
  Sources/Brave/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift
  Sources/Brave/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift
Labels: Epic: Playlist
