Repository brave/brave-ios, pull requests merged in 2023-10, with the labels that each got.

#8177 No Bug: Update github actions variables
  .github/workflows/build_and_test.yml
  fastlane/Fastfile
Labels: QA/No

#8176 [release] Ref #7927: Update brave-core to 1.58.135
  package-lock.json
  package.json
Labels: QA/No

#8117 Fix #8007: Add additional details to webcompat report
  Sources/Brave/Frontend/Shields/ShieldsViewController.swift
  Sources/BraveShields/WebcompatReporter.swift
  Sources/Data/models/Domain.swift
  Tests/BraveSharedTests/URLExtensionTests.swift
Labels: needs security review

#7905 Add Release Notes for iOS Release 1.52
  CHANGELOG.md
Labels: QA/No, release-notes/exclude, CI/skip

#8186 Fix 8163: Notification asking to set Brave as the default browser is still shown after an external link opened via the 3P app
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Onboarding/OnboardingPreferences.swift
Labels: bug

#8196 [release] Ref #7927: Update brave-core to 1.58.139
  package-lock.json
  package.json
Labels: QA/No

#8202 Ref #8078: Fix collapsed URL bar background color
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
Labels: QA/No

#8269 Fix #8268: UIGraphicsBeginImageContextWithOptions causing Intermittent crash while taking Tab Screenshot
  Sources/Brave/Extensions/UIViewExtensions.swift
  Sources/Favicon/BundledFaviconRenderer.swift
  Sources/Favicon/UIImage+FaviconRenderer.swift
  Sources/Onboarding/Callouts/OnboardingPlaylistView.swift
  Sources/Shared/Extensions/UIImageExtensions.swift
Labels: bug

#8314 Fix #8255: Reordering Favourites shows duplicated items
  Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift
Labels: bug

#8315 Fix #8236: Adding export fail case and alert for success
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: bug

#8323 Fix #8316: Onboarding Title Case Text Change
  Sources/BraveStrings/BraveStrings.swift
Labels: bug

#8325 Fix #8317: Menu Update for VPN Status
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
Labels: bug

#8306 Fix #8305 - Ref #8297: Allow Syncing All History - Update brave-core to 1.60.105
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+BraveTalk.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+IPFSScheme.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+UIDropInteractionDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Web3NameService.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Sources/Brave/Frontend/Browser/Toolbars/ToolbarUrlActionsDelegate.swift
  Sources/Brave/Frontend/Sync/BraveCore/History/HistoryAPIExtensions.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Internal/Web3IPFSScriptHandler.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Internal/Web3NameServiceScriptHandler.swift
  Sources/Brave/Shortcuts/ActivityShortcutManager.swift
  Sources/Shared/Extensions/URLExtensions.swift
  Tests/BraveSharedTests/NSURLExtensionsTests.swift
  package-lock.json
  package.json
Labels: Epic: Sync

#8336 [Uplift] Impose the max engines limitation on content blockers (uplift to 1.58.1)
  Sources/Brave/Frontend/Browser/Helpers/LaunchHelper.swift
  Sources/Brave/WebFilters/AdblockResourceDownloader.swift
  Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift
  Sources/Brave/WebFilters/FilterListCustomURLDownloader.swift
  Sources/Brave/WebFilters/FilterListResourceDownloader.swift
  Sources/Brave/WebFilters/ShieldStats/Adblock/AdBlockStats.swift
  Tests/ClientTests/ContentBlockerManagerTests.swift
Labels: QA/No

#8335 Fix #8329: Send to your Devices action "Send" button placement
  Sources/Brave/Frontend/Browser/SendTab/SendTabToSelfController.swift
  Sources/BraveStrings/BraveStrings.swift
  Tests/CertificateUtilitiesTests/Certificates/leaf.cer
  Tests/CertificateUtilitiesTests/Certificates/self-signed.cer
Labels: Epic: Sync
