Repository brave/brave-ios, pull requests merged in 2023-02, with the labels that each got.

#6524 Fix #5789: Pin Certs with Chromium API
  Client/Assets/Interstitial Pages/Pages/CertificateError.html
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Interstitial Pages/CertificateErrorPageHandler.swift
  Client/Frontend/Browser/Interstitial Pages/GenericErrorPageHandler.swift
  Client/Frontend/Browser/Tab.swift
  Client/Frontend/Browser/TabManagerNavDelegate.swift
  Sources/BraveShared/BraveStrings.swift
  Tests/BraveSharedTests/CertificatePinningTest.swift
Labels: needs security review, Epic: Security

#6864 Ref #6863 - Bump Brave-Core to 1.48.154
  Client/Frontend/Browser/Tabs/TabTray/TabTrayController+TableViewDelegate.swift
  Sources/BraveWallet/Extensions/SwapServiceExtension.swift
  Tests/ClientTests/SearchTests.swift
  package-lock.json
  package.json
Labels: Epic: Brave Core

#6882 Fix #6881: Disable filter lists when shields are off
  Client/WebFilters/ShieldStats/Adblock/CachedAdBlockEngine.swift
Labels: QA/Yes

#6898 Fix #4998: Fix auto-play playing without obeying the preference
  Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift
Labels: QA/Yes

#6887 Fix #6886: Refactor Certificate Evaluation to Async-Await
  Client/Frontend/Browser/BrowserViewController.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
  Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift
  Sources/BraveShared/BraveCertificateUtils.swift
Labels: QA/Yes

#6876 Fix #6873: Back button to NTP is not active/tappable
  Sources/Brave/Frontend/Browser/Interstitial Pages/InternalSchemeHandler.swift
Labels: bug

#6901 Fix #6586: Unable to redirect Apple Maps URLs to the Maps app properly
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
Labels: bug

#6947 Ref #6863: Update brave-core to 1.48.163
  package-lock.json
  package.json
Labels: QA/No

#6950 Fix #6917 - Fix Favicons showing transparent & caching
  Sources/Brave/Frontend/Browser/Favicons/LargeFaviconView.swift
  Sources/Brave/Frontend/Browser/Favicons/UIImageView+Favicon.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
  Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
  Sources/Favicon/Assets/top_sites.json
  Sources/Favicon/BundledFaviconRenderer.swift
  Sources/Favicon/Favicon.swift
  Sources/Favicon/FaviconFetcher.swift
  Sources/Favicon/FaviconRenderer.swift
  Sources/Favicon/UIImage+FaviconRenderer.swift
Labels: QA/Yes, Epic: NTP

#6958 Ref #6957- Bump Brave-Core to 1.49.100
  Sources/Brave/Frontend/Rewards/BraveRewards.swift
  Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/RewardsReportingScriptHandler.swift
  Sources/BraveWallet/Crypto/Stores/AccountActivityStore.swift
  Sources/BraveWallet/Crypto/Stores/AssetDetailStore.swift
  Sources/BraveWallet/Crypto/Stores/CryptoStore.swift
  Sources/BraveWallet/Crypto/Stores/KeyringStore.swift
  Sources/BraveWallet/Crypto/Stores/TransactionConfirmationStore.swift
  Sources/BraveWallet/Extensions/RpcServiceExtensions.swift
  Sources/BraveWallet/Preview Content/MockBraveWalletService.swift
  Sources/BraveWallet/Preview Content/MockEthTxService.swift
  Sources/BraveWallet/Preview Content/MockJsonRpcService.swift
  Sources/BraveWallet/Preview Content/MockKeyringService.swift
  Tests/BraveWalletTests/AccountActivityStoreTests.swift
  Tests/BraveWalletTests/PortfolioStoreTests.swift
  Tests/BraveWalletTests/SendTokenStoreTests.swift
  Tests/BraveWalletTests/UserAssetsStoreTests.swift
  package-lock.json
  package.json
Labels: Epic: Brave Core

#6963 [No Bug] - Fix Favicon DCHECK when loading default icon from Brave-Core
  App/iOS/Icons.xcassets/default_world_favicon.imageset/Contents.json
  App/iOS/Icons.xcassets/default_world_favicon.imageset/Image@2x 1.png
  App/iOS/Icons.xcassets/default_world_favicon.imageset/Image@2x.png
Labels: QA/No

#6978 Ref #6957: Update brave-core to 1.49.106
  package-lock.json
  package.json
Labels: QA/No

#7001 No Bug: Fix FavoritesWidget enum case warning
  App/BraveWidgets/FavoritesWidget.swift
Labels: QA/No

#7002 Fix #6294: Bookmark import not working
  Sources/Brave/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift
Labels: bug

#7004 [release branch] Ref #6863: Update brave-core to 1.48.171
  package-lock.json
  package.json
Labels: QA/No

#7003 No Bug: Add new scheme to build with entitlements & release bundle id
  App/Client.xcodeproj/project.pbxproj
  App/Client.xcodeproj/xcshareddata/xcschemes/Debug (AppStore).xcscheme
  App/Configuration/Debug-AppStore.xcconfig
  App/iOS/Entitlements/Debug (AppStore).entitlements
Labels: QA/No

#7028 Ref #6957: Update brave-core to 1.49.115
  Sources/Brave/Frontend/Sync/BraveCore/BraveSyncAPIExtensions.swift
  Sources/BraveWallet/Preview Content/MockJsonRpcService.swift
  package-lock.json
  package.json
Labels: Epic: Brave Core
