Repository brave/brave-ios, pull requests merged in 2024-02, with the labels that each got.

#8716 Fix #8663: Account Details v2
  Sources/BraveWallet/Crypto/Accounts/AccountTransactionListView.swift
  Sources/BraveWallet/Crypto/Accounts/AccountsView.swift
  Sources/BraveWallet/Crypto/Accounts/Activity/AccountActivityView.swift
  Sources/BraveWallet/Crypto/AssetsListView.swift
  Sources/BraveWallet/Crypto/CryptoView.swift
  Sources/BraveWallet/Crypto/NFTsGridView.swift
  Sources/BraveWallet/Crypto/Stores/AccountActivityStore.swift
  Sources/BraveWallet/Crypto/Transactions/TransactionParser.swift
  Sources/BraveWallet/Crypto/Transactions/TransactionsListView.swift
  Sources/BraveWallet/SearchBar.swift
  Sources/BraveWallet/WalletStrings.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.grid04.symbolset/Contents.json
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.lock.dots.symbolset/Contents.json
  Tests/BraveWalletTests/AccountActivityStoreTests.swift
Labels: puLL-Merge

#8742 Fix #8736: Fix No Spam NFTs
  Sources/BraveWallet/Crypto/Stores/CryptoStore.swift
Labels: unverified-commits

#8756 Fix #8755: Add variations as stable for Griffin until Channel is fixed in Brave-Core
  App/iOS/Delegates/AppState.swift
Labels: QA/Yes

#8692 Add Release Notes for iOS Release 1.61
  CHANGELOG.md
Labels: QA/No, CI/skip
