Repository brave/brave-ios, pull requests merged in 2024-01, with the labels that each got.

#8599 [release] Update brave-core to 1.62.128.
  package-lock.json
  package.json
Labels: QA/No

#8612 Fix #8374: Cursor is misplaced for a selected URL when that URL doesn't fit the screen
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift
Labels: bug

#8615 Fix #8614: Playlist auto download not working
  Sources/Data/models/PlaylistItem.swift
  Sources/Playlist/PlaylistDownloadManager.swift
  Sources/Playlist/PlaylistManager.swift
Labels: QA/Yes, Epic: Playlist

#8611 Fix #8565: Re-enable Screen-Time.
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+ScreenTime.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+TabManagerDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift
  Sources/Brave/Frontend/ClientPreferences.swift
  Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/OtherPrivacySettingsSectionView.swift
Labels: QA/Yes

#8595 Fix #8137: Asset detail v2
  Sources/BraveWallet/Assets.xcassets/Empty States/account-empty.imageset/Contents.json
  Sources/BraveWallet/Assets.xcassets/Empty States/account-empty.imageset/account-empty-dark.png
  Sources/BraveWallet/Assets.xcassets/Empty States/account-empty.imageset/account-empty-dark@2x.png
  Sources/BraveWallet/Assets.xcassets/Empty States/account-empty.imageset/account-empty-dark@3x.png
  Sources/BraveWallet/Assets.xcassets/Empty States/account-empty.imageset/account-empty-light.png
  Sources/BraveWallet/Assets.xcassets/Empty States/account-empty.imageset/account-empty-light@2x.png
  Sources/BraveWallet/Assets.xcassets/Empty States/account-empty.imageset/account-empty-light@3x.png
  Sources/BraveWallet/Assets.xcassets/Empty States/transaction-empty.imageset/Contents.json
  Sources/BraveWallet/Assets.xcassets/Empty States/transaction-empty.imageset/transaction-empty-dark.png
  Sources/BraveWallet/Assets.xcassets/Empty States/transaction-empty.imageset/transaction-empty-dark@2x.png
  Sources/BraveWallet/Assets.xcassets/Empty States/transaction-empty.imageset/transaction-empty-dark@3x.png
  Sources/BraveWallet/Assets.xcassets/Empty States/transaction-empty.imageset/transaction-empty-light.png
  Sources/BraveWallet/Assets.xcassets/Empty States/transaction-empty.imageset/transaction-empty-light@2x.png
  Sources/BraveWallet/Assets.xcassets/Empty States/transaction-empty.imageset/transaction-empty-light@3x.png
  Sources/BraveWallet/Crypto/Accounts/AccountView.swift
  Sources/BraveWallet/Crypto/Asset Details/AssetDetailHeaderView.swift
  Sources/BraveWallet/Crypto/Asset Details/AssetDetailView.swift
  Sources/BraveWallet/Crypto/Portfolio/PortfolioHeaderView.swift
  Sources/BraveWallet/Crypto/Stores/AssetDetailStore.swift
  Sources/BraveWallet/Crypto/Transactions/TransactionsListView.swift
  Sources/BraveWallet/WalletPromptView.swift
  Sources/BraveWallet/WalletStrings.swift
  Tests/BraveWalletTests/AssetDetailStoreTests.swift
Labels: unverified-commits, puLL-Merge

#8609 Fix #8608: Authenticate when disabling browser lock
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/Brave/Frontend/Settings/Shields/OptionToggleView.swift
  Sources/Brave/Frontend/Settings/Tabs/PrivateTabsView.swift
Labels: sec-low

#8626 Fix #8070: Support 'Clean Copy Link' from Sharesheet
  Sources/Brave/Frontend/Browser/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+ShareActivity.swift
  Sources/Brave/Frontend/Share/AddFeedToBraveNewsActivity.swift
  Sources/Brave/Frontend/Share/AddSearchEngineActivity.swift
  Sources/Brave/Frontend/Share/AddToFavoritesActivity.swift
  Sources/Brave/Frontend/Share/CreatePDFActivity.swift
  Sources/Brave/Frontend/Share/FindInPageActivity.swift
  Sources/Brave/Frontend/Share/PageZoomActivity.swift
  Sources/Brave/Frontend/Share/ReportWebcompatIssueActivity.swift
  Sources/Brave/Frontend/Share/RequestDesktopSiteActivity.swift
  Sources/Brave/Frontend/Share/SendTabToSelfActivity.swift
Labels: enhancement, puLL-Merge

#8591 Fix #8521: ASA Custom Onboarding Feature Linkage
  App/iOS/Delegates/AppDelegate.swift
  App/iOS/Delegates/SceneDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+BraveTalk.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Callout.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+DownloadQueueDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+FindInPageDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+IPFSScheme.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+KeyCommands.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Keyboard.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Menu.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Onboarding.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+OpenSearch.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+P3A.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Playlist.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+ProductNotification.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+ReaderMode.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+TabManagerDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+ToolbarDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+UIDropInteractionDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+WKDownloadDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Wallet.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Web3NameService.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Widgets.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/Search/OpenSearchEngineButton.swift
  Sources/Brave/Frontend/ClientPreferences.swift
  Sources/Brave/Frontend/Settings/Debug/RetentionPreferencesDebugMenuViewController.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/BraveShared/Extensions/URLSessionExtensions.swift
  Sources/BraveStrings/BraveStrings.swift
  Sources/Growth/DAU.swift
  Sources/Growth/URP/AdAttributionReportData.swift
  Sources/Growth/URP/AttributionManager.swift
  Sources/Growth/URP/UrpService.swift
  Sources/Growth/URP/UserReferralProgram.swift
  Sources/Onboarding/Welcome/WelcomeViewCallout.swift
  Sources/Onboarding/Welcome/WelcomeViewController.swift
  Sources/Preferences/GlobalPreferences.swift
Labels: enhancement, Epic: Retention, puLL-Merge

#8651 Fix #8650: Fix SSL Status on Offline pages and Http pages
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/Helpers/ErrorPageHelper.swift
  Sources/Brave/Frontend/Browser/Interstitial Pages/NetworkErrorPageHandler.swift
Labels: QA/Yes

#8654 Fix #8649: Improve Performance of Select Token to Send
  Sources/BraveWallet/Crypto/BuySendSwap/SendTokenView.swift
  Sources/BraveWallet/Crypto/SelectAccountTokenView.swift
  Sources/BraveWallet/Crypto/Stores/SelectAccountTokenStore.swift
  Sources/BraveWallet/Extensions/RpcServiceExtensions.swift
  Tests/BraveWalletTests/SelectAccountTokenStoreTests.swift
Labels: puLL-Merge

#8632 Fix 8630: Disable Button Search Suggestion Opt-in not updating
  Sources/Brave/Frontend/Browser/Search/SearchViewController.swift
Labels: bug

#8666 Fix #8665: Fix an issue where URL won't load if already loaded in a different mode
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Rewards.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/TabManager.swift
Labels: QA/Yes

#8670 Ref #8647: Fix crash when loading invalid URLs
  Sources/Data/models/Model.xcdatamodeld/.xccurrentversion
Labels: bug

#8681 No Bug: Brave Talk logs update
  Sources/Brave/Frontend/Settings/Debug/BraveTalkLogsView.swift
  Sources/Brave/Frontend/Settings/Debug/BraveTalkLogsViewController.swift
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
Labels: QA/No

#8685 [release] Update brave-core to 1.62.149
  package-lock.json
  package.json
Labels: QA/No

#8686 No Bug: Wrong localized string key.
  Sources/BraveWallet/WalletStrings.swift
Labels: QA/No

#8659 Fix #8600: Accounts Tab v2
  Sources/BraveWallet/Crypto/Accounts/AccountsView.swift
  Sources/BraveWallet/Crypto/Accounts/Details/AccountDetailsView.swift
  Sources/BraveWallet/Crypto/AssetIconView.swift
  Sources/BraveWallet/Crypto/CryptoTabsView.swift
  Sources/BraveWallet/Crypto/MainMenuView.swift
  Sources/BraveWallet/Crypto/MultipleAssetIconsView.swift
  Sources/BraveWallet/Crypto/MultipleNetworkIconsView.swift
  Sources/BraveWallet/Crypto/NetworkSelectionRootView.swift
  Sources/BraveWallet/Crypto/Portfolio/PortfolioView.swift
  Sources/BraveWallet/Crypto/Stores/AccountsStore.swift
  Sources/BraveWallet/Crypto/Stores/CryptoStore.swift
  Sources/BraveWallet/Crypto/Transaction Confirmations/PendingTransactionView.swift
  Sources/BraveWallet/Crypto/Transaction Confirmations/SaferSignTransactionContainerView.swift
  Sources/BraveWallet/Extensions/BraveWalletExtensions.swift
  Sources/BraveWallet/MultipleCircleIconView.swift
  Sources/BraveWallet/NetworkIcon.swift
  Sources/BraveWallet/Preview Content/MockStores.swift
  Sources/BraveWallet/WalletStrings.swift
  Sources/DesignSystem/Icons/Symbols.xcassets/leo.web3.blockexplorer.symbolset/Contents.json
  Tests/BraveWalletTests/AccountsStoreTests.swift
Labels: puLL-Merge

#8581 Add Release Notes for iOS Release 1.60
  CHANGELOG.md
Labels: QA/No, CI/skip

#8680 Fix #8664: Add content blocker to upgrade passive mixed content
  Package.swift
  Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift
  Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift
  Sources/Brave/WebFilters/ContentBlocker/Lists/mixed-content-upgrade.json
Labels: needs security review

#8691 Add Release Notes for iOS Release 1.60.1
  CHANGELOG.md
Labels: QA/No, CI/skip

#8693 Fix #8607: Add 1.62 translations.
  Sources/BraveShields/Resources/de.lproj/BraveShared.strings
  Sources/BraveShields/Resources/es.lproj/BraveShared.strings
  Sources/BraveShields/Resources/fr.lproj/BraveShared.strings
  Sources/BraveShields/Resources/id-ID.lproj/BraveShared.strings
  Sources/BraveShields/Resources/it.lproj/BraveShared.strings
  Sources/BraveShields/Resources/ja.lproj/BraveShared.strings
  Sources/BraveShields/Resources/ko-KR.lproj/BraveShared.strings
  Sources/BraveShields/Resources/ms.lproj/BraveShared.strings
  Sources/BraveShields/Resources/nb.lproj/BraveShared.strings
  Sources/BraveShields/Resources/pl.lproj/BraveShared.strings
  Sources/BraveShields/Resources/pt-BR.lproj/BraveShared.strings
  Sources/BraveShields/Resources/ru.lproj/BraveShared.strings
  Sources/BraveShields/Resources/sv.lproj/BraveShared.strings
  Sources/BraveShields/Resources/tr.lproj/BraveShared.strings
  Sources/BraveShields/Resources/uk.lproj/BraveShared.strings
  Sources/BraveShields/Resources/zh-TW.lproj/BraveShared.strings
  Sources/BraveShields/Resources/zh.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/de.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/es.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/fr.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/id-ID.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/it.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/ja.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/ko-KR.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/ms.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/nb.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/pl.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/pt-BR.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/ru.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/sv.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/tr.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/uk.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/zh-TW.lproj/BraveShared.strings
  Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
  Sources/BraveWallet/Resources/de.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/es.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/fr.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/id-ID.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/it.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/ja.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/ko-KR.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/ms.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/nb.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/pl.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/pt-BR.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/ru.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/sv.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/tr.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/uk.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/zh-TW.lproj/BraveWallet.strings
  Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
Labels: puLL-Merge

#8698 Fix #8688: Fix URL-Bar not updating sometimes to show the latest cert status
  Sources/Brave/Frontend/Browser/BrowserViewController/BVC+WKNavigationDelegate.swift
  Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController.swift
  Sources/Brave/Frontend/Browser/Helpers/ErrorPageHelper.swift
  Sources/Brave/Frontend/Browser/Interstitial Pages/CertificateErrorPageHandler.swift
  Sources/Brave/Frontend/Browser/Tab.swift
  Sources/CertificateUtilities/BraveCertificateUtils.swift
Labels: bug, QA/Yes

#8706 Fix #8705: Add display for version info
  Sources/Brave/Frontend/Settings/SettingsViewController.swift
  Sources/BraveStrings/BraveStrings.swift
Labels: QA/Yes

#8682 Fix #8516: Add Open in Brave to iOS Share Sheet Action (Action Extension)
  App/ActionExtension/ActionExtension.plist
  App/ActionExtension/ActionExtensionIcons.xcassets/ActionExtensionIcons.appiconset/Contents.json
  App/ActionExtension/ActionExtensionIcons.xcassets/ActionExtensionIcons.appiconset/brave-icon-outline.png
  App/ActionExtension/ActionExtensionIcons.xcassets/Contents.json
  App/ActionExtension/ActionToBraveViewController.swift
  App/ActionExtension/de.lproj/InfoPlist.strings
  App/ActionExtension/en.lproj/InfoPlist.strings
  App/ActionExtension/es.lproj/InfoPlist.strings
  App/ActionExtension/fr.lproj/InfoPlist.strings
  App/ActionExtension/id-ID.lproj/InfoPlist.strings
  App/ActionExtension/it.lproj/InfoPlist.strings
  App/ActionExtension/ja.lproj/InfoPlist.strings
  App/ActionExtension/ko-KR.lproj/InfoPlist.strings
  App/ActionExtension/ms.lproj/InfoPlist.strings
  App/ActionExtension/nb.lproj/InfoPlist.strings
  App/ActionExtension/pl.lproj/InfoPlist.strings
  App/ActionExtension/pt-BR.lproj/InfoPlist.strings
  App/ActionExtension/ru.lproj/InfoPlist.strings
  App/ActionExtension/sv.lproj/InfoPlist.strings
  App/ActionExtension/tr.lproj/InfoPlist.strings
  App/ActionExtension/uk.lproj/InfoPlist.strings
  App/ActionExtension/zh-TW.lproj/InfoPlist.strings
  App/ActionExtension/zh.lproj/InfoPlist.strings
  App/Client.xcodeproj/project.pbxproj
  App/Client.xcodeproj/xcshareddata/xcschemes/ActionExtension.xcscheme
Labels: enhancement, puLL-Merge
